### ISSUE TITLE
newbie: installation method

### ISSUE THREAD

**Issue by mmiat** [propelorm/Propel2#1003]
using composer or downloading full package give me 2 different content
searching into folders, it seems to me that full package doesn't have symform and other libraries
is this correct? if so, why is it called "full"? thanks

**Comment by cristianoc72** [comment]
Propel relies to some third part libraries. If you install Propel from
.tar.gz you should manually install all the dependencies.
Personal opinion: don't waste your time, use composer!
Il 04/ott/2015 18:25, "mmiat" <notifications@github.com> ha scritto:

**Comment by mmiat** [comment]
ok thanks
but I suggest to rename "full" package with something other, a newbie like me could be tricked
