### ISSUE TITLE
propel init

### ISSUE THREAD

**Issue by mmiat** [propelorm/Propel2#1004]
I've a database, and I've tried to launch "propel init", that creates Base and Map folders and many php files. And then? I've read documentation but it doesn't explain how to start with a blank file: what I have to include?

**Comment by cristianoc72** [comment]
http://propelorm.org/documentation/02-buildtime.html
Paragraph "Runtime connection settings".
Il 04/ott/2015 18:27, "mmiat" <notifications@github.com> ha scritto:

**Comment by mmiat** [comment]
thanks but I still dont' understand
1. I create a folder called test, and using composer now I've composer.json and composer.phar files and vendor folder
2. I've yet a populated database, so I've launched "propel init" and now I've propel.yml and schema.xml
3. I've launched model:build and it creates many php files in my root, and folders Base and Map
4. I've launched config:convert and now I've generated-conf folder too

This is my test folder:
<pre>\Base
\generated-conf
\Map
\vendor
Articoli.php
ArticoliQuery.php
composer.json
composer.phar
propel.yml
schema.xml</pre>

now I create a test.php file:

<pre>
// setup the autoloading
require_once 'vendor/autoload.php';

// setup Propel
require_once 'generated-conf/config.php';

$articolo = new Articoli();
echo $articolo->getId();
</pre>

and I've:
<pre>Fatal error: Class 'Articoli' not found in D:\xampp\htdocs\propel\test.php on line 9</pre>

**Comment by mpscholten** [comment]
What's the content of your `composer.json`? I guess the autoloader is not configured properly, from the docs: "After generating the classes, you have to autoload them. For example, with composer this can be achieved with: [...] and then executing the command composer dump-autoload. See also namespaces recipe if you prefer to autoload your model classes following PSR-0." (http://propelorm.org/documentation/02-buildtime.html)

**Comment by mpscholten** [comment]
Here's how your `composer.json` should look like:

```
{
    // ... some other stuff
    "autoload": {
        "psr-4": {"YourNameSpace\\": "src/"}
    }
}
```

`YourNameSpace` should be replaced with whatever you responded to `Which namespace should the generated php models use?` during the `propel init` step. If you don't know this anymore you can check your `schema.xml`, at the top of this file should be a `namespace` attribute. 

After you've done this run `composer dump-autoload` and everything should be working :)

**Comment by mmiat** [comment]
mmm, I created my composer.json reading here: http://propelorm.org/documentation/01-installation.html

so it contains only:

<pre>{
    "require": {
        "propel/propel": "~2.0@dev"
    }
}</pre>

and in schema.xml there is no namespace's field

**Comment by mmiat** [comment]
now I've copied my schema.xml on http://sandbox.propelorm.org/, create a new example, downloaded it, put in a new folder, made a new install, then launched model:build and config:convert and now it works. I don't know how.... :P

**Comment by mpscholten** [comment]
Great :) In case you've more issues you can reach many propel users [via gitter](https://gitter.im/propelorm/Propel). I guess this issue can be closed then, right?

**Comment by mmiat** [comment]
I think so
