### ISSUE TITLE
download examples

### ISSUE THREAD

**Issue by mmiat** [propelorm/Propel2#1005]
are there some working examples that I can download? thanks

**Comment by Big-Shark** [comment]
Open http://sandbox.propelorm.org/example/bookstore and click "Download as zip"

**Comment by mmiat** [comment]
very well, thanks!
I think I need to place it in the root folder, with vendor folder downloaded with composer, right?

**Comment by Big-Shark** [comment]
yes

**Comment by Big-Shark** [comment]
yes

**Comment by mmiat** [comment]
perfect, thanks!
