### ISSUE TITLE
Not saving default value set in schema.xml

### ISSUE THREAD

**Issue by jsbjair** [propelorm/Propel2#1012]
if i set a default value to an attribute and try to save without change that value, the value isn't saved, because on method  doInsert, there is a check when is creating a sql query  
```php
        if ($this->isColumnModified(UserTableMap::COL_PROFILE)) {
            $modifiedColumns[':p' . $index++]  = 'profile';
        }
```
that will jump that attribute insertion, i have to put  
```php
 $this->modifiedColumns[UserTableMap::COL_PROFILE] = true;
```
i think this logic could be used only on doUpdate

**Comment by marcj** [comment]
There is no need to save default values in INSERT statement as the database knows already what the default is and places in that column the defined value. What do you think is wrong here?

**Comment by jsbjair** [comment]
@marcj, was my fault, when i changed the schema.xml, to put a default value in a column, i regenerated the model, but didn't regenerate the sql.
