### ISSUE TITLE
Inline assigment should be avoided

### ISSUE THREAD

**Issue by dereuromark** [propelorm/Propel2#1019]
There is even an error in there because of that:

In Generator DelegateBehavior:
```
if (is_callable(array('$ARFQCN', \$name))) {
    if (!\$delegate = \$this->get$relationName()) {
        \$delegate = new $ARClassName();
        \$this->set$relationName(\$delegate);
    }

    return call_user_func_array(array(\$delegate, \$name), \$params);
}";
```

The `if (!\$delegate = \$this->get$relationName()) {` makes assignment and negation in an unexpected order and leads to undesired behavior.

This should read (and then work as expected):
```
\$delegate = \$this->get$relationName();
if (!\$delegate) {
```

**Comment by marcj** [comment]
Thanks for reporting this issue. Would you like to create a [Pull-Request](https://help.github.com/articles/using-pull-requests/)?

**Comment by dereuromark** [comment]
Yes I will do that.
Those bugs are quite severe and that !$x = $y behavior should be fixed asap.

**Comment by dereuromark** [comment]
Can you maybe add Travis for PRs, too?
