### ISSUE TITLE
Pagination wrong if no results

### ISSUE THREAD

**Issue by ktounet** [propelorm/Propel2#1025]
Hi, there is a problem with the last page if there is no result.

```php
$pager = $query->paginate(1, 100);

var_dump($pager->getNbResults()); // 0
var_dump($pager->getPage()); // 1
var_dump($pager->getFirstPage()); // 1
var_dump($pager->getLastPage()); // 0
```

It is not logical that the current page and the first page are greater than the last page !
The value of last page should be equal to 1.

**Comment by marcj** [comment]
Yeah, rather seems like we should return everywhere 0 if there aren't any results?

**Comment by ktounet** [comment]
Yes, it would be even better :+1:
