### ISSUE TITLE
Undefined index: name in Propel/Runtime/Util/Profiler.php

### ISSUE THREAD

**Issue by williamlang** [propelorm/Propel2#1028]
When running propel diff I get a notice 

PHP Notice:  Undefined index: name in vendor/propel/propel/src/Propel/Runtime/Util/Profiler.php on line 206

And yet, if I give the section a name I get this error:

  [Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]
  Unrecognized option "name" under "propel.runtime.profiler.details.time"

The docs on propelorm.org here: http://propelorm.org/documentation/07-logging.html#tweaking-the-profiling-information-at-runtime show the name being set programmatically but cannot be set via config.

**Comment by Big-Shark** [comment]
Are you using version alpha4?

**Comment by Big-Shark** [comment]
https://github.com/propelorm/Propel2/commit/097b2137be31cb9e45ca1f853b7a8ff22c6364e8 
This is fixed, but it will only be in the alpha 5

**Comment by williamlang** [comment]
According to my composer.lock I am using alpha 5

{
            "name": "propel/propel",
            "version": "2.0.0-alpha5",
            "source": {
                "type": "git",
                "url": "https://github.com/propelorm/Propel2.git",
                "reference": "75f775cf6de41595d1240885eea5fa5d475d228d"
            },

**Comment by Big-Shark** [comment]
Try dev-master version.

**Comment by williamlang** [comment]
That worked.

Thank you!
