### ISSUE TITLE
Propel Not adding `` around reserved word column names

### ISSUE THREAD

**Issue by SamNicholson** [propelorm/Propel2#1036]
Propel let me create a column named "interval" however then whenever making queries with this column it did not surround the column name with `` to escape the fact it is a reserved word - 

Propel gave me the following error - 

Unable to execute INSERT statement [INSERT INTO server (id, name, address, interval) VALUES (:p0, :p1, :p2, :p3)]

In my schema the column was defined as - 
<column name="interval" type="integer" required="true"/>

I guess it either shouldn't let me create that column or know to escape the name?

**Comment by marcj** [comment]
Per default it does not quote identifiers because this leads to unexpected behavior in many databases. You can activate it per table or per database using `<table identifierQuoting ="true">` (http://propelorm.org/documentation/reference/schema.html#table-element)
