### ISSUE TITLE
Problem on update if one of PK fields changed

### ISSUE THREAD

**Issue by canyildiz** [propelorm/Propel2#1054]
Hi all,

I have a table which has a PK field as combination of three fields. When I wanted to update an entity in this table I saw it's not updating. Then I reversed some and found a problem in **_buildPkeyCriteria_** method.  When building PK key, criteria is generated using _**$this->fieldName**_ attributes which return the new values of fields, so entity cannot be found in database.

Let me tell this with an example:

Original Row: 
```json
{
  "pk_field_1" 	: "a",
  "pk_field_2"	: "b",
  "pk_field_3"	: "c",
  "field_4"		: "d",
  "field_5"		: "e"
}
```

Updated Data: 
```json
{
  "pk_field_1" 	: "a",
  "pk_field_2"	: "bbbb",
  "pk_field_3"	: "c",
  "field_4"		: "ddddd",
  "field_5"		: "e"
}
```

Generated update query:
```sql
UPDATE `someTable` 
SET `pk_field_2` = 'bbbb', `field_4` = 'ddddd'
WHERE `pk_field_1` = 'a' AND `pk_field_2`='bbbb' AND `pk_field_3` = 'c';
```

Thanks,
Can

**Comment by marcj** [comment]
Yes, this is a current limitation. Use a unique instead and a primary key which is auto-incremented. However, In the `data-mapper` branch this is supported.
