### ISSUE TITLE
Model updating is slow

### ISSUE THREAD

**Issue by drodil** [propelorm/Propel2#1066]
Hi,

When schema with multiple external schemas has very many tables the model updating is getting very slow. Would it be possible to create some kind of timestamp cache for the external schemas and update only the ones that have been changed? There might be issue with this when using custom behaviors but otherwise I think it would speed up the model updating a lot. What do you think?

**Comment by staabm** [comment]
could you provide a small code snippet which exactly shows what "is slow"?

**Comment by drodil** [comment]
I have around 300 tables in database which are defined in 21 different external schemas. When I run the model:build command it takes around 2 minutes on my quite good computer (Intel Core i7, SSD drive, 16GB memory etc.) even nothing has changed in the external schema files. 

It takes a bit too long to change just some attribute or add new column to some table. This mirrors to the Continous Integration system we are using to verify changes so that the build times are also 2 minutes longer for changes that did not do anything for the schemas.

**Comment by staabm** [comment]
Would you mind profilling the CLI run, so we can see where most time is spent?

https://blackfire.io/docs/cookbooks/profiling-cli

**Comment by drodil** [comment]
Sure thing, here is the profiled model build: https://blackfire.io/profiles/dd03dc97-cdc6-4f6f-bbcf-899cdc5b6918/graph

**Comment by staabm** [comment]
@drodil could you give this change a try?
https://github.com/staabm/Propel2/commit/aafa585dde5127b0976ed234be1ecb6226d207d5

also creating another profile with the patch included would be perfect.

**Comment by staabm** [comment]
pushed a followup, please ignore the one mentioned above:
https://github.com/staabm/Propel2/commit/f8fbe1ce1843f28c97f46b95fd53659afbdd947b

**Comment by drodil** [comment]
Hi,

Some improvement in performance with that commit. The model generation time dropped from 2 minutes and 13 seconds to 1 minute and 40 seconds. Here is the profiled run with that change: https://blackfire.io/profiles/35114fdc-8aec-4ea2-ba31-e88d8bec865e/graph

It's good direction but still wondering if there was possibility to check for external schema changes somehow. Don't want to go and do some special shell script or so for that.

**Comment by staabm** [comment]
what do you mean by "external schema changes"?

**Comment by staabm** [comment]
is the source of the `XSSBehaviour` open source?

**Comment by staabm** [comment]
@drodil I just realised in your perf profile that you have xdebug enabled on CLI. please disable it and run it again. I expect a speed improvement of 30-60% only by not loading xdebug. read: you must not load the extension, only disabling it will cost you performance even if all features are disabled.

**Comment by drodil** [comment]
Here is the profile of the latest patch staabm@7d8bafb and without xdebug: https://blackfire.io/profiles/c9325e64-6c88-4db6-a4f6-d230c1171fb3/graph

**Comment by staabm** [comment]
In comparison to 2min 13sec this seems to be a big step forwards, nice. Would you do me the favour and profile your app for each of the linked PRs with and without the PRs patch applied?

**Comment by drodil** [comment]
It's very good improvement! And answer to your question; XSSBehavior is not open source. I will make the profiles for you tomorrow, no time left today.

**Comment by staabm** [comment]
Further inspection of your lost profile brought me to the conclusion that most of the remaining slowdown is triggered by a `entity_cache_purge` behaviour.

especially the method `EntityCachePurgeBehaviour->replaceRelationSet()` uses `PhpParser->findMethod` extensively, which seem sto be the culprit in your particular case.

**Comment by drodil** [comment]
Hi,

Did some profiling for you and here are the results. Seems like the other PR does not affect the time almost at all. 

Changes | Time | Profile
-------------|--------|----------
staabm@7d8bafb and staabm@e87db60 | 1min, 9 seconds | https://blackfire.io/profiles/96ce28dd-51f1-4190-bf9a-00b648ecae58/graph
staabm@7d8bafb | 1min, 8 seconds | https://blackfire.io/profiles/a4370ced-9a4a-43b9-96a5-682b172acc9b/graph
No changes | 1min, 43 seconds | https://blackfire.io/profiles/2da713fb-72f9-4aec-baa7-5db70b55246b/graph

And yes, EntityCachePurgeBehavior uses the findMethod very much as it goes through all related tables and replaces setters if the related table has specific behavior enabled. Don't really know if there is something I can do to that functionality later on but it seems that your first change is speeding up the process already.

Also what I was earlier meaning by external schema checking means that when I have the following line in schema.xml:

```
<external-schema filename="db/schema/framework.xml"/>
```

It would be good only to process that schema if it has changed from last build. I am proposing using PHPs file_md5 and filemtime and store them upon model generation to somewhere (maybe specify some cache directory in schema?) and then compare those when looping through external schemas and skipping the ones that have not been changed.

**Comment by staabm** [comment]
@drodil thx for those numbers. Unfirtunately I wasn clear enough what I expected from you, sorry about that.
Could you please profile the changes of the above linked PRs, namely https://github.com/propelorm/Propel2/pull/1070 https://github.com/propelorm/Propel2/pull/1069

Regarding the external schema: I have to think about it

**Comment by drodil** [comment]
Sure, I run the profiles for #1069 but I don't think there is need to do the profiling for #1070 as it basically just warns the user about the xdebug; you agree?

I will check if I can modify the behavior to run a bit faster with your comment, lets see :) Thanks!

**Comment by staabm** [comment]
@drodil thx. I agree that the change in #1069 itself doesnt need to be profilled. would only be good to see the difference in runtime if xdebug is enabled or not (which is the assumption the change in the PR is based on)

**Comment by drodil** [comment]
Hi

We are using git as our repository for our project so I decided to make small bash script to check if schema or our custom behaviors have been changed before running the schema update. Here it is:

```bash
#!/bin/bash

# Default env to dev
ENV=dev

# Check environment
for i in "$@"
do
case $i in
    -e=*|--env=*)
    ENV="${i#*=}"
    ;;
esac
done

echo "Running schema model update in $ENV environment"

# Different check for dev and ci environments to get changed files
if [ $ENV == ci ] ; then
    files=(`echo $(git diff --diff-filter=ACMRTUXB --name-only HEAD~1 HEAD) | tr " " "\n"`)
else
    # In dev env, we must check for added and changed files
    added_files=(`echo $(git ls-files --others --exclude-standard) | tr " " "\n"`)
    changed_files=(`echo $(git diff --name-only HEAD) | tr " " "\n"`)
    files=( "${added[@]}" "${changed_files[@]}" )
fi

# Flag if the schema update is needed
run_update=false

# If no files changed, force the update
if [ ${#files[@]} -eq 0 ]; then
    echo "No files changed"
    run_update=true
else
    echo "Files changed: $(printf ", %s" ${files[@]})"

    # Loop filelist and find out if schema or behaviors have changed
    for i in "${files[@]}"
    do
        :
        # Schame dir is db/schema and behaviors are in framework/database/propel folder
        if  [[ $i == db/schema* ]] || [[ $i == framework/database/propel* ]] ;
        then
            run_update=true
            break
        fi
    done
fi

if [ "$run_update" == true ] ; then
    echo "Running schema update"
    php vendor/propel/propel/bin/propel.php build --verbose --recursive --output-dir . --config-dir db/ --schema-dir db/schema
else
    echo "No schema changes, skipping update"
fi
```
