### ISSUE TITLE
models with column names that are keywords cause errors

### ISSUE THREAD

**Issue by williamlang** [propelorm/Propel2#1076]
I am using MySQL. I have a column called "index" -- because "index" is a keyword in MySQL and the generated queries don't enclose column names in the backtick (`) you get a MySQL error.

PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'index ....

**Comment by Big-Shark** [comment]
http://propelorm.org/documentation/reference/configuration-file.html 
Add key `disableIdentifierQuoting` in config file and set 'true'

**Comment by williamlang** [comment]
You da real mvp.

Thank you!

**Comment by williamlang** [comment]
I actually had to set this in my schema.xml in the database tag to get this to work.

I ended up getting a message 'invalid configuration option 'propel.generator.objectModel'

**Comment by phlopsi** [comment]
@williamlang As far as i can see in the documented configuration, there is no objectModel, just packageObjectModel.
Look here: http://propelorm.org/documentation/reference/configuration-file.html#generator-settings

**Comment by marcj** [comment]
Not in the configuration but in the actual schema.xml. And please do it only per table, activating this quoting per default for all tables leads in strange behavior and shouldn't be activated. `<table identifierQuoting="true">`
