### ISSUE TITLE
Symfony 3 issues

### ISSUE THREAD

**Issue by venata** [propelorm/Propel2#1080]
Fatal error: Class 'Symfony\Component\Console\Helper\DialogHelper' not found in ....vendor\propel\propel\src\Propel\Generator\Command\Helper\DialogHelper.php on line 8

Symfony 3 is missing the DialogHelper

**Comment by moh-abk** [comment]
Getting this too :-1:

**Comment by SCIF** [comment]
@moh-abk , @venata you can branch "issue-1080" in my repo even PR not merged yet.
