### ISSUE TITLE
Update symfony components to version 3

### ISSUE THREAD

**Issue by gossi** [propelorm/Propel2#1083]
I just updated my symfony components to version 3. During install it says that propel requires some of them in version `~2.3`. So what I did was requiring both versions:

```
{
    "require": {
        "symfony/config": "~3||~2"
    }
}
```

which actually kinda sucks. So I was wondering about whether propel would also leap towards symfony components v3?

**Comment by stevleibelt** [comment]
As end user, I don't see any problems with using "~3||~2.3" as long as the API from Symfony that Propel uses is not breaking, this is a fine approach to support older installations. Symfony 2.x can be used with old php 5.3.9 while 3.x needs 5.5.9.
As long as code from the newer Symfony is not needed, why requiring it?

**Comment by gossi** [comment]
Already changed in master. I will close my own issue.
