### ISSUE TITLE
 i18n setLocale binding model. Global configuration?

### ISSUE THREAD

**Issue by Breezess** [propelorm/Propel2#1086]
Users select the language. To bind setLocale model in order to obtain data. Are improve the look？

**Comment by marcj** [comment]
Sorry, I don't get what you want. Can you please try to explain it in more detail?

**Comment by Breezess** [comment]
@marcj 
http://sandbox.propelorm.org/64c26cb

see
// setLocale($QueryUserLang);
// $items = ItemQuery::create()->find();
// foreach ($items as $i) {
//  echo $i->getPrice(); // 12.99
//  echo $i->getName(); // Microwave oven not show en_US ? show fr_FR
// }

**Comment by gossi** [comment]
I'm working on a behavior to achieve that. See here: https://github.com/gossi/propel-l10n-behavior

Will be released this week.

**Comment by gossi** [comment]
It's released: https://packagist.org/packages/gossi/propel-l10n-behavior

**Comment by dereuromark** [comment]
Maybe this could be linked from docs? PR welcome.
Closing for now
