### ISSUE TITLE
Should be able to select a subset of fields and populate the activerecord model

### ISSUE THREAD

**Issue by bpicolo** [propelorm/Propel2#1095]
It should be possible to utilize select(array('subset', 'of', 'fields')) and also go through serialization stages that models go through.

In addition, using a specific formatter (e.g. ObjectFormatter) with select() fails for totally not-obvious reasons (it literally just goes through formatting expecting all the fields to exist)

**Comment by marcj** [comment]
There's no way to hydrate a object with limited informations yet. This would make it necessary that any column is dynamically lazy-load which is only in the `data-mapper` implemented.
