### ISSUE TITLE
Events pre/postSave. Ability to know values before modification.

### ISSUE THREAD

**Issue by SCIF** [propelorm/Propel2#1096]
Current event models provide only next features: check if field had modified and know only new value. Also, it's limited only by `preSave()` event and you can access only new state of model on `postSave()`. I want to store changed fields and they «before» values through pre and post events. Any suggestions or objections?

**Comment by dhm80** [comment]
+1 for that ;)

**Comment by cristianoc72** [comment]
Afaik this feature is already implemented in 'data-mapper' branch. Isn't it
@marcj ?

2016-01-07 9:21 GMT+01:00 Ansas Meyer <notifications@github.com>:

**Comment by marcj** [comment]
Yes, it is. There's no way except to track old values setters on your own currently with Propel to retrieve the old values.

**Comment by SCIF** [comment]
I know that it doesn't allow now but i want to implement it without waiting ready of datamapper version.

**Comment by marcj** [comment]
You need to overwrite your setter and add new properties to your class which are being used to track the change.

**Comment by SCIF** [comment]
@marcj, of course i know this workaround but it seems really easy to implement values tracking as standart Propel feature. Why not? It will not introduce any disadvantage as i think.

**Comment by marcj** [comment]
That's a rather big change in the current version. I believe it's better to work on the data-mapper branch, where this is already possible.
