### ISSUE TITLE
Problem with QuickBuilder

### ISSUE THREAD

**Issue by gossi** [propelorm/Propel2#1098]
I'm developing a behavior and used the `QuickBuilder` for the TestSuite. Well, out of a sudden it stopped working for me. The error message I get is the following:

`Fatal error: Cannot redeclare class test\Base\ProductQuery in /private/var/folders/22/r4kt28011pn2pyx5wkgg_1gr0000gn/T/propelQuickBuild-2.0.0-dev-220ea8f62c/Product_ProductI18n.php on line 2508`

That's the version where every file is munged into one. I checked the generated code and didn't find an error. I also used my behavior on a private test project and it worked fine (various files are generated then).

It's easy to test for yourself: clone + run phpunit in the project root -> https://github.com/gossi/propel-l10n-behavior

**Comment by cristianoc72** [comment]
In your `ProductTest::setUp()` method write this:
```php
if (!class_exists('\Product')) {
    $schema = <<<EOF
<database name="l10n_behavior" namespace="test">
	<table name="product">
		<column name="id" required="true" primaryKey="true" autoIncrement="true" type="INTEGER" />
		<column name="title" type="VARCHAR" required="true" />
		
		<behavior name="l10n">
			<parameter name="i18n_columns" value="title" />
		</behavior>
	</table>
</database>
EOF;
		$this->getBuilder($schema)->build();
}

........
```
QuickBuilder always includes the generated classes, so that after the first test, if you run QuickBuilder again you redeclare your model classes twice.

**Comment by gossi** [comment]
Thank you, I see what's causing the problem now. I guess if `QuickBuilder` is using `include_once` instead of `include` this will cause other tests to fail, because some models are generated over and over again but with different combinations in the propel testsuite?

**Comment by Big-Shark** [comment]
@gossi using setUpBeforeClass instead setUp
I fixed a similar problem https://github.com/Big-Shark/Propel2/commit/758413522864c338c2522419302b59f442ec3da8

**Comment by gossi** [comment]
Wonderful, your help is much appreciated - thank you very much. Tests are running now. Propel will soon be enriched with a new behavior.
