### ISSUE TITLE
Technical Documentation for Builder in data-mapper branch?

### ISSUE THREAD

**Issue by gossi** [propelorm/Propel2#1100]
Is there a technical documentation for the new builder? I'm currently wrote my behavior for the old api but was interessted in the new one and how much I probably need to redo. The new one looks promising, yet by just shortly locking at it, it wasn't just clear to me. So I was wondering if there is a technical docu (maybe just in the wiki here as a start) that helps people jumpstart with the new builder? And also later for behavior authors?

**Comment by marcj** [comment]
You should probably take a look most core behaviors, which have already been adjusted.
