### ISSUE TITLE
Problem with timestamp data type in table

### ISSUE THREAD

**Issue by soend** [propelorm/Propel2#1117]
Hei, i have created_at field with timestamp datatype. I get hits error when i try to query data from that table:
`PHP Fatal error:  Uncaught exception 'Exception' with message 'DateTime::__construct(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone.' in /var/www/html_dev/dev/propel_test/vendor/propel/propel/src/Propel/Runtime/Util/PropelDateTime.php:90\nStack trace:\n#0 /var/www/html_dev/dev/propel_test/vendor/propel/propel/src/Propel/Runtime/Util/PropelDateTime.php(90): DateTime->__construct('2016-02-02 12:4...')\n#1 /var/www/html_dev/dev/propel_test/generated-classes/Base/Faction.php(483): Propel\\Runtime\\Util\\PropelDateTime::newInstance('2016-02-02 12:4...', NULL, 'DateTime')\n#2 /var/www/html_dev/dev/propel_test/generated-classes/Base/FactionQuery.php(168): Base\\Faction->hydrate(Array)\n#3 /var/www/html_dev/dev/prop in /var/www/html_dev/dev/propel_test/generated-classes/Base/Faction.php on line 495`

Any idea how i can fix this?

**Comment by marcj** [comment]
Yeah, you need to define in your php.ini the default timezone: http://www.unixmen.com/timezone-for-php-is-not-set-please-set-qdatetimezoneq-option-in-phpini/
