### ISSUE TITLE
Boolean getter with isCol()

### ISSUE THREAD

**Issue by gossi** [propelorm/Propel2#1118]
I do have some column names, that are prefixed with `is_*` because they are boolean. Now the methods generated for a column with name `is_system` are `setIsSystem()` and `getIsSystem()`, which is absoutely correct, yet ugly. I was wondering if there is a better mechanism to turn this into `setSystem()` and `isSystem()` as these would be my preferred method names in this case. What I'm looking for is probably a config option - for `propel.yaml` - which handles boolean column names and takes some values for different generation scenarios. Some that come to my mind:

- `set-get` - current generation scenario, should be the default
- `set-is` - same as explained above, applied to every boolean column
- `set-is-detect` - same as `setis` but only applied, when the column name starts with `is_*`

Suggestions?

**Comment by gharlan** [comment]
> Now the methods generated for a column with name is_system are setIsSystem() and getIsSystem()

There should be an alias `isSystem`. (#547 for isser, #593 for hasser)
