### ISSUE TITLE
Streamline Table/Entity get*Name() methods

### ISSUE THREAD

**Issue by gossi** [propelorm/Propel2#1121]
I'm using the model `Table` class lately. The get*Name() methods are very unconvenient and seem random, too. For examle there is `getCommonName()` which actually is the prefixed table name and then there is `getOriginCommonName()`, which returns the blank table name - so why is the common name the table name? So, looks like there was common name first and the somebody realized it didn't return what they expected and that's why there is origin common name? They don't feel like intuitive.
On the other hand there is `getPhpName()` which does what it says, I lately even realized `getCamelCaseName()`, which returns the `getPhpName()` as camel case, for easy use in variables, which is great, too.
After all, it is not very convenient to work with all these methods as they also follow different principles. I'd wish to have a more consistent API about names. Especially from a code generation point of view this can be very handy to collect all necessary getters, turn them into a convention and apply them on the other models as well (as far as they are present there).

**Comment by marcj** [comment]
Those name will be change with new data-mapper branch, beside that I don't see any miss-consistency that are worth to fix it. But if you want to try to make the API slimmer, feel free to provide a pull-request.
