### ISSUE TITLE
Impossible to force a value in an auto-increment column

### ISSUE THREAD

**Issue by supermamie** [propelorm/Propel2#1122]
I have several tables with primary key in auto-increment, but for some import of data, I have to set the ID by myself and propel does not allows it, throwing an error 

> 'Cannot insert a value for auto-increment primary key (' .$colConst . ')'
Here is the schema.xml for one of these tables : 

```xml
<table name="Patient" idMethod="native" phpName="Patient">
	<column name="IdPatient" phpName="IdPatient" type="INTEGER" primaryKey="true" autoIncrement="true" required="true"/>
	<column name="Name" phpName="Name" type="VARCHAR" size="30" required="true"/>
	<vendor type="mysql">
		<parameter name="Engine" value="InnoDB"/>
	</vendor>
</table>
```

The code adding this check seems to be in **Propel\Generator\Builder\Om\ObjectBuilder addDoInsertBodyRaw()**
```php
$script .= "
        if (null !== \$this->{$columnProperty}) {
            throw new PropelException('Cannot insert a value for auto-increment primary key (' . $constantName . ')');
        }";
```
There are 3 other points in the Generator where this exception can be generated so I'm not confident enough to propose a patch (it seems to be a feature and not a bug but... but... but I need to set the IDs by myself sometimes)

**Comment by staabm** [comment]
I guess we have this check, because providing a value for a auto-increment like column is not support X-DBMS

**Comment by marcj** [comment]
Have you tried the attribute `allowPkInsert`? http://propelorm.org/documentation/reference/schema.html#table-attributes -> last bullet point

**Comment by supermamie** [comment]
Seems I need to read the doc more.
Thanks a lot for your help !
