### ISSUE TITLE
Missing documentation about error handling?

### ISSUE THREAD

**Issue by ePirat** [propelorm/Propel2#1123]
I am looking for a while now but can't seem to find any documentation at all about error handling in Propel2. Specifically I am trying to figure out how to handle connection failures, I suspect some Exception is thrown but I can't find any documentation about which exception will be thrown and I don't want to blindly catch all exceptions.

I tried the API docs but it contains a lot of Exception Classes without any description whatsoever about them.

**Comment by marcj** [comment]
Propel only [extends PDO](https://github.com/propelorm/Propel2/blob/master/src/Propel/Runtime/Connection/PdoConnection.php#L19), so if there is a connection issue you will get regular PDO exception.
