### ISSUE TITLE
Allow private attributes in schema.xml

### ISSUE THREAD

**Issue by gossi** [propelorm/Propel2#1124]
I'd like to do the following:

```xml
<table name="user" namespace="\keeko\core\model" apiType="user/users">
-- or --
<table name="user" namespace="\keeko\core\model" x-apiType="user/users">
```

As you can see `apiType` is not an officially supported attribute. Yet I'd like to be able to use my own attributes, that I can read through the `Table` (rsp. `Entity`) model class.

**Comment by staabm** [comment]
Just a idea: in html5 custom attributes are notated by prepending `data-`. Maybe we could do something similar

**Comment by gossi** [comment]
I used `x-` as I've recently seen it in jsonapi (x = extension here), using `data-` is basically identical. Which API? What about:

```
$table->getData($field, $defaultValue = null);
$table->setData($field, $value);
```

**Comment by marcj** [comment]
I'm open for such change, but won't hold it as official issue/todo. So, if you want to provide a pull-request for this change, we'd very appreciate it.

**Comment by gossi** [comment]
Just talked with @marj that's what the `<vendor>` is for rsp. can be used as.
