### ISSUE TITLE
[MySQL] Allow to set sql_mode, and define a default (sql_mode=only_full_group_by)

### ISSUE THREAD

**Issue by marcj** [propelorm/Propel2#1129]
With new MySQL Versions they set "sql_mode=only_full_group_by" which breaks our group by sql generation, as MySQL acts now equally to PostgreSQL where it's not valid anymore to select plain columns which aren't in the GROUP BY statement. They need either to be in the SELECT surrounded by aggregation methods or in the GROUP BY statement itself.

Two solutions:

Add the https://github.com/propelorm/Propel2/blob/master/src/Propel/Runtime/Adapter/Pdo/PgsqlAdapter.php#L144-L171 code to MySQL now as well
or introduce a new `sql_mode` option where in its default the "only_full_group_by" is not active.

**Comment by marcj** [comment]
Or give a note where its possible through 'database.connections.<name>.query' to set it

```yaml
database:
  connections:
    default:
      query: ["set mode = ''"]
```

**Comment by marcj** [comment]
Or give a hint how they configure their MySQL settings

**Comment by oojacoboo** [comment]
I'm currently finding it very difficult to even use Propel with ONLY_FULL_GROUP_BY enabled.

My vote is for the first behavior, but that really abstracts away a lot of the logic which could have some really adverse effects.  From some of my testing, you're not going to end up with the same results from a previous query with ONLY_FULL_GROUP_BY disabled.  Adding columns to the GROUP BY, will sometimes result in extra rows, understandably.  Propel is no longer doing magic behind the scenes.  And placing aggregates on selects isn't very friendly with Propel if you want to use the default object formatters.

Frankly, I think a conversation needs to be had towards more of a DQL style DSL where more control can be placed on the SELECT and GROUP BY logic.  As it presently is, I know we're going to be writing a lot more custom SQL and having to build up collection manually with the formatters, possibly even writing a custom formatter.

**Comment by apmuthu** [comment]
There is no equivalent of` public function getGroupBy()` of Pgsql in [MySQL adapter](https://github.com/propelorm/Propel2/blob/master/src/Propel/Runtime/Adapter/Pdo/MysqlAdapter.php).

**Comment by vikassahu74590** [comment]
Codeigniter/php

when have no superior privileges of ### **[database]**
 this code on your query ONLY_FULL_GROUP_BY disable

for Mysql:-- use this code on your query )-

$set_mode = "SET sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''))"; $resultss = mysqli_query($this->dbh,$set_mode);

for codeigniter :-- use this code on your query )-

$this->db->query("SET sql_mode=(SELECT REPLACE(@@sql_mode, 'ONLY_FULL_GROUP_BY', ''));") ;

**Comment by dereuromark** [comment]
This should be solved on master for now.
