### ISSUE TITLE
Allow isNew value to be updated from Model::preSave()

### ISSUE THREAD

**Issue by TrogloGeek** [propelorm/Propel2#1137]
Given the following generated BaseModel::save() method:
```php
    public function save(ConnectionInterface $con = null)
    {
        if ($this->isDeleted()) {
            throw new PropelException("You cannot save an object that has been deleted.");
        }

        if ($con === null) {
            $con = Propel::getServiceContainer()->getWriteConnection(SupportTicketTableMap::DATABASE_NAME);
        }

        return $con->transaction(function () use ($con) {
            $isInsert = $this->isNew();
            $ret = $this->preSave($con);
[...]
```

Is there any reason why isNew status is fetched before calling Model::preSave()?
Inverting the two last quoted lines would allow a (non atomical) way to to prepare the DB record and then set isNew to false from Model::preSave() to transform the insert operation to an update.
I am aware that such usages would be dirty as hell, but it would allow doing such logic in a minimal overloading way, and I can't see any negative effect from inverting these two lines.

Currently, such logic requires to setNew(false) from Model::preSave(), then call again Model::save() from there, and finally return false to cancel parent save() on the call stack.

**Comment by marcj** [comment]
Did you try inverting it and run the test suite? If everything is green, then obviously we could go that way.

**Comment by TrogloGeek** [comment]
Seems good, but only checked with MySQL.

**Comment by marcj** [comment]
Great, merged :)
