### ISSUE TITLE
password not placed in generated propel.php configuration 

### ISSUE THREAD

**Issue by benbankes** [propelorm/Propel2#1139]
When using propel init to create an initial propel.php configuration file, the password that the user input via command line prompt is not included in the php configuration file.  However, it is included correctly in the propel.yml configuration file if that is chosen instead

**Comment by mpscholten** [comment]
Thanks for the report :) Could you check if https://github.com/propelorm/Propel2/pull/1140 fixes this?

**Comment by benbankes** [comment]
@mpscholten That fixed it.  Thanks!
