### ISSUE TITLE
pgsql unique constraint not removed

### ISSUE THREAD

**Issue by eelkevdbos** [propelorm/Propel2#1143]
Unique constraints are created by the propel migrator like this:

`CREATE UNIQUE INDEX "address_type_slug" ON "address_type" ("slug");`

To remove the constraint, the migrator suggests the following line of code:

`ALTER TABLE "address_type" DROP CONSTRAINT "address_type_slug";`

However, this throws an exception stating there is no such constraint. After a bit of puzzeling, I stumbled upon the following: http://stackoverflow.com/questions/12922500/trouble-dropping-unique-constraint 

Converting the above alter statement to:

`DROP INDEX "address_type_slug";`

Solves the issues I had. But since there are no github issues (nor failing tests?) for Propel 2 on this topic, I wonder if it is a local problem or a postgresql-platform-wide.

**Comment by marcj** [comment]
Thats interesting. Maybe we have accidently no integration test for dropping indices for Postgresql. Which version of PostgreSQL did you use?
