### ISSUE TITLE
The Propel generates only one object when Postgres schema is used

### ISSUE THREAD

**Issue by MiroslavMerinsky** [propelorm/Propel2#1179]
Hi,

I use some tables with the same name, but different schema, for instance public and history, but the generated object is overwritten by the last definition. The Propel can not recognize different schemas and generate objects by tables.

```xml
<database name="..." defaultIdMethod="native" schema="public">
    <table name="challenge">
        <column name="id" type="integer" required="true" primaryKey="true" autoIncrement="true"/>
        ...
    </table>
    <table name="challenge" schema="history">
        <column name="id" type="integer" required="true"/>
        ...
    </table>
</database>
```

Thank you for feedback.

Best Regards,

Miroslav

**Comment by marcj** [comment]
Thats indented. You should specify a own phpName on each table. `<table name="challenge" phpName="ChallengeHistory" schema="history">`
