### ISSUE TITLE
PDO driver specific options are ignored

### ISSUE THREAD

**Issue by mathieuimbert** [propelorm/Propel2#1185]
I was trying to make Propel work with PDO::MYSQL_ATTR_SSL_KEY specific option, since I'm working on a project that requires a SSL key to connect to the database.  I checked the ATTR_PERSISTENT option, since it's the only one that seems to be supported. But options seem to be com

The class PdoConnection allows to pass an array of options:

```
public function __construct($dsn, $user = null, $password = null, array $options = null)
{
    parent::__construct($dsn, $user, $password, $options);
```

But during the connection process in GeneratorConfig, $options is omitted:

```
$con = ConnectionFactory::create(['dsn' => $dsn, 'user' => $username, 'password' => $password], AdapterFactory::create($buildConnection['adapter']));
```

Maybe I missed something, but when I tested I am certain that $options was always empty.

**Comment by marcj** [comment]
Have you tried using the latest master version? we recently pulled in some code that should cover your MYSQL_ATTR_SSL_KEY option. https://github.com/propelorm/Propel2/pull/1176

**Comment by mathieuimbert** [comment]
@marcj Thanks for your answer. You are right, I checked the master build, and the MYSQL_ATTR_SSL_KEY is there, but I see 2 issues:

First the $options are not passed to PDO's constructor. From PdoConnection.php:

    public function __construct($dsn, $user = null, $password = null, array $options = null)
    {
        var_dump($options);
        parent::__construct($dsn, $user, $password, $options);

=> `array(0) {}`

This can be fixed by modifying the GeneratorConfig class:

    // Set user + password to null if they are empty strings or missing
    $username = isset($buildConnection['user']) && $buildConnection['user'] ? $buildConnection['user'] : null;
    $password = isset($buildConnection['password']) && $buildConnection['password'] ? $buildConnection['password'] : null;
    $options = isset($buildConnection['options']) && is_array($buildConnection['options']) ? $buildConnection['options'] : null;

    $con = ConnectionFactory::create(['dsn' => $dsn, 'user' => $username, 'password' => $password, 'options' => $options], AdapterFactory::create($buildConnection['adapter']));

Then there is the second issue, it that the option name is a string (MYSQL_ATTR_SSL_KEY), but PDO constructor is expecting an integer value (\PDO::MYSQL_ATTR_SSL_KEY). I was able to convert the options:

    public function __construct($dsn, $user = null, $password = null, array $options = null)
    {
        $pdoOptions = [];
        if (is_array($options)) {
            foreach ($options as $key => $option) {
                $pdoOptions[constant('self::' . $key)] = $option;
            }
        }
    
        parent::__construct($dsn, $user, $password, $pdoOptions);

I created a pull request: https://github.com/propelorm/Propel2/pull/1190

**Comment by dereuromark** [comment]
PR has been merged
