### ISSUE TITLE
Express one-to-one relationship

### ISSUE THREAD

**Issue by gossi** [propelorm/Propel2#1187]
With `<foreign-key>` almost all keys relate to a one-to-many relationship, with a special case where it is treated as a [one-to-one relationship](http://propelorm.org/documentation/04-relationships.html#one-to-one-relationships). This isn't true for each case and basically it is impossible to detect what the author wanted. I was wondering if there could be some more markup on the `<foreign-key>` element to express this relationship as a `one-to-one` instead of the default `one-to-many`. Something like:

```xml
<foreign-key oneToOne="true">
```

This would help creating methods in singular instead of the plural forms. Also I do use the propel model API to generate actions, serializer, domain objects, etc. Yet I do have an accompanying file with additional metadata that says which foreign-key is a one-to-one relationship, actually. I think this belongs to propel itself.

**Comment by marcj** [comment]
A outgoing relation is treated as one-to-one when its local column is a primary key. This is what a one-to-one is in RDBMS. http://propelorm.org/documentation/04-relationships.html#one-to-one-relationships
I don't see that it's necessary to have a even more verbose way to define a one-to-one relation.

**Comment by gossi** [comment]
If you have three tables: A, B, C, D and table A is referencing B and C, D is referencing A. The references of A to B and C are one-to-one while A to D is one-to-many (or many-to-many), yet you give A it's own primary key for ease of usage, then you want to have a more verbose way to define a one-to-one relation.

**Comment by marcj** [comment]
>  then you want to have a more verbose way to define a one-to-one relation.

I don't see why I would want to have that more verbose way.

**Comment by gossi** [comment]
To have methods that are more appropriate according to the domain model instead of to the technical one.

**Comment by marcj** [comment]
You are free to add your custom model logic, to create relation methods that are more appropriate to your model relation set-up.

**Comment by oojacoboo** [comment]
Inheritance, what a mess...
