### ISSUE TITLE
Cannot insert a value for auto-increment primary key 

### ISSUE THREAD

**Issue by BondITSolutions** [propelorm/Propel2#1195]
I'm getting the error `Cannot insert a value for auto-increment primary key (...)` when I'm trying to write a row to a MySQL database table with the primary key field pre-defined. I've always been under the impression MySQL allows this by default. Contrary to MSSQL which requires to set `IDENTITY_INSERT` to `ON` first. 

Is this a 'bug' in Propel, or have I gone full retard with my limited MySQL knowledge?

**Comment by Recon** [comment]
> Calling the setter on an autoincremented PK will throw an exception as soon as you try to save the object. You can allow PK inserts on such columns by setting the allowPkInsert attribute to true in the \<table\> tag of the XML schema. 

Reference: http://propelorm.org/documentation/reference/active-record.html

**Comment by BondITSolutions** [comment]
Ah, didn't know that, thanks!
