### ISSUE TITLE
Custom ORDER BY clause with ModelCriteria

### ISSUE THREAD

**Issue by ktounet** [propelorm/Propel2#1210]
I would use ```NULLS LAST``` [option](https://www.postgresql.org/docs/current/static/queries-order.html) in the ```ORDER BY``` clause. However, no function of the class ModelCriteria allows this.

Is there a solution without rewriting the query into native SQL language ?

Thanks.

**Comment by marcj** [comment]
Not built-in, but you can write your own in your Query class, that modifies `$this->orderByColumns`

**Comment by ktounet** [comment]
Obviously... thanks, it's perfect !
