### ISSUE TITLE
propel build turns null into 'null'

### ISSUE THREAD

**Issue by gossi** [propelorm/Propel2#1226]
I modified my generated model. Basically, overriding a parent method, here is the signature:

```php
public function getChildren(Criteria $criteria = null, ConnectionInterface $con = null)
```

well.. after running `propel build` again, propel turns the above code into this one:

```php
public function getChildren(Criteria $criteria = 'null', ConnectionInterface $con = 'null')
```

So, I need to search & replace every `'null'` into `null` after running propel build.

**Comment by marcj** [comment]
Propel doesn't change (in terms of loading and then modify) php code. Base classes are generated completely (overwritten), child classes aren't touched when already exist. So, I don't see here a issue. Feel free to describe in a way we can understand the actual issue.
