### ISSUE TITLE
Symfony2 has removed Propel bridge from Symfony Core.

### ISSUE THREAD

**Issue by ben-giles** [propelorm/Propel2#1227]
Symfony2 has removed Propel bridge from Symfony Core. So your install instructions no longer work.

"require": {
    "propel/propel": "2.0.*@dev",
    "propel/propel-bundle": "~2.0@dev"
}

You must add:
"symfony/propel1-bridge": "master-dev"
as well.

https://github.com/symfony/symfony/commit/3f4b87d8c0103297fe6528845cdee0946de860ae

**Comment by marcj** [comment]
Its Propel1 bridge. What has v2 to do with it?

**Comment by ben-giles** [comment]
The version number doesn't matter. 
I was just saying that Symfony no longer installs propel1-bridge by default. So if you follow the directions to install PropelBundle as they are written it will fail because the propel1-bridge classes are not there.

**Comment by marcj** [comment]
I guess it matters as Propel v2 doesnt need propel1-bridge.

**Comment by ben-giles** [comment]
Composer is showing propel/propel1 as required for 
propel-bundle ~2.0@dev.

 So it install propel1 as well.

```
./composer.phar show propel/propel-bundle ~2.0@dev
name     : propel/propel-bundle
descrip. : Integration of Propel in Symfony2
keywords : orm, persistence, propel
versions : * 2.0.0-alpha4
type     : symfony-bundle
license  : MIT License (MIT) (OSI approved) https://spdx.org/licenses/MIT.html#licenseText
source   : [git] https://github.com/propelorm/PropelBundle.git d54ee14d2a8cb636f413661930247834df61386b
dist     : [zip] https://api.github.com/repos/propelorm/PropelBundle/zipball/d54ee14d2a8cb636f413661930247834df61386b d54ee14d2a8cb636f413661930247834df61386b
names    : propel/propel-bundle

autoload
psr-0
Propel\PropelBundle => .

requires
propel/propel1 ~1.6
symfony/symfony ~2.4

requires (dev)
fzaninotto/faker dev-master
sensio/framework-extra-bundle ~3.0

```

**Comment by marcj** [comment]
This was a bug in 2.0.0-alpha4, which is fixed since months in master.
