### ISSUE TITLE
Specify schema on reverse engineering

### ISSUE THREAD

**Issue by gioid** [propelorm/Propel2#1232]
I'm trying to use Propel on a Postgres installation, but I have a problem with the reverse engineering mechanism.
I have a database with a "public" schema containing a table named _user_. If I try to reverse the database into the _schema.xml_, no reference to the "public" schema can be found on the XML:

``` xml
<database name="test" defaultIdMethod="native" defaultPhpNamingMethod="underscore">
```

So, when I generate the classes and I try to list the _user_ table, there is no reference to the schema itself.
However, if I add the attribute **schema** to the XML definition like this:

``` xml
<database name="test" defaultIdMethod="native" defaultPhpNamingMethod="underscore" schema="public">
```

all the generated classes include the "public" schema on the queries.

I see that on Propel1 there was a configuration property called "propel.database.schema", but I can't figure out how to get a similar behaviour on Propel2, to let the reverse engineering works better.

**Comment by marcj** [comment]
What is your actual question? I don't see any issue with using the value of `schema` in the actual queries.
