### ISSUE TITLE
Migrations with onDelete Restrict

### ISSUE THREAD

**Issue by jmourgues** [propelorm/Propel2#1238]
In the schema, if I have a foreign key defined with 
`onDelete="RESTRICT"`

Each time a diff command is called, a migration class is generated to update the FK, even if the current onDelete value is already RESTRICT.

To fix this, I omit the onDelete tag, as Restrict is the default, but I would think that it should be possible to specify a RESTRICT value in the schema.

with propel 2.0.0-dev mysql  5.5.49

**Comment by dereuromark** [comment]
Is someone able to make a PR here with suggested changes?

**Comment by djairhogeuens** [comment]
@dereuromark I'm almost finished with a PR for a fix. It's a little bit more complex than it seems as the default behavior is not the same for every DBMS. As this case is about MySQL, shall I fix it for that one just for now? The way that I fixed it allows to easily set the default values for the other DBMSes as well if this would be needed. Or do you have any idea what the default values are for the different supported DBMSes?
