### ISSUE TITLE
[NOT AN ISSUE] Just a thank you for your hard work!

### ISSUE THREAD

**Issue by MikeeI** [propelorm/Propel2#1252]
Discovered Propel after a long search for a DB "supercharger".

You increased my productivity 10 times. Thank you so much.

I think propel is underhyped and underappreciated. 

Greetings

PS: Sorry for the SPAM

**Comment by gboddin** [comment]
Oh well, I'll take the opportunity to drop a big thanks as well :)

**Comment by dhm80** [comment]
Stop spamming! Just kidding ;)

I love Propel as well, BUT how will it go on?
- Propel1 is not maintained since 2 years
- Propel2 ist still alpha?
- How far is data-mapper and unit of work (see #795)?

Cheers!

**Comment by gboddin** [comment]
I'm using the 2.0-dev for quite some times and the community is reactive on any bugs popping there.

If you're not afraid about getting your hands dirty, you use testing, lock the used version (composer.lock) on your projects and can afford a fast release cycle, there's nothing preventing you to use it.

**Comment by kapowkimc** [comment]
I just want to echo the OP. 

I used propel for almost a decade for all PHP projects and have no plans to change that. Thank you.

**Comment by marcj** [comment]
Thanks and thanks to all contributor as well :) @cristianoc72 works currently hard on the new `data-mapper` architecture which will make things even more awesome. 🎉

**Comment by nibsirahsieu** [comment]
@marcj, is there any tutorials regarding data-mapper architecture? I want to try it for my pet project

**Comment by dereuromark** [comment]
Propel2 is on the way to become stable
All help is greatly appreciated!
