### ISSUE TITLE
Updating the ID of entity fails for (at least) compund PKs

### ISSUE THREAD

**Issue by MrShoenel** [propelorm/Propel2#1254]
Hey,
I noticed that I cannot update entities for which I changed the PK, if the PK consists of two columns. This probably applies to other cases with single- or multi (more than 2) -valued PK-fields as well.

Scenario:
- Entity-class with PK (id_1, id_2), lets say the IDs were 1 and 2
- Update id_1 to 3 and call save()
- Results in update-query where the new value (3) is used as update-criteria
- Does not work as there is no entitiy with ID (3, 2) yet

Example query-generated by Propel:
`UPDATE my_relation SET id_1=:p1 WHERE my_relation.id_1=:p2 AND my_relation.id_2=:p3`
with `p1 = 3, p2 = 3 and p3 = 2` but it should have been `p1 = 3, p2 = 1 and p3 = 2` (set id_1 to 3 where id_1 = 1 and id_2 = 2).

_edit:_ It seems to fail to update entities in general if the primary key is updated.

**Comment by marcj** [comment]
Changing PKs has currently serious limitations. We're solving this issue with the new data-mapper architecture in the `data-mapper` branch.

**Comment by MrShoenel** [comment]
That sounds exciting, thanks for the update :)
