### ISSUE TITLE
PHPDoc wrong for auto-usage of LIKE when '*' or '%' found

### ISSUE THREAD

**Issue by dhm80** [propelorm/Propel2#1256]
Hi there!

After my application stopped returning the desired results I found your change:
https://github.com/propelorm/Propel2/commit/5d5825b61d2432dbb03467d08db71fb116bd8c63

I can understand the "risk" and why you removed it, but you should also update the generated PHPDoc block, see:
https://github.com/propelorm/Propel2/blob/83906eef02260f1f41e5b4f4d83779dada01b0f4/src/Propel/Generator/Builder/Om/QueryBuilder.php#L975-L988

It's quite confusing if the docs say the exact opposite of what is really happening ;)

Cheers, Ansas

**Comment by marcj** [comment]
Thanks, would you like to send us a pull-request?
