### ISSUE TITLE
Need tests for Microsoft SQL

### ISSUE THREAD

**Issue by mhaisley** [propelorm/Propel2#1266]
Need tests for Microsoft SQL.

**Comment by marcj** [comment]
Feel free to submit a PR

**Comment by mhaisley** [comment]
@marcj Do any of the CI platforms offer SQL Server support?  I believe that Travis & CircleCI do not support SQL Server at all, if so is the project open to adding a third CI platform?

**Comment by marcj** [comment]
I don't know any that is free. We're open to integrate a third CI of course.
