### ISSUE TITLE
Propel reverse  function redeclaration

### ISSUE THREAD

**Issue by mitchez20** [propelorm/Propel2#1269]
Propel reverse engineering uses the same function to access an attribute and a collection of related objects if the column name end with 's'.

Example: Mysql Table 'Gene' with attribute 'homologs'

Model Gene Class contains:

 public function getHomologs()
 public function getHomologs(Criteria $criteria = null, ConnectionInterface $con = null)

Causes Function Redeclaration error.

Solution:
Always add an 's' to retrieve collections (compare Java Hibernate Mapping Wizard)
 public function getHomologss(Criteria $criteria = null, ConnectionInterface $con = null)

Best regards,
Mile

**Comment by marcj** [comment]
Why don't you adjust the generated schema.xml, so it actually works the way you want it?
