### ISSUE TITLE
MSSQL - Uncaught 'PDOException' - "Incorrect syntax near keyword"

### ISSUE THREAD

**Issue by MDT-FGI** [propelorm/Propel2#1272]
Hello,

I got a table named "User" and this is a reserved keyword in MSSQL. When using the SQL Management Studio, you have to put those tables (or even better: all tables) in brackets "[User]" to keep the right syntax.
Propel seems to miss this:
> Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[42000]: [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]Incorrect syntax near the keyword 'User'.' in H:\xampp\htdocs\vendor\propel\propel\src\Propel\Runtime\Adapter\Pdo\PdoStatement.php:57 Stack trace: #0 H:\xampp\htdocs\vendor\propel\propel\src\Propel\Runtime\Adapter\Pdo\PdoStatement.php(57): PDOStatement->execute(NULL) #1 H:\xampp\htdocs\vendor\propel\propel\src\Propel\Runtime\Connection\StatementWrapper.php(194): Propel\Runtime\Adapter\Pdo\PdoStatement->execute(NULL) #2 H:\xampp\htdocs\vendor\propel\propel\src\Propel\Runtime\ActiveQuery\Criteria.php(2644): Propel\Runtime\Connection\StatementWrapper->execute() #3 H:\xampp\htdocs\vendor\propel\propel\src\Propel\Runtime\ActiveQuery\ModelCriteria.php(1988): Propel\Runtime\ActiveQuery\Criteria->doSelect(Object(Propel\Runtime\Connection\ConnectionWrapper)) #4 H:\xampp\htdocs\vendor\propel\propel\src\Propel\Runtime\ActiveQuery\ModelCriteria.php(1024): Propel\Runtime\ActiveQuery\ModelCriteria->doSelec in H:\xampp\htdocs\vendor\propel\propel\src\Propel\Runtime\ActiveQuery\Criteria.php on line 2650

**Comment by marcj** [comment]
Activate identifierQuoting.
