### ISSUE TITLE
Handling of fields in models/collections?

### ISSUE THREAD

**Issue by derpoho** [propelorm/Propel2#1273]
Hey Guys,

this is some kind of BestPractices Question.
i am currently building an App with Propel for the first time, it looks VERY promising. But there are some question that i can't answer on my own.

- How do rename Model Fields to be output in an API. Let`s say, i want to hide some fields from the output. Is there any way this can be done without reassigning every key of the model?
- The same for model collections?

Am i missing something or do i have to go the good old way of remapping every key in every model of an collection?

Thanks for the help!

Greets Marcus

**Comment by marcj** [comment]
It's actually more a general data mapper question than an ORM question as ORMs are not responsible to map your models to api result structures. You have several possibilities:

* Use `select()` at your *Query object so you get directly an array with your requested columns
```php
$array = BlaQuery::create()
   ->select(['Id', 'Name'])
   ->find()
   ->getArrayCopy();
```
* Classic mapping
```php
$array = array_map(function(Item $item){ 
    return [
        'id' => $item->getId(),
        'name' => $item->getName()
    ];
}, $query->find()->getArrayCopy());
```
* Use a helper method to extract fields, `$array = Helper::toArrayLimitedByFields($items, ['Id', 'Name']);`

For performance reasons I'd go the first way, but it really depends.

Propel does not provide any method to get an array from a limited column dataset from an object directly (except that Query way).
