### ISSUE TITLE
PDO::ATTR_PERSISTENT not recognized by config attributes

### ISSUE THREAD

**Issue by sleenen** [propelorm/Propel2#1278]
When adding 

'attributes' => [
    PDO::ATTR_PERSISTENT => true,
],

to connection settings, I get the following error:

[Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]
  Unrecognized option "12" under "propel.database.connections.default.attributes"

The PropelConfiguration class only has ATTR_EMULATE_PREPARES has a valid child. 

Why are lots of the other PDO attributes not added? Is there a reason for this?

The options part does have a 'ATTR_PERSISTENT', but what does that actually do? Does that apply the PDO::ATTR_PERSISTENT => true ?

**Comment by sleenen** [comment]
#1213 , hadn't seen that one, my bad.

**Comment by marcj** [comment]
Fixed via #1279.
