### ISSUE TITLE
propel init fails - no user and password

### ISSUE THREAD

**Issue by xorock** [propelorm/Propel2#1283]
I have just created a new mysql project.
My composer.json is simple:

``` json
"minimum-stability": "dev",
    "require": {
        "propel/propel": "^2.0@alpha"
    }
```

And now ./vendor/bin/propel init fails when selecting `Do you have an existing database you want to use with propel? [no]: : yes`

```
[Propel\Runtime\Connection\Exception\ConnectionException]  
  Unable to open connection                                  

  [Propel\Runtime\Adapter\Exception\AdapterException]  
  Unable to open PDO connection                        

  [PDOException]                                                                     
  SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)  
```

No user and password are set.

I can login directly without any problem

```
mysql -u root -p
select version();
+----------------+
| version()      |
+----------------+
| 5.5.33-MariaDB |
+----------------+
1 row in set (0.00 sec)
```

**Comment by marcj** [comment]
Why didn't you set a user at least?

**Comment by xorock** [comment]
I'm setting everything but in final step it's missing. That is why I have reported issue.

**Comment by dereuromark** [comment]
I will close this old ticket. If someone wants to make a PR or reissue, feel free to do so.
