### ISSUE TITLE
plural of "ox" words

### ISSUE THREAD

**Issue by kriks57** [propelorm/Propel2#1284]
Hi,

with StandardEnglishPluralizer, when a column name is box, it's plural form is generated as boxen, which is wrong.
In the StandardEnglishPluralizer class "ox" is in $plural and $irregular, but the latter is applied first.

maybe should there be a ^ in $pattern or $searchPattern ?

**Comment by dereuromark** [comment]
Is someone able to make a PR here with suggested changes?

**Comment by dereuromark** [comment]
https://github.com/propelorm/Propel2/pull/1772
