### ISSUE TITLE
Is this promising project dead?

### ISSUE THREAD

**Issue by derpoho** [propelorm/Propel2#1285]
Just looked at the commit graphs, it looks like nobody is taking care lately. I love to work with Propel, but there are for sure some points that could be extended.

Just wanted to know, if it's going to be continued, to make the right decisions for my next projects?

Greets Guys!

**Comment by marcj** [comment]
[No it's not dead](https://github.com/propelorm/Propel2/commits/master).

**Comment by derpoho** [comment]
I have seen the commits @marcj, and for starters, i am not angry asking or anything else. I am just interested, i have Propel in Use for some SideProjects for now, and i am quite happy with it, but i want to push it into real production code, so i just wanted to kindly ask for information!

F.e:
- is the 2.0 sometimes released out of alpha?
- what are updated plans for the datamapper branch?
- and so on... ;)

So many question, i guess it might be good for Propel if some news came to light, or am i missing something?
