### ISSUE TITLE
MSSQL - Diff generates wrong syntax on ALTER TABLE

### ISSUE THREAD

**Issue by MDT-FGI** [propelorm/Propel2#1294]
When you change a type in your schema.xml and the column has to be modified, propel generates wrong syntax on the update statements. This happens on any table/column if you change their type afterwards.

Generated statement:
> ALTER TABLE [Note] MODIFY
> (
>     [created_at] DATETIME2 NULL,
>     [updated_at] DATETIME2 NULL
> );

Exception of the executed statement:
> [Propel\Runtime\Exception\RuntimeException]
> Failed to execute SQL "ALTER TABLE [Note] MODIFY
> (
>     [created_at] DATETIME2 NULL,
>     [updated_at] DATETIME2 NULL
> )". Aborting migration.
> [PDOException]
> SQLSTATE[42000]: [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]Incorrect syntax near 'MODIFY'.

Correct Syntax would look like this:
> ALTER TABLE [Note] ALTER COLUMN
>     [created_at] DATETIME2 NULL;
> ALTER TABLE [Note] ALTER COLUMN    
>     [updated_at] DATETIME2 NULL;

You can not modify multiple columns at once with MSSQL.

**Comment by MDT-FGI** [comment]
Same problem happends with "ALTER TABLE x ADD column_a;"
There is some brackets "( ... )" not being expected by MSSQL

**Comment by dereuromark** [comment]
Closing in favor of the other ticket with more details.
Also, PR seems open and just needs to get finished and merged.
