### ISSUE TITLE
Clarity on direction of library required

### ISSUE THREAD

**Issue by mc0** [propelorm/Propel2#1297]
The current direction of the library is really unknown to me and I assume others right now. Obviously development is happening but there are mixed messages about the future. This is important because picking a library for a project is a commitment.

Will Propel2 be an active record pattern or a data mapper pattern? Development is happening in both `master` and in `data-mapper`. If that new branch really is the "future," why not make it Propel3?

Some concerns that are visible "externally":
- There hasn't been a blog post on the Propel2 site since 2015.
- The master branch is having fixes trickle in.
- No real path forward for external contributors (because of all of the above).
- Alpha6 came out without any posts.
- Only 6 pull requests closed in the past month+.
- Activity is down on the project (fear of using an alpha?).
- The wiki is outdated and the pull request for data-mapper is closed because development resumed in the `data-mapper` branch.

Maybe some of the above should be their own issue but I'd appreciate at least being able to have a discussion be in the open.

**Comment by marcj** [comment]
As I've seen only one question in your issue:

> Will Propel2 be an active record pattern or a data mapper pattern? Development is happening in both master and in data-mapper. If that new branch really is the "future," why not make it Propel3?

Propel2 will be a data-mapper and optional active-record through traits.

Please read https://github.com/propelorm/Propel2/pull/795. Very detailed explained, why there will be no unmaintained Propel2, just to move data-mapper to Propel3.

Writing a data-mapper from scratch that needs to cover all Propel features takes a very long time, especially when only two people work on it.

Please add questions, so I can answer them.

**Comment by mc0** [comment]
> There hasn't been a blog post on the Propel2 site since 2015.

Why hasn't there been a post in a year if development is active? It doesn't necessarily need to be elaborate.

> The master branch is having fixes trickle in.

Why isn't data-mapper merged in if it's closer to what Propel2's API is going to look like?

> No real path forward for external contributors (because of all of the above).

How can someone contribute to help get the project further along to a stable version?

> Alpha6 came out without any posts.

Is alpha6 master or data-mapper?

If master: Why release a new alpha if it's API will just be unmaintained?

> Only 6 pull requests closed in the past month+.

There are pulls requests from months ago - why are these sitting around stagnant?

> The wiki is outdated and the pull request for data-mapper is closed because development resumed in the data-mapper branch.

Why not update the wiki since this is where the contribute section points people for clarity?

Also: Is the data-mapped branch just in need of passing tests or is work being done on the core still?

**Comment by marcj** [comment]
> Why hasn't there been a post in a year if development is active? It doesn't necessarily need to be elaborate.

Because there are no big news yet and nobody felt the need to creat a post.

> Why isn't data-mapper merged in if it's closer to what Propel2's API is going to look like?

Because its tests aren't green and it would break many applications out there.

> How can someone contribute to help get the project further along to a stable version?

Help fixing tests in data-mapper branch.

> Is alpha6 master or data-mapper?

alpha6 is a version of master. data-mapper is just a feature branch that is being developed.

> If master: Why release a new alpha if it's API will just be unmaintained?

API is very close, so there's no need to freeze current master. Many people are using master in their apps and want to see bug fixes. When data-mapper feature is merged we will get another alpha with breaking changes.

> There are pulls requests from months ago - why are these sitting around stagnant?

Because nobody had the time to review, or the reporter didn't fix tests, or there're open questions, or someone forget it. Could be many reasons.

>Why not update the wiki since this is where the contribute section points people for clarity?

Pull-Requests for data-mapper is not closed, so everybody is free to send pull-request against that branch.

> Also: Is the data-mapped branch just in need of passing tests or is work being done on the core still?

Both. Tests has priority, but we will move a lot of repository stuff to entitymap because of separation of responsibility etc.
