### ISSUE TITLE
Multiple Stages of the Database. Local/Staging/Production. Whats the best way with Propel?

### ISSUE THREAD

**Issue by derpoho** [propelorm/Propel2#1298]
Hey, trying to get my head around how to handle multiple Database Stages the best way with propel, without changing the config or having to set environment variables. Secondary might be an option, but is there a better way? Also thinking about the migrations etc, can they be made to multiple Stages too?

Thanks for the help.

**Comment by marcj** [comment]
I'd go with environment variables, or Symfony configuration system (if you use the PropelBundle), or [propel.ext.dist](http://propelorm.org/documentation/10-configuration.html#naming-conventions).

You can even use propel.php format and do whatever you want. e.g. Using YamlDumper and load other yml files based on your application configuration. I'm not sure what type of configuration architecture you're using, but in general when you have staging and production server, you have usually a deploy script which creates either config files (like propel.php) or sets environment variables. What else would you like?

**Comment by derpoho** [comment]
Ok, i didn't mention my real problem. To use either environment variables or different propel configs for the stages totally makes sense for sure.
But what about migrations? When i run migrations when i am in dev stage, how can i run the same migrations on to production or staging? Is this possible?
I know this is more a general question and not totally responsibility of propel. But it would be nice if this is achievable somehow.

I basically mean a migration store for each stage.

**Comment by marcj** [comment]
If you need to update your production database, you execute the `propel:migration:up` command on the production server (not from your localhost). Same with staging.

**Comment by derpoho** [comment]
ok, i need to get my head around your first suggestion. not totally clear right now. Anyway, will find out ;)

Thanks for the help @marcj and keep up the good job.
