### ISSUE TITLE
HashCode and Virtual Column

### ISSUE THREAD

**Issue by jeremydenoun** [propelorm/Propel2#1299]
Hi EveryBody,

I work on specific request and I need your help for understand and find a fix for a specific case.

I use a many-to-many relation table (with crossRef) between two table and I made a request like :

`TableAQuery::create()->useManyToManyTableQuery()->leftJoinCrossTableB()->endUse()->withColumn(CrossTableB.Name, TableBName)->find();`

If I debug SQL query I have a perfect query with correct result and my custom column "TableBName" become a virtual column and fill in target object, this work perfectly if I have an unique entry in ManyToManyTable to TableA but if I have multiple reference to the same object in Table A, I retrieve correctly some times the same object but the virtual column (TableBName) is fill with the same value and not with SQL Query result.

I trace code and I find a "deduplication/optimisation" with the following algorithm :
1) the result come from SGDB and is forward to ObjectFormatter
2) the format method append to ObjectCollection a computed (getAllObjectsFromRow) object
3) the offsetSet ([] operator) apply an algorithm for determine a hash code with

```
if ($validPk) {
            return crc32(json_encode($this->getPrimaryKey(), JSON_UNESCAPED_UNICODE));
} elseif ($validPrimaryKeyFKs) {
            return crc32(json_encode($primaryKeyFKs, JSON_UNESCAPED_UNICODE));
}
return spl_object_hash($this);
```
and dedup based on this hash...

**Problem :**
The object can be the same (primary key) but virtual column value can differ (group by, many to many)

I try to use some others strategy (use relation on demand directly on result object without join), this work but this isn't performant. Actually my only solution is to use createSelectSql made PDO binding and fetch raw content for hydrate target Object (bad solution)

Do you have another solution ?

What do you think consider use spl_object_hash in getHashCode if current value has virtual column set ? else I think the Base Class generator hashCode function should be updated for object that can be targeted by a cross ref

Thanks for your help

**Comment by marcj** [comment]
spl_object_hash doesnt work when you deactivate the instancePooling. Your case is logically not feasible. You can either use

```php
/** @var \Propel\Runtime\DataFetcher\DataFetcherInterface */
$dataFetcher = TableAQuery::create()
    ->useManyToManyTableQuery()
        ->leftJoinCrossTableB()
    ->endUse()
    ->withColumn(CrossTableB.Name, TableBName)
    ->doFind();

foreach ($dataFetcher as $row) {
}
```

Or you use the ManyToMany Table as entry point:

```php
$manyToMany = ManyToManyTableQuery::create()
    ->withJoinCrossTableA()
    ->withJoinCrossTableB()
    ->withColumn('CrossTableB.Name', 'TableBName')
    ->find();
foreach ($manyToMany as $item) {
    var_dump($item->getVirtualColumn('TableBName');
}
```

**Comment by jeremydenoun** [comment]
for be more clear I have concrete case :
```xml
    <table name="contacts" phpName="Contact">
        <column name="id" type="integer" required="true" primaryKey="true" autoIncrement="true"/>
        <column name="name" type="LONGVARCHAR"/>
    </table>
    <table name="customers" phpName="Customer">
        <column name="id" type="integer" required="true" primaryKey="true" autoIncrement="true"/>
        <column name="name" type="LONGVARCHAR"/>
    </table>

    <table name="customer_contact" isCrossRef="true">
        <column name="customer_id" type="integer" primaryKey="true"/>
        <column name="contact_id" type="integer" primaryKey="true"/>
        <foreign-key foreignTable="customers" onUpdate="cascade" onDelete="cascade" skipSql="true"
                     phpName="CrossCustomers">
            <reference local="customer_id" foreign="id"/>
        </foreign-key>
        <foreign-key foreignTable="contacts" onUpdate="cascade" onDelete="cascade" skipSql="true"
                     phpName="CrossContacts">
            <reference local="contact_id" foreign="id"/>
        </foreign-key>
    </table>
```

 in customer_contact
---


- customer_id : 1
- contact_id: 1

**

- customer_id : 2
- contact_id: 1

Contact table
---

- Contact id 1 / Name => Contact1
- Contact id 2 / Name => Contact2

Customer table
---

- Customer id 1 / Name => Customer1
- Customer id 2 / Name => Customer2

If I try
```php
        $list = ContactQuery::create()
            ->useCustomerContactQuery()
                ->leftJoinCrossCustomers()
            ->endUse()->withColumn('CrossCustomers.Name','customerName')
            ->filterById(1)
            ->find()->toArray();
```

return 
```
    [0] => Array
        (
            [Id] => 1
            [Name] => Contact1
            [customerName] => Customer2
        )

    [1] => Array
        (
            [Id] => 1
            [Name] => Contact1
            [customerName] => Customer2
        )
```

and should be
```
    [0] => Array
        (
            [Id] => 1
            [Name] => Contact1
            [customerName] => Customer1
        )

    [1] => Array
        (
            [Id] => 1
            [Name] => Contact1
            [customerName] => Customer2
        )
```

Your options based on ManyToManyTableQuery works because the hashCode in this case use spl_object_hash 
```php
        if ($this->aCrossCustomers && $hash = spl_object_hash($this->aCrossCustomers)) {
            $primaryKeyFKs[] = $hash;
        } else {
            $validPrimaryKeyFKs = false;
        }

        //relation customer_contact_fk_7afb5a to table contacts
        if ($this->aCrossContacts && $hash = spl_object_hash($this->aCrossContacts)) {
            $primaryKeyFKs[] = $hash;
        } else {
            $validPrimaryKeyFKs = false;
        }
```
but in this case I have only Contacts with a relation, my target was to build a request for fetch all contacts and associated customer if a relation exists (exactly the result from SQL query built from first request)

but with a right join I can find a workaround for answer to my need with your tips (and be performant...)

but I think results objects should always look like to SQL result, this can imply non intuitive issue

Thanks @marcj

**Comment by marcj** [comment]
As said:

```php
        $list = ContactQuery::create()
            ->useCustomerContactQuery()
                ->leftJoinCrossCustomers()
            ->endUse()->withColumn('CrossCustomers.Name','customerName')
            ->filterById(1)
            ->find()->toArray();
```

is logically not possible because it would create several Contact objects with the same primary key, which would break a lot of things. Either use CustomerContactQuery as entry point or query the results directly in the query above like I showed.

**Comment by jeremydenoun** [comment]
Ok the set Formatter with a simpleArrayFormatter is a good solution thanks for it
