### ISSUE TITLE
Generated function has misleading documentation

### ISSUE THREAD

**Issue by bkjohnson** [propelorm/Propel2#1308]
Imagine a scenario where I have a `Cat` table with a `lives` column to count how many lives a particular cat has left.  Here is the generated documentation for the function I need to use:

### Documentation
```
    /**
     * Filter the query on the lives column
     *
     * Example usage:
     * <code>
     * $query->filterByLives(1234); // WHERE lives = 1234
     * $query->filterByLives(array(12, 34)); // WHERE lives IN (12, 34)
     * $query->filterByLives(array('min' => 12)); // WHERE lives > 12
     * </code>
     ...
```

So if I want to get all cats that have more than 5 lives, the documentation would suggest that I do this:

### My code
```
$cats = CatQuery::create()
                 ->filterByLives(array('min' => 5))
                 ->find();
```

However, the generated function is using `Criteria::GREATER_EQUAL` rather than `Criteria::GREATER`, which means that my code is off by 1

Either the documentaion should be updated [here](https://github.com/propelorm/Propel2/blob/97dcdae4aff3ae6ae5f5bcf356a72babaa9f293d/src/Propel/Generator/Behavior/Delegate/templates/queryMethodsTemplate.php#L8) to use `>=` rather than `>` or the code itself should change, I'm not sure which is the preferred way.

**Comment by dereuromark** [comment]
PR merged
