### ISSUE TITLE
Auto-generating isCrossRef

### ISSUE THREAD

**Issue by flapy2b** [propelorm/Propel2#1312]
Hi,
I generated a schema.xml file from my mysql database with the `propel reverse `command.
The schema is well-formed but for the many-to-many relations, I had to put manually the attribute isCrossref=true. 
Can this attribute be added automatically ?

**Comment by marcj** [comment]
I'm afraid there's no solid way to determine which is a many-to-many relation. Sometimes it's only two one-to-many relations to the same pivot table.

**Comment by flapy2b** [comment]
The main case for a many to many relation is the link table has two primary key (the two foreign keys). 
A pivot table has just one primary key and two (or more) foreign keys.
I wish we could find an alogrithm  that can work for a maximum of cases.

**Comment by marcj** [comment]
The reverse functionality is actually only a little helper so you don't have to write a complete schema if you already have a database. It's not meant to be used regularly. So if you find a solution, feel free to send a Pull Request, but I'd not want it as an official feature or bug report.
