### ISSUE TITLE
PHP Warning in Profiler

### ISSUE THREAD

**Issue by williamlang** [propelorm/Propel2#1316]
Haven't been able to reliably reproduce. I think it's the execution time of the query, and so very time dependent.

    PHP Warning:  number_format() expects parameter 2 to be integer, float given in /vendor/propel/propel/src/Propel/Runtime/Util/Profiler.php on line 309

**Comment by Musiksammler** [comment]
+1

I came across the same error.

**Comment by ChristiaanBilthof** [comment]
+1 .. highly annoying :) any chance we can get this fixed?

**Comment by marcj** [comment]
@ChristiaanBilthof, sure you can send a pull-request http://propelorm.org/contribute.html

**Comment by dereuromark** [comment]
PR open.
