### ISSUE TITLE
Add parent::__construct to addConstructorOpen when BaseClass is defined

### ISSUE THREAD

**Issue by chriz0101** [propelorm/Propel2#1317]
When i have a BaseClass in my <table> node in schema.xml the $outputDir/Base/$name.php has the right extends Expression. 

```
/**
 * Initializes internal state of $pathToModel object.
 */
 public function __construct()
 {
 }
```

But why not then there is no parent::__construct() after? Would be nice if the BaseClass is valid and added to the class defination. 

```
/**
 * Initializes internal state of $pathToModel object.
 */
 public function __construct()
 {
   parent::__construct();
 }
```

**Comment by dereuromark** [comment]
Is someone able to make a PR here with suggested changes?
