### ISSUE TITLE
Mysql: if table name is mysql key word...

### ISSUE THREAD

**Issue by jmjoy** [propelorm/Propel2#1320]
I have a table name `group`,
```php
$group = new Group();
$group->setName('???');
$group->save();
```
then it will execute this sql:
```sql
INSERT INTO group (id, name) VALUES (NULL, '???');
```
But the word `group` is mysql key word, it will fail becase of syntax error, so, can it be solved by surround `group` with `` ?

**Comment by marcj** [comment]
[identifierQuoting](http://propelorm.org/documentation/reference/schema.html#table-attributes)
