### ISSUE TITLE
missing foreignSchema in schema.xml

### ISSUE THREAD

**Issue by domcar** [propelorm/Propel2#1323]
I'm trying to import an existing pgsql database in my project but it gets a problem when running the sql:build, the error is `Table "schema.yyy" contains a foreign key to nonexistent table "schema.zzz"`. This means that foreign-table `zzz` is looked up into the same schema and this is wrong.

I would expect that propel were going to look into the other schemas, but this is not happening.

I looked at the generated schema.xml and the problem is that at the <foreign-key does not have a reference to the other schema: ´<foreign-key foreignTable="zzz" name="example">`  it works when I add foreignSchema="other_schema", in this case the foreign key will be looked into other_schema.zzz

Since the DB is very big, this cannot be done manually. Can you please have a look at this issue?

**Comment by marcj** [comment]
Propel doesn't inspect the whole database and find the `foreignTable`automatically in another schema. What if you have that same table name in different schemas? It's too ambiguous. Also this would need to happen during the build, introducing database calls with it, which is not how the build works. So you only solution is to define for each `foreignKey` the `foreignSchema` attribute.

**Comment by domcar** [comment]
When using reverse on a huge DB is not possible to set manually the `foreignSchem` and I also don't agree with you that the name would be ambiguos: if two tables have the same name but in different schemas there is no ambiguity. Have a look here: https://github.com/propelorm/Propel2/pull/1326

**Comment by marcj** [comment]
I agree, it not ambiguous in the database's world, but in Propel's. Propel simply can't know which table you mean in the `foreignKey`. Also the reverse feature is not meant to be used repeatedly, especially not if you have a big database. Sorry, but I don't see a way to make this use case solid workable, this would actually be way out of scope of an ORM.

**Comment by domcar** [comment]
In this case I would like to see somewhere in the documentation that the reverse feature is not adapt for big databases (what is big, btw?).
But I repeat, with the MR I linked before, it works.
