### ISSUE TITLE
Regression in Builder Breaks Generated Entities 

### ISSUE THREAD

**Issue by ThomasKuehnel** [propelorm/Propel2#1324]
The alpha 6 release introduced a regression in the generation of entity files. It's very likely due to this change: https://github.com/propelorm/Propel2/pull/1090

We recently updated Propel to version alpha 6 at Spryker an are seeing issues with platforms supporting native id-method auto-increment (e.g. MySql). 

It seems that the changes applied to `DefaultPlatform::getIdentifierPhp()` (https://github.com/propelorm/Propel2/blob/2.0.0-alpha6/src/Propel/Generator/Platform/DefaultPlatform.php#L1347) are not in sync with how this method gets called in `ObjectBuilder::addDoInsertBodyRaw()` (https://github.com/propelorm/Propel2/blob/2.0.0-alpha6/src/Propel/Generator/Builder/Om/ObjectBuilder.php#L5887). 

The results in the generated entity files look something like this:
```$pk = $con'foo-pk-seq'->lastInsertId();```
which results in a critical parse error.

Thanks for looking into it.

**Comment by marcj** [comment]
I don't think #1090 is responsible for this. Can you give me your schema.xml that generates that wrong php code?

**Comment by ThomasKuehnel** [comment]
Thanks for the quick response. It's not only one schema file that causes the issue, it's all of them that define  `id-method-parameter`. Here's an example: https://github.com/spryker/Acl/blob/master/src/Spryker/Zed/Acl/Persistence/Propel/Schema/spy_acl.schema.xml

The issue doesn't occur with Propel 2.0.0 alpha5 though

**Comment by marcj** [comment]
You were right, #1090 was buggy. I fixed it in master.

**Comment by ThomasKuehnel** [comment]
Thanks a lot for taking care of it so quickly. Do you have any ETA on a new release that contains this fix?

**Comment by marcj** [comment]
https://github.com/propelorm/Propel2/releases/tag/2.0.0-alpha7

**Comment by ThomasKuehnel** [comment]
Thanks for the awesome support! It is highly appreciated 👍
