### ISSUE TITLE
Using sqlType won't generate correct migration file by PgsqlPlatform

### ISSUE THREAD

**Issue by oliwier-spryker** [propelorm/Propel2#1336]
Hi,

Using `<column sqlType="...">` won't generate correct migration file. 

For example, consider this simple schema:

```xml
<table name="foo">
    <column name="email" required="true" type="VARCHAR" size="255" />
</table>
```

After installing it, the expected column is created.

Now adding `sqlType` attribute to `email` column, won't generate correct migration file.

```xml
<table name="foo">
    <column name="email" required="true" type="VARCHAR" size="255" sqlType="citext" />
</table>
```

Current Result:

```php
return array (
  'test' => '',
);
```

Expected Result:
```php
return array (
  'test' => '
BEGIN;

ALTER TABLE "foo"

  ALTER COLUMN "email" TYPE citext USING NULL;

COMMIT;
',
);
```

I was able to trace the code which is responsible for generating the diff, and it's in [PgsqlPlatform class on line 525](https://github.com/propelorm/Propel2/blob/master/src/Propel/Generator/Platform/PgsqlPlatform.php#L525).

Adding `sqlType` to the list of conditions, and running diff command again generates expected results.

```php
if (isset($changedProperties['size']) || isset($changedProperties['type']) || isset($changedProperties['sqlType']) || isset($changedProperties['scale'])) {
```

**Comment by dereuromark** [comment]
I agree, it would be great if propel internally would recognize that change  in schema, and create the diff accordingly. :+1:

**Comment by marcj** [comment]
Can you create a pull request for that change?

**Comment by dereuromark** [comment]
PR is now open.
