### ISSUE TITLE
Duplicated filter function name when using array type

### ISSUE THREAD

**Issue by TBoonX** [propelorm/Propel2#1346]
_I am using "propel/propel": "~2.0@dev" in composer._

In my schema.xml I have the following lines:
```
<table name="class_p2o5" schema="agronomic" idMethod="native" phpName="ClassP2o5">
   <column name="soil_class" phpName="SoilClassP2o5" type="ARRAY"/>
...
```
The table has no foreign key stuff and the phpName is distinct.

I created the model files and started using them. When I load everything I get the error:
`Cannot redeclare Base\\ClassP2o5Query::filterByHumus_P2o5()`
In the Base/ClassP2o5Query.php file the function is there two times:
`public function filterByHumus_P2o5($humus_P2o5 = null, $comparison = null)`
The description and the code differ - e.g. the first parameter:
```
array $humus_P2o5 The values to use as filter
mixed $humus_P2o5 The value to use as filter
```

**Do I have to add something to the schema.xml file or is this a bug?**

**Comment by marcj** [comment]
I guess this has something todo with the pluralizer

**Comment by TBoonX** [comment]
Nice guess! If I force plural ("es" at the end of name and phpName) then there is no collution. Please add such information to the docs - like on http://propelorm.org/documentation/cookbook/working-with-advanced-column-types.html#array-columns
