### ISSUE TITLE
Validator 3.2.2

### ISSUE THREAD

**Issue by angelk** [propelorm/Propel2#1347]
Discussion: https://github.com/propelorm/Propel2/commit/b7c8ac9052c972838ae74d6ad0f6fa9ea5f2a100

Fix that we are waiting: https://github.com/symfony/symfony/pull/21592
This must be fixed before I (or someone else) continue to investigate the problem with validator v3.2.2.

I'm creating this issue because the problem is bigger than I tough and to keep every one updated with the investigation :)

Explanation of the problem:

Constraint result with 3.2.1
```
array(2) {
  [0] =>
  class Symfony\Component\Validator\Constraints\Regex#91 (6) {
    public $message =>
    string(25) "Please enter a valid ISBN"
    public $pattern =>
    string(9) "/[^\d-]+/"
    public $htmlPattern =>
    NULL
    public $match =>
    bool(false)
    public $payload =>
    NULL
    public $groups =>
    array(3) {
      [0] =>
      string(7) "Default"
      [1] =>
      string(19) "ValidateTriggerBook"
      [2] =>
      string(22) "ValidateTriggerFiction"
    }
  }
  [1] =>
  class Symfony\Component\Validator\Constraints\Regex#93 (6) {
    public $message =>
    string(25) "Please enter a valid ISBN"
    public $pattern =>
    string(9) "/[^\d-]+/"
    public $htmlPattern =>
    NULL
    public $match =>
    bool(false)
    public $payload =>
    NULL
    public $groups =>
    array(2) {
      [0] =>
      string(7) "Default"
      [1] =>
      string(22) "ValidateTriggerFiction"
    }
  }
}
```

Constraints with 3.2.2
```
array(1) {
  [0] =>
  class Symfony\Component\Validator\Constraints\Regex#78 (6) {
    public $message =>
    string(25) "Please enter a valid ISBN"
    public $pattern =>
    string(9) "/[^\d-]+/"
    public $htmlPattern =>
    NULL
    public $match =>
    bool(false)
    public $payload =>
    NULL
    public $groups =>
    array(2) {
      [0] =>
      string(7) "Default"
      [1] =>
      string(22) "ValidateTriggerFiction"
    }
  }
}
```

# fix
> Potential idea. I will re-investigate after changes in symfony!
I think we should iterate over the [$fictionConstraints](https://github.com/propelorm/Propel2/blob/master/tests/Propel/Tests/Generator/Behavior/Validate/I18nConcreteInheritanceHandleValidateBehaviorTest.php#L87) and expect the following groups `ValidateTriggerFiction, ValidateTriggerBook, ValidateTriggerFiction`.

**Comment by marcj** [comment]
I have honestly way too less experiences in Validation component that I would very appreciate as many opinions as we could get @propelorm/propel

**Comment by angelk** [comment]
Just fired PR: https://github.com/propelorm/Propel2/pull/1350

I don't think that we should care about Validator internals. Api works - we are happy.
