### ISSUE TITLE
Fake database adapter or fake query execution

### ISSUE THREAD

**Issue by blumfontein** [propelorm/Propel2#1362]
Is there any way to configure Propel not to execute queries on a real database? This is helpfull in testing. Consider, we have a query:

```php
BookQuery::create()->filterByGenre('thriller')->orderByTitle()->find();
```

I do not want to test this query against database, because this is an obvious query. But I want to test that those methods "filterByGenre" and "orderByTitle" actually exist (i.e. if I've changed a schema and deleted or renamed columns), and this expression does not throw undefined method exception. So I need some option to tell Propel to skip the database query in "find()" method.

I know I can just catch PDOException, but I wonder if there is a built-in possibility to fake queries.

**Comment by marcj** [comment]
Well, as you said "I want to test that those methods "filterByGenre" and "orderByTitle" actually exist", why don't you just do that? :)

```php
$this->assertTrue(method_exists(BookQuery::class, 'filterByGenre'))
```
