### ISSUE TITLE
setFormatter on populateRelation

### ISSUE THREAD

**Issue by joshualawson** [propelorm/Propel2#1367]
When trying to use setFormatter on populateRelation as below I get the following error:
`NOTICE: PHP message: PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Propel\Runtime\Collection\Collection::setFormatter() must be an instance of Propel\Runtime\Formatter\AbstractFormatter`

```
return UserQuery::create()
            ->paginate(1,10)
            ->populateRelation('Address')
            ->setFormatter('Propel\Runtime\Formatter\ArrayFormatter')->toJson();
```

but when I use it without populateRelation it works fine

I can't seem to find any documentation on using populateRelation and setFormatter, I even tried moving the setFormatter into a different location, (e.g. as the 2nd call in the chain etc)

**Comment by marcj** [comment]
I think populateRelation returns no longer a query object, so you need to call setFormmater on the query object (thus move it one line above)

**Comment by joshualawson** [comment]
@marcj yeah I tried that also... still the same issue

**Comment by marcj** [comment]
You should really take a look into the documentation. Even in the generated code itself, you see which objects all those methods return. It's not always the same.

```php
return UserQuery::create()
            ->setFormatter('Propel\Runtime\Formatter\ArrayFormatter')
            ->paginate(1,10)
            ->populateRelation('Address')->toJson();
```

**Comment by joshualawson** [comment]
As i mentioned above, I tried that and go the following error:

Call to undefined method: populateRelation
