### ISSUE TITLE
New Feature Request: Support for Selecting Random Rows

### ISSUE THREAD

**Issue by nikeshhajari** [propelorm/Propel2#137]
Hi,

I don't know how feasible this request would be, but it would be nice to have support for selecting a random row for from a table.

Maybe something like:

$query = ColorTableQuery::create()
->random();

Thanks,
Nikesh Hajari

**Comment by michaelrimbach** [comment]
+1

**Comment by dereuromark** [comment]
We will have to open a new discussion here for 2022+
