### ISSUE TITLE
MSSQL `applyLimit` Regex patch breaking virtual columns

### ISSUE THREAD

**Issue by McManning** [propelorm/Propel2#1381]
I seemed to have been a bit gung-ho about resolving #1376 

While it did fix the case of the regex not parsing out the appropriate WHERE clause, it introduces a bug for virtual columns that are based on select statements. 

E.g. the following use case generates a malformed SQL statement (Same base sample from #1376):
```php
$projects = ProjectQuery::create()
    ->withColumn('(SELECT Email FROM User WHERE ID = Project.OwnerID)', 'Email')
    ->offset(10)
    ->limit(10)
    ->find();
```

In this case, the `FROM` in the virtual column is the split point in `MssqlAdapter::applyLimit`. 

If you want me to do a PR to reverse PR #1375 in the meantime while I iron out these new issues, I can do that. 

Thanks,
Chase

**Comment by McManning** [comment]
Update on this; I have a potential patch ready to go. I'm adding a handful of regression tests, just to give myself (and probably others) peace of mind on this one. 

I'm seeing that there isn't a `MssqlAdapterTest` class present - would it be fine if I added one alongside the other Pdo adapter tests? It seems like you guys aren't doing active MSSQL testing in your CI environment, but the tests I want to write wouldn't need an active connection anyway. They'd be very similar to `OracleAdapterTest`.

**Comment by marcj** [comment]
Yeah sure, go for it. :)

**Comment by dereuromark** [comment]
PR seems merged.
