### ISSUE TITLE
vendor/bin/propel command tries to include files from wrong directory

### ISSUE THREAD

**Issue by paperscissors** [propelorm/Propel2#1385]
Hello! Tried to run `vendor/bin/propel` from the command line and it told me it couldn't find the propel library. On further investigation the sh script:

`require(__DIR__ . '/propel.php');` is trying to include propel from /vendor/bin/, when the files actually exist in `vendor/propel/propel/bin`. 

I'm able to run the command via `vendor/propel/propel/bin/propel` no problem, just took a second to realize the sh script was pointing to the wrong place!

Thanks!

**Comment by angelk** [comment]
the `/bin/propel` is symlink
```
potaka@debian /var/www/tekstove-api (master) $ ls -la vendor/bin/
total 8
....
lrwxrwxrwx  1 potaka potaka   27 Feb 11 20:00 propel -> ../propel/propel/bin/propel
```

Then __DIR__ is resolved to ./vendor/propel/propel/bin and it should work (works for me).

What OS are you running ? What is your composer version ?

**Comment by paperscissors** [comment]
That makes sense.

Here is the behavior I'm seeing:

```[user web]$ vendor/bin/propel
-bash: vendor/bin/propel: No such file or directory
[user web]$ vendor/bin/propel
PHP Warning:  require(/var/www/web/vendor/bin/propel.php): failed to open stream: No such file or directory in /var/www/web/vendor/bin/propel on line 4

Warning: require(/var/www/web/vendor/bin/propel.php): failed to open stream: No such file or directory in /var/www/web/vendor/bin/propel on line 4
PHP Fatal error:  require(): Failed opening required '/var/www/web/vendor/bin/propel.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/web/vendor/bin/propel on line 4

Fatal error: require(): Failed opening required '/var/www/web/vendor/bin/propel.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/web/vendor/bin/propel on line 4
```

Running CentOS 6.7, Composer 1.2.4.

This is a vagrant box running rsync for file syncing. I'm thinking after composer installed propel it interpreted the symlink as a file and saved over the symlink with the real deal. This looks like the case:

```
[user web]$ ls -la vendor/bin
total 32
...
-rwxrwxr-x  1 vagrant apache   60 Jun  2 21:31 propel
```
So that solves that mystery. A pain but at least this is here for posterity. Thanks for the quick reply!
