### ISSUE TITLE
propel doesn't retrieve tildes, etc

### ISSUE THREAD

**Issue by Brugui7** [propelorm/Propel2#1390]
I use a third-party service that provides me a list of articles and inserts them directly into the database (not via propel).

I want to obtain these products via propel, but if just one of them has a non-utf8 character (ñ, á) the php script just returns a 200 OK status but 0 data.

Is there any fix for this? I tried adding something like this to my propel.php
`'settings' => [
                        'charset' => 'utf8',
                        'queries' => [
                            "SET NAMES utf8_general_ci COLLATE utf8_general_ci",
                            " COLLATION_CONNECTION = utf8_general_ci",
                            " COLLATION_DATABASE = utf8_general_ci",
                            " COLLATION_SERVER = utf8_general_ci"
                        ]
                    ]`
 and re-generated the classes 

(Sorry if my english is bad)

**Comment by Brugui7** [comment]
Just realized that the problem is in the toJSON method, because if I do a echo directly from the find() method, it works

**Comment by marcj** [comment]
Well, ñ, á is valid utf8. You should probably set up full UTF-8 correctly. http://propelorm.org/documentation/02-buildtime.html#setup-utf-8
