### ISSUE TITLE
PropelDateTime::createHighPrecision fails when 0 ms from the last second

### ISSUE THREAD

**Issue by jimd20i** [propelorm/Propel2#1391]
```
[28-Jun-2017 14:20:24 UTC] Slim Application Error:
Type: Error
Message: Call to a member function setTimeZone() on boolean
File: .../vendor/propel/propel/src/Propel/Runtime/Util/PropelDateTime.php
Line: 73
Trace: #0 ...: Propel\Runtime\Util\PropelDateTime::createHighPrecision()
```

Irrelevant paths and filenames stripped above. This problem comes up infrequently, but is a crash when it does happen.

The context is:

```
        $dateTime = \DateTime::createFromFormat('U.u', $time ?: self::getMicrotime());

        $dateTime->setTimeZone(new \DateTimeZone(date_default_timezone_get()));
```

getMicrotime() does:

```
        $mtime = microtime(true);

        return str_replace(',', '.', $mtime);
```

...and that's the problem. When PHP stringifies a floating point number which happens to have no fractional component, it returns an integer, which doesn't have a decimal point (.) and so doesn't match the pattern 'U.u'. `\DateTime::createFromFormat()` itself takes a string so would have the same problem if called directly.

The fix should really go in `getMicrotime()` because it's returning the wrong thing here. I'd recommend completely ignoring locale-affected floating-point conversions by doing something like:

```
        return sprintf("%d.%03d", $mtime, $mtime * 1000 % 1000);
```

...however you may prefer to just ensure that you do have the expected string format like:

```
        return str_replace(',', '.', sprintf("%.3f", $mtime));
```

A quick PHP snippet if you want to see the behaviours involved:

```
print_r([
	\DateTime::createFromFormat('U.u', str_replace(',', '.', 1498660661.000)),
	\DateTime::createFromFormat('U.u', 1498660661.000),
	\DateTime::createFromFormat('U.u', sprintf("%.3f", 1498660661.000)),
	\DateTime::createFromFormat('U.u', str_replace(',', '.', 1498660661.001))
]);
```

**Comment by gharlan** [comment]
-> https://github.com/propelorm/Propel2/commit/efafd0960ada68914b2a03f97151da98226c0f75

**Comment by jimd20i** [comment]
Nice, you've got some fast fingers there :)

**Comment by jimd20i** [comment]
Change looks good, closing.
