### ISSUE TITLE
getRelatedTable() on ColumnMap instance throws exception

### ISSUE THREAD

**Issue by Ooypunk** [propelorm/Propel2#1393]
So I have this instance of Propel\Runtime\Map\ColumnMap, and it has a foreign key (isForeignKey() returns true). But, when calling getRelatedTable() on it, instead of receiving a TableMap from it, I get an exception:
"Call to a member function getTable() on null".

Closer inspection tells me getTable() is being called on "$this->table->getDatabaseMap()" (ColumnMap line 444), which returns null. So my guess is that the question should be: why is getDatabaseMap() returning null?

Still quite new to Propel, so I hope I gave enough information; if not, please tell me so.

**Comment by marcj** [comment]
The actual question is: Why do you fiddle around with ColumnMap directly? You shouldn't instantiate it on your own. Can you please post your use case, full stacktrace etc? Maybe using sandbox.propelorm.org.

**Comment by Ooypunk** [comment]
I don't instantiate it on my own, it is what is returned by TableMap::getColumn(), as shown in this sandbox: http://sandbox.propelorm.org/171a236

The goal of all this is to get the metadata of columns from the model, as this already contains most of this data. Seeing this, it would not be sensible to define this metadata in another place again (keeping it DRY, and all that).

**Comment by marcj** [comment]
```php
$map = $user::TABLE_MAP;
$table_map = new $map();
```

You shouldn't do that. Do instead `$map::getTableMap()` and you're golden.

Also, if you need references like in your fiddle, you need to make the table known to the runtime. You do that by letting the autoloader load  the TableMap. You can do that by calling `OtherTable2TableMap::buildTableMap();` or simple loading `OtherTable2` in your code like `class_exists(OtherTable2::class)`. You need to do this because we do not load all available tables per default into the memory that were existent during build-time (to save memory&cpu).

See my fiddle http://sandbox.propelorm.org/8ffafe5.

**Comment by Ooypunk** [comment]
Golden, not yet. Your fiddle works (thanks for that!), but now I have a new question: you write in your fiddle
```
Map\OrganisationTableMap::buildTableMap()
```
but how do I get the "Organisation"-part? In my fiddle I wrote "$user = new User()", but that was for explaining my question; in my use case I don't know the name of the model beforehand, as an instance of the model is inserted into my class. That's why I am doing "$map::getTableMap()" instead of "User::getTableMap()".

**Comment by marcj** [comment]
If you don't know your own models, you need to read your model definitions using the .xml files.
In Propel2 there's no such thing as index of all available models, so your only bet is the origin - the xml files.

**Comment by Ooypunk** [comment]
That's a pity. In that case I wonder if it would not be faster to get all metadata from the XML in the first place, in which case I have two more questions:
- does Propel have classes for that, that I can use/reuse?
- if I added attributes to the XML that Propel didn't know, would Propel ignore them?

**Comment by marcj** [comment]
Yes and Yes. However, I'd use simplexml for performance reasons and cache that stuff.

**Comment by Ooypunk** [comment]
OK, then. :D 
Thanks a lot! You've been a great help.
