### ISSUE TITLE
Migration remove mysql column comments

### ISSUE THREAD

**Issue by michaelfoley1** [propelorm/Propel2#1403]
I have taken an existing mysql schema and started managing migrations through propel.

Unfortunately every time I generate a migration diff it attempts to delete the existing comments I have on any table columns.

**Comment by marcj** [comment]
Because you don't have them in your xml file.

**Comment by michaelfoley1** [comment]
You're correct, that would cause what i described.

I'm trying to describe a slightly different issue which is actually the opposite.

My xml file has comments annotated in it.
My running database has comments in it.

Despite this, every diff I create includes an alter table statement essentially to add the comment attribute.
.

I believe the cause is because MysqlSchemaParser.php doesn't extact comments from the live database before performing a diff against the schema generated by the XML

**Comment by AviBueno** [comment]
@michaelfoley1, your PR seems to be a good step in the right direction.
Can you please explain why you decided to close it?

**Comment by michaelfoley1** [comment]
It was abandoned for personal, not technical reasons.
