### ISSUE TITLE
Numeric column prefix causes invalid php symbol

### ISSUE THREAD

**Issue by michaelfoley1** [propelorm/Propel2#1404]
Using a schema with columns that are prefixed generates invalid php models.

Quoting http://php.net/manual/en/language.variables.basics.php:

> A valid variable name starts with a letter or underscore, followed by any number of letters, numbers, or underscores. As a regular expression, it would be expressed thus: '[a-zA-Z_\x7f-\xff][a-zA-Z0-9_\x7f-\xff]*'

The following code is an example of a schema which generates a protected member called `1_test` 

```xml
<database name="default" defaultIdMethod="native" defaultPhpNamingMethod="underscore">
  <table name="foo">
    <column name="bar" type="INTEGER"/>
    <column name="1_test" type="INTEGER"/>
  </table>
</database>
```
```php
<?php

use \DateTime;
...
use Propel\Runtime\Util\PropelDateTime;

/**
 * Base class that represents a row from the 'foo' table.
 * @package    propel.generator..Base
 */
abstract class Foo implements ActiveRecordInterface
{
...
...
    /**
     * The value for the bar field.
     *
     * @var        int
     */
    protected $bar;
    
    /**
     * The value for the 1_test field.
     *
     * @var        int
     */
    protected $1_test;
...
...
}
```

**Comment by michaelfoley1** [comment]
whoops. Didn't mean to close this.

I'm seeking opinions of whether to support reserved keywords as column names (IMHO: yes) and utf8 column names (IMHO: no).

Please weigh in.

**Comment by marcj** [comment]
Well, we should restrict the regex check, so `1_test` won't be possible anymore. All other deeper changes should be addressed against Propel3.

**Comment by michaelfoley1** [comment]
I agree.

I'm going to document here that i've hit the same snag with other schema attributes values colliding against variables in auto-generated base classes.

eg:
```Schema
  <table name="Foo" >
    <column name="deleted" phpName="Deleted" />
  </table>
```

```
abstract class Foo implements ActiveRecordInterface
{
...
    /**
     * attribute to determine if this object has previously been saved.
     * @var boolean
     */
    protected $new = true;

    /**
     * attribute to determine whether this object has been deleted.
     * @var boolean
     */
    protected $deleted = false;
...
    /**
     * The value for the deleted field.
     *
     * Note: this column has a database default value of: 0
     * @var        int
     */
    protected $deleted;
...
}

```
PHP Fatal error:  Cannot redeclare Foo::$deleted in src/schema/Base/Foo.php
```
