### ISSUE TITLE
Some table queries return no records?

### ISSUE THREAD

**Issue by Trellian** [propelorm/Propel2#1412]
Hi, 

I have set up a new project, against a new MySQL DB. in my default schema (iwall), most of my tables have a prefix of 'iw_', eg. 'iw_timezone',  and some have no prefix, eg 'users'.

I have reverse engineered the schema, and I have a working generated model for the schema.

I can apparently only fetch rows from the tables without the table prefix 'iw_'?

Here is my test code:

```
use Propel\Runtime\Propel;
use iwall\iwall\IwTimezoneQuery;

$con = Propel::getWriteConnection('iwall');

$con->useDebug(true);

$sql = "SET GLOBAL init_connect='SET foreign_key_checks = 0';";    // Let Propel handle the RI, since MySQL is broken

$stmt = $con->prepare($sql);
$stmt->execute();  // returns TRUE

```
In MySQL Workbench, I can query table iwall.iw_timezone as follows:

`SELECT * FROM iwall.iw_timezone;`

and the result is:

```
id  name      value
--  ---------  ------
1   GMT+2   2
```

If I try to retrieve it via a direct Propel statement:

```
$stmt = $con->prepare('select * from iwall.iw_timezone;');
$result = $stmt->execute();
$rows = $stmt->fetchAll(); // returns no errors, but $rows = Array[0]

$data = IwTimezoneQuery::create()->setFormatter('Propel\Runtime\Formatter\ArrayFormatter')->find();
$count = $data->count();

```
There is no error reported, but...
$data.data is Array[0]
and $count is 0

I have tried this with several tables, and I can only return rows from tables without the 'Iw' prefix. The generated docs say that a `ChildIwTimezone` object should be returned... what does the 'Child' portion mean????

Please can someone help me understand what is happening here?

In my Composer.json file I have:

```
"require": {
		"php": ">=5.5",
		"propel/propel": "~2.0@dev"

```
and I'm running PHP 5.6.3

Thanks in advance,
Adrian

**Comment by marcj** [comment]
Do they have all a primary key?

**Comment by Trellian** [comment]
Hi Marc, 

Yes, all my tables always have an autoincrement ID field as the primary key... even reporting tables

**Comment by Trellian** [comment]
I left a more detailed description of the problem in the Propel group forum, perhaps it would help to look at it there?

**Comment by Trellian** [comment]
Marc, 

I am deeply sorry for wasting your time, it was my mistake. The particular way I created the records in MySQL Workbench did not autocommit the records as it was supposed to, and I didn't notice.  So Propel was 100% correct, there WERE no records!

My humble apologies, and thanks again for the awesome beast that is  called Propel!

Regards,
Adrian
