### ISSUE TITLE
Invalid hydration when using mergeWith of criteria with "with" models

### ISSUE THREAD

**Issue by prgTW** [propelorm/Propel2#1420]
## Background
- 3 models defined in DB: A, B, C
- A hasOne/hasMany B
- A hasOne/hasMany C

## Scenario
Making a query for A models with B models hydrated and merging criteria for the same base model having "with" models (here: C model)

```php
$aModels = (new AQuery)
    ->leftJoinWith('B');
    ->mergeWith((new AQuery)->leftJoinWith('C'))
    ->find();
```

## Produced SQL:
```sql
SELECT
    a.id, a.a_field, -- A fields
    b.id, b.a_id, b.b_field, -- B fields
    a.id, a.a_field, -- A fields again
    c.id, c.a_id, c.c_field -- C fields
FROM a
    LEFT JOIN b ON (a.id = b.a_id)
    LEFT JOIN c ON (a.id = c.a_id)
```

## Results
- model A hydrated properly
- model B hydrated properly
- model C hydrated improperly

## Reason
`PDODataFetcher::getIndexType` is `TableMap::TYPE_NUM` so object hydration relies on the order of the columns in `SELECT` part.

At the beginning the `offset` of hydration is 0 meaning the A model is hydrated from columns indexed `0` and `1`. Then `offset` is incremented to point to next column for next model hydration.
Then B model is hydrated from `offset=2` to `offset=4` (3 columns).
Then C model is hydrated from `offset=5` to `offset=7`

__Due to fact that A columns are selected twice the C model is hydrated partly from A columns being selected between B model columns and C model columns.__

| SELECT column | mapping   | notes                        |
|:--------------|:----------|:-----------------------------|
| a.id          | A->id     | valid                        |
| a.a_field     | A->aField | valid                        |
| b.id          | B->id     | valid                        |
| b.a_id        | B->aId    | valid                        |
| b.b_field     | B->bField | valid                        |
| a.id          | C->id     | __(inconsistency!)__         |
| a.a_field     | C->aId    | __(inconsistency!)__         |
| c.id          | C->bField | __(inconsistency!)__         |
| c.a_id        |           | *(ignored during hydration)* |

**Comment by dereuromark** [comment]
PR open
