### ISSUE TITLE
upcoming: php 7.2 countable issue

### ISSUE THREAD

**Issue by cbschuld** [propelorm/Propel2#1424]
All:

Looking into php7.2 and seeing some upcoming warning(s) that will need to be addressed due to the countable updates - I'll try to look into creating a PR for it but wanted to get it into the issues bucket:

Warning: count(): Parameter must be an array or an object that implements Countable in src/Propel/Runtime/ActiveQuery/InstancePoolTrait.php on line 33

Thanks!

**Comment by guoshaoxia** [comment]
same problem here, BTW, is Propel2 still maintaining?
