### ISSUE TITLE
Run Propel-commands without shell

### ISSUE THREAD

**Issue by Syndesi** [propelorm/Propel2#1430]
Hi,

is it possible to run commands from propel like `propel sql:insert` without using the shell at all?
The reason is that I've got an webspace with PHP and MySQL but no access to the shell at all (and exec, system etc. are disabled).

Is there a solution?

**Comment by cristianoc72** [comment]
Hi,
imho the best solution is the following:

1) run propel commands locally, to generate the model classes and the sql
file
2) upload your generated model classes via ftp (or ssh)
3) the generated sql file contains sql commands and you can run them
directly on your mysql server, via phpMyAdmin or some client like this. In
phpMyAdmin you should be able to upload a file containing sql commands and
run them, isn't it?
4) Adjust your configuration file according to your remote mysql server
username, password etc.

Regards.

2017-11-18 15:17 GMT+01:00 Syndesi <notifications@github.com>:

**Comment by dhm80** [comment]
Sure you can... that is if you are allowed to run `exec()`.

Just find the full path to the `~vendor/propel/propel/bin/propel.php` and execute the command from your webpage.

But make sure to protect the script from unallowed access ;)

**Comment by Syndesi** [comment]
Hi,

@cristianoc72 your answer seems more or less easy, but I think that it would be complicated to update the local instance, then run the migration-command, check the sql, upload it and run it on the server. But for a one-time-job it would be a fast solution :)

@dhm80 sadly I'm not allowed to run `exec()`, `system()` and similar commands :/

But in the end I found a way to run every command from Propel 2 only with PHP :D 

```php
<?php
// path of current file: /api/lib/propel.php
namespace lib;

use Symfony\Component\Finder\Finder;
use Symfony\Component\Console\Input\ArrayInput;
use Symfony\Component\Console\Output\BufferedOutput;
use Propel\Runtime\Propel;
use Propel\Generator\Application;

class Test {

  public function __construct(){
    // code from vendor/propel/propel/bin/propel.php
    $finder = new Finder();
    $finder->files()->name('*.php')->in(__DIR__.'/../../vendor/propel/propel/src/Propel/Generator/Command')->depth(0); // path adjusted to the location of this file
    $this->app = new Application('Propel', Propel::VERSION);
    $ns = '\\Propel\\Generator\\Command\\';
    foreach ($finder as $file) {
      $r  = new \ReflectionClass($ns.$file->getBasename('.php'));
      if ($r->isSubclassOf('Symfony\\Component\\Console\\Command\\Command') && !$r->isAbstract()) {
        $this->app->add($r->newInstance());
      }
    }
    $this->app->setAutoExit(false);
  }

  public function test(){
    // https://symfony.com/doc/current/console/command_in_controller.html
    $input = new ArrayInput([
      'command'     => 'sql:build',
      '--overwrite' => null
    ]);
    // change the current directory to the project's main folder
    chdir(realpath(__DIR__.'/../../'));
    $output = new BufferedOutput();
    $this->app->run($input, $output);
    return $output->fetch();
  }
}

?>
```
