### ISSUE TITLE
Cannot insert new entities using save

### ISSUE THREAD

**Issue by avindor** [propelorm/Propel2#1440]
Hi,
I'm trying to insert new entity to the database, but I'm receiving an error when trying to insert the entity.

Specifically, after saving the entity, the code generated for the entity calls the static method on the corresponding map of the entity named "addInstanceToPool" with only the object (the key is not being passed) and in the static method named getInstanceKey($object) - the code throws an exception,

**The code count($pk = $value->getPrimaryKey()) throws an exception since getPrimaryKey returns an integer and count throws an exception since it excepts a Countable**

public static function getInstanceKey($value)
    {
        if (!($value instanceof Criteria) && is_object($value)) {
**// this code throws an exception, since getPrimaryKey returns an integer and count throws an exception since it excepts a Countable
            if (count($pk = $value->getPrimaryKey()) > 1 || is_object($value->getPrimaryKey())) {
                $pk = serialize($pk);
            }**

            return (string) $pk;
        } elseif (is_scalar($value)) {
            // assume we've been passed a primary key
            return (string) $value;
        }
    }

The exact exception:

count(): Parameter must be an array or an object that implements Countable

**Comment by marcj** [comment]
Fixed
