### ISSUE TITLE
count() for non array variable

### ISSUE THREAD

**Issue by riso348** [propelorm/Propel2#1443]
Warning: count(): Parameter must be an array or an object that implements Countable in 

\vendor\propel\propel\src\Propel\Runtime\ActiveQuery\ModelCriteria.php on line 402
/vendor/propel/propel/src/Propel/Runtime/ActiveQuery/InstancePoolTrait.php on line 33

Could you please add is_array or validate if count is possible to make? This show warning in php7.2+

**Comment by fbourigault** [comment]
A PR already exists https://github.com/propelorm/Propel2/pull/1437.

**Comment by marcj** [comment]
Fixed

**Comment by riso348** [comment]
Yes fixed for InstancePoolTrait.php but not for ModelCriteria.php
Can you please also fix that?
```
public function select($columnArray)
    {
        if (!count($columnArray) || empty($columnArray)) {
            throw new PropelException('You must ask for at least one column');
        }
````
