### ISSUE TITLE
Different DateTime::format() options used

### ISSUE THREAD

**Issue by stereomon** [propelorm/Propel2#1459]
DateTimes are differently formatted inside Propel. When used Entity::toArray() DateTime fields will be formatted with `format('c')`. With the setter methods the DateTimes are formatted (for comparison) with `format('Y-m-d H:i:s.u')`.

This results in comparison of strings like this:

2018-01-30 14:09:55.000000 (DateTime->format('c'))
2018-01-30 14:09:55.876942 (DateTime->format('Y-m-d H:i:s.u'))

And thus entities are always marked as modified although the entity is not touched.

Simple example:

```
$entity = $query->findOne();
$entity->fromArray($entity->toArray());
```

The entity is now marked as modified which shouldn't be the case here.

**Comment by mruoss** [comment]
This is a problem indeed. Please see my comments on the referenced Spryker ticket. It looks like the function `addToArray()` that generates the `toArray()` function of the Propel models should make use of the `getTemporalFormatter($col)` helper function.

**Comment by dereuromark** [comment]
PR open for this
