### ISSUE TITLE
How to use your lib if anything can change in one moment ?

### ISSUE THREAD

**Issue by zorn-v** [propelorm/Propel2#1460]
I talk about permanent alpha state. Who needs it ? Why I shold use it, instead of Eloquent (I love ActiveState) for example ?
You guys are hurting shit.

**Comment by halfer** [comment]
It's certainly valid to ask why an open source project is not getting the time it needs, but abusive posts are not welcome or justifiable, and accordingly I would endorse this issue being closed and locked.

It _should_ go without saying that F/OSS maintainers are volunteers, and we should appreciate the work they do. If Eloquent works for you, then use that, and mind that you do not abuse the maintainers of that project either.

**Comment by zorn-v** [comment]
> It's certainly valid to ask why an open source project is not getting the time it needs

Nope. There are THOUSANDS open source projects which is not in "alpha" state thru MANY years...

**Comment by marcj** [comment]
Why don't you use then other open-source projects instead of creating a pointless discussion here?

**Comment by zorn-v** [comment]
I'm already do it. But pitifully of yours.
