### ISSUE TITLE
release note issue

### ISSUE THREAD

**Issue by dereuromark** [propelorm/Propel2#1466]
https://github.com/propelorm/Propel2/releases/tag/2.0.0-alpha8 says "PHP 7.1 compatibility", but in fact it should be "PHP 7.2 compatibility"

**Comment by marcj** [comment]
Actually, it's both, I updated to "PHP 7.1+"

**Comment by dereuromark** [comment]
Most people recently have been especially anxious about the PHP7.2 part (as deploy have been impossible on new servers here with the last few master versions up until the very recent fix a few days ago, thus I thought it might be worth explicitly mentioning the support here.

**Comment by marcj** [comment]
Nah, I don't think it's that dramatic.
