### ISSUE TITLE
Custom SQL question

### ISSUE THREAD

**Issue by oscar0812** [propelorm/Propel2#1469]
I have a quick question when it comes to making calculations in custom SQL, I have the following SQL code: 

```php
     public static function orderByProximity($lat, $lon)
     {
        // $lat <= 180 && $lat >=-180, same for $lon
         $sf = M_PI / 180; // scaling factor

         $con = Propel::getWriteConnection(\Map\JobTableMap::DATABASE_NAME);
         // dist = acos[ sin(lat1)*sin(lat2)+cos(lat1)*cos(lat2)*cos(lng1-lng2) ]
         $sql = "SELECT * FROM job
         ORDER BY ACOS(SIN(latitude*$sf)*SIN(:lat*$sf) +
         COS(latitude*$sf)*COS(:lat*$sf)*COS((longitude-:lon)*$sf))";

         $stmt = $con->prepare($sql);
         $stmt->bindParam(':lat', $lat);
         $stmt->bindParam(':lon', $lon);
         $stmt->execute();

         $formatter = new ObjectFormatter();
         $formatter->setClass('\Job'); //full qualified class name
         $jobs = $formatter->format($con->getDataFetcher($stmt));
         return $jobs;
     }
```
This works, but I would like it to be object oriented.

Jobs table has a latitude and longitude column, both are decimals (16, 8). So the question is, how can I convert the previous custom SQL to be more object oriented? For example, I want to have a function in JobQuery like so
```php
public function orderByProximity($lat, $lon){
     // this is one of the many things I've tried, I've also tried adding a custom column
     $sf = M_PI / 180; // scaling factor
     return $this->orderBy(ACOS(SIN('Job.Latitude'*$sf)*SIN($lat*$sf) +
         COS('Job.Latitude'*$sf)*COS($lat*$sf)*COS(('Job.Longitude'-$lon)*$sf));

}
```
I want this in order to accomplish the following:
```php
$jobs = JobQuery::create()->orderByProximity(20, -100)->limit(3)->find();
```

Any clues? Help is appreciated

**Comment by pkschweiger** [comment]
Don't have time actually make this happen for you but can point you in the right direction:

* add a virtual column w/ the custom sql using ```withColumn()```
* order by that virtual column instead

something on the order of:

```php
public function orderByProximity($lat, $lon)
{
    $sf    = M_PI / 180;
    $sfLat = $lat * $sf;
    $alias = $this->getModelAliasOrName();

    $this->withColumn(
        'DbDerivedProximity',
        "ACOS(SIN($alias.Latitude * $sf) * SIN($sfLat) +
              COS($alias.Latitude * $sf) * COS($sfLat) * COS(($alias.Longitude - $lon) * $sf))");

    return $this->orderByDbDerivedProximity();
}
```

Referring to the model w/ its potential alias in custom SQL is good practice to support:

```php
JobQuery::create('j')->orderByProximity(20, -100)->limit(3)->find();
// now  j.(Lat|Long)itude not Job.(Lat|Long)itude
```

More likely an alias you assign as you join (maybe more than once).  Ordering is an unlikely use case for multiple joins, but virtual columns are good for more than ordering, and I digress ...

Note that active records in your result set will have the derived column available via magic getter just as  the active query object now provides a magic ```orderByDbDerivedProximity()```:

```php
$someJob = JobQuery::create()->orderByProximity(20, -100)->findOne();
echo $someJob->getDbDerivedProximity();
```

This matters in a different context. Virtual columns can trip up existing code that pulls a single column.  Unlikely in your use case but I thought it was worth mentioning either way:

```php
// assume the following returns [5, 10, 15]
JobQuery::create()->select('Id')->limit(3)->find()->getArrayCopy();  

// introducing a virtual column forces it into the result set
JobQuery::create()
    ->select('Id')->orderByProximity(20, -100)->limit(3)->find()
    ->getArrayCopy();
// out come nested arrays with the virtual column when only 'Id' column was requested:
[
    ['Id' => 5,  'DbDerivedProximity' => proxOfJob5],
    ['Id' => 10, 'DbDerivedProximity' => proxOfJob10],
    ['Id' => 15, 'DbDerivedProximity' => proxOfJob15],
];

// a way to work around this and get nearly the same result is:
JobQuery::create()->select('Id')->orderByProximity(20, -100)->find()
    ->toKeyValue('Id', 'Id');
// so
[5 => 5, 10 => 10, 15 => 15];
// not
[0 => 5, 1 => 10, 2 => 15];
// but goodnuff oftenuff
```

Digressing again ... see [Adding Columns](http://propelorm.org/documentation/reference/model-criteria.html#adding-columns) in the active query reference ...

Good to see folks trying to embrace propel's paradigm!  Have fun!

**Comment by dereuromark** [comment]
Maybe someone could make a PR for docs improvements if there is anything we can let all others know about this.
Closing for now
