### ISSUE TITLE
ObjectCollection::toArray() will not pass on $includeForeignObjects parameter to objects

### ISSUE THREAD

**Issue by ioannis-papikas** [propelorm/Propel2#1471]
Although each generated object that implements `ActiveRecordInterface` has a parameter `$includeForeignObjects` to include any foreign objects, `ObjectCollection` does not make use of this parameter and passes on always `true`.

The issue is here: `\Propel\Runtime\Collection\ObjectCollection::toArray($keyColumn = null, $usePrefix = false, $keyType = TableMap::TYPE_PHPNAME, $includeLazyLoadColumns = true, $alreadyDumpedObjects = [])`

**Comment by dereuromark** [comment]
PR open
