### ISSUE TITLE
table names not quoted (with identifierQuoting=true in schema)

### ISSUE THREAD

**Issue by rauwebieten** [propelorm/Propel2#1478]
I have a existing SQL-server database, made a xml-schema. 
Because some tables have reserved names, i enabled identifierQuoting and rebuild the models.
Still the table names are not quoted in the executed queries.  (neither are the schemas or columns)

**Comment by rauwebieten** [comment]
Enabling the quoting at runtime on the query works.
`$query->setIdentifierQuoting(true);`

**Comment by dereuromark** [comment]
Is someone able to make a PR here with suggested changes?

**Comment by oojacoboo** [comment]
This isn't currently an issue.  I can confirm that the `identifierQuoting` property set on the `database` node of the xml-schema works properly, at least on the latest commits.  That said, with Postgres, I'm getting back-ticks instead of double quotes.
