### ISSUE TITLE
Multiple Schema SQL Server Reverse Engineer Problem

### ISSUE THREAD

**Issue by donnyfauzan** [propelorm/Propel2#1499]
There is a same bug that exists in Propel 1 when you are trying to reverse engineer MS SQL Server database with multiple schema.

I was using dev-master (currently after 2.0.0-alpha8). Correction is made in the file vendor\propel\propel\src\Propel\Generator\Reverse\ (assumming you’re using composer).

I posted the correction in the following gist, changes commented by me (Abah): 
https://gist.github.com/donnyfauzan/fcdfeccb2374f37857c28d0cb4010b23

**Comment by dereuromark** [comment]
Is this still relevant or can it be closed?

**Comment by zaunaf** [comment]
The bug occured in the  2.0.0-alpha8 release. Reviewing the code today, looks like some refactoring was done. I haven't got time to recheck if the problem still exists, so I think we can close the issue for now. If later on the bug still persists, i will open a new issue.
