### ISSUE TITLE
Propel 2 + Bulk Insert not working

### ISSUE THREAD

**Issue by parthiv2585** [propelorm/Propel2#1501]
Hi All, 
I have try below code for bulk insert. Query executed successfully but data not insert in table

```
$con = Propel::getWriteConnection(PhoneDetailsTableMap::DATABASE_NAME);
// $con = Propel::getConnection();  I have also try this
$sql = "INSERT INTO phone_details (phone_master_id,phone_number,number_use) VALUES ";
for($row =2; $row <= $total_rows; $row++) {
	$sql .= " (1,$phoneNumber,0), ";
}
$stmt = $con->prepare($sql);                 
$stmt->execute();
```

Please help me to fixed this issue ASAP.
Also if you have any example for bulk insert please share URL.
I have more then 45000 row.

Thanks 

Parthvi Shah

**Comment by gillesbourgeat** [comment]
Hello,

you do not have an open transaction ?

http://propelorm.org/Propel/documentation/06-transactions.html

**Comment by mirsch** [comment]
I'm pretty sure your query will not execute successfully because it ends with a comma.
You should also make sure your `$phoneNumber` is properly escaped and maybe read about prepared statements.
