### ISSUE TITLE
Update Symfony 3.4 To Symfony 4.1 + build:model not working

### ISSUE THREAD

**Issue by parthiv2585** [propelorm/Propel2#1503]
Hi All ,
I have upgrade my application in symfony3.4 To symfony 4.1. 
After up gradation below commands are not working.

(1) php bin/console generate:bundle
(2) php bin/console build:model

I have use Propel ORM.

Please help me to fixed this issue.

Thanks 

Parthiv Shah

**Comment by cristianoc72** [comment]
Switch to PropelBundle ~4.0@dev

Il giorno mer 5 dic 2018 alle ore 06:51 Parthiv Shah <
notifications@github.com> ha scritto:
