### ISSUE TITLE
Method equivalent to clearInstancePool no longer available?

### ISSUE THREAD

**Issue by rayrigam** [propelorm/Propel2#1504]
I'm trying to migrate from Propel 1.7 to 2, but don't see an equivalent to the old Peer class method clearInstancePool() that was used to make sure a new query was made to the database when needed.

Is there a new method I can use for that purpose?

Ref: https://stackoverflow.com/questions/11411153/clear-propel-cache-instance-pool

**Comment by cristianoc72** [comment]
Hi, 
`clearInstancePool()` method now is in your TableMap generated classes (e.g. BookTableMap::clearInstancePool() ). It's exactly the same method, moved from old Peer class.

**Comment by cristianoc72** [comment]
Hi, 
`clearInstancePool()` method now is in your TableMap generated classes (e.g. BookTableMap::clearInstancePool() ). It's exactly the same method, moved from old Peer class.
