### ISSUE TITLE
QUERY methods are not delegated

### ISSUE THREAD

**Issue by wurststulle** [propelorm/Propel2#151]
in the delegation behaviour, the QUERY methods are not delegated.

when using

```xml

<table name="account">
  <column name="id" required="true" primaryKey="true" autoIncrement="true" type="INTEGER" />
  <column name="login" type="VARCHAR" required="true" />
  <column name="password" type="VARCHAR" required="true" />
  <behavior name="delegate">
    <parameter name="to" value="profile" />
  </behavior>
</table>
<table name="profile">
  <column name="email" type="VARCHAR" />
  <column name="telephone" type="VARCHAR" />
</table>

```
you can not do a accountQuery::create()->filterByEmail('foo')->find()

(copied from https://github.com/propelorm/Propel/issues/157)

**Comment by SCIF** [comment]
@wurststulle , you can to try patch in #919, it must solve your issue

**Comment by solidevolution** [comment]
Since the merge of this commit: 

https://github.com/SCIF/Propel2/commit/06914b7a4c688d3ce86b27e651e19e8be9b5afbf

we have the following problem with "php propel build"

 [Propel\Runtime\Exception\PropelException]                                                                                          
  Column with name «created_at» (delegated from table «user_payment») already exists in table «user». Probably database design mista  
  ke    

I wondered because in our composer.json we decide to take version "2.0.0-alpha" ...

**Comment by SCIF** [comment]
Field is double defined i.e. for example: created_at defined in parent and delegated table. How Query class can detect which table field you want to filter?

**Comment by solidevolution** [comment]
Yes, that's what we want. A created_at & updated_at timestamp on every join table.

It was possible in past so we designed it like that.

**Comment by marcj** [comment]
maybe we should just skip those columns which are double defined like before @SCIF?

**Comment by SCIF** [comment]
But it's not correct, i think. What way of «overlap» detection do you suppose? What field it must filter if you will use multiple delegations with created_at/updated_at?

```
  <behavior name="delegate">
    <parameter name="to" value="profile, preference" />
  </behavior>
```

It will causes unpredictable behavior or just skip that fields.

**Comment by SCIF** [comment]
@marcj was some faster than me. :) Yeah, we can skip double defined. Really don't know what is better — BC or correct design forcing :)

**Comment by solidevolution** [comment]
I understand your fears @SCIF but then you need another behaviour where it's possible to use default timestampable on multiple 1:1 tables. Let me explain what we do/want:

        <behavior name="delegate">
            <parameter name="to" value="user_payment, user_address, user_text" />
        </behavior>

We want to know, when a user changed/created his user_address data. Before that, the tables data is NULL.

Further, if you see this behavior like "full join data", you should create data for all delegate-tables on parent-creating. A.t.m. it's possible to work with "left join" to reach what we desire.

**Comment by SCIF** [comment]
Seems like it makes sense. @marcj , do you agree that i will skip it?

**Comment by marcj** [comment]
Yeah, to me its totally ok to skip duplicated columns. It's a expected behaviour like in the actual model class, so we should go for it.

**Comment by solidevolution** [comment]
Thx guys for understanding.

We learned from that and fixed version with to 2.0.0-alpha4.

Too bad, I have been following your development happy ;)

**Comment by marcj** [comment]
@solidevolution, it's always a good idea to fix requirements, especially with alpha versions. :p

**Comment by solidevolution** [comment]
I know, thought we already did that but no ;)

**Comment by SCIF** [comment]
@solidevolution , i didn't tested it on real schema, but tests passed. Check it please in my repo — https://github.com/SCIF/Propel2. If everything is ok, i will do PR tomorrow (it's deep night here).

**Comment by marcj** [comment]
Thanks @SCIF for your fast fix! :) @solidevolution please verify his work so we can merge it asap.

**Comment by SCIF** [comment]
@solidevolution , did you check?

**Comment by solidevolution** [comment]
Please give me some days, there's a lot of work a.t.m.

**Comment by SCIF** [comment]
I created schema examples and tested. Fixed my previous commit. Properies skips and tests works ok. Did PR.

**Comment by SCIF** [comment]
@solidevolution , @marcj , any updates guys?

**Comment by marcj** [comment]
@SCIF if he doesn't answer you could just add a test proving your change that double defined columns are handled now correctly and send a pull-request, I'm gonna merge it then :)

**Comment by solidevolution** [comment]
Sorry for that delay. It works now, thx.

**Comment by SCIF** [comment]
@marcj , will you merge it without unit tests? I haven't time to create it in next month (diploma work eats all free time).

**Comment by marcj** [comment]
Yes, I'm going to merge it this evening :smile:
