### ISSUE TITLE
toArray() with converter argument issue

### ISSUE THREAD

**Issue by fd6130** [propelorm/Propel2#1514]
Hello guys, when i convert result using toArray(TableMap::TYPE_FIELDNAME) it will throw an exception:
`Fatal error: Uncaught Propel\Runtime\Exception\BadMethodCallException: Call to undefined method: getfieldName`

I try in php 7 and php 5 still same error.

**Comment by dereuromark** [comment]
Is this still relevant or can it be closed?
It might not have enough info to reproduce here.

**Comment by fd6130** [comment]
> Is this still relevant or can it be closed?
> It might not have enough info to reproduce here.

Hi, i will close this issue for now since i'm now using Symfony + Doctrine.
