### ISSUE TITLE
field name conflict.

### ISSUE THREAD

**Issue by NicoMachado** [propelorm/Propel2#1515]
Hello, I just tried Propel 2.

I spend 3 hours trying to debug sql,  and I can only get this error:
`[2019-05-27 23:01:54] defaultLogger.ERROR: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'desc) VALUES (1, 'Prueba')' at line 1 [] []
`
The problem was the name of the column: in my case "desc", short of description...
I change it to "name" and everything works fine...

Is there any way to wrap the column names ? like sql ? ['desc'] ....

Best regards

**Comment by dhm80** [comment]
You already got the problem: `DESC` is a reserved SQL keyword and cannot by used as column name without quotation. Just use the attribute `identifierQuoting="true"` on table or database level in your schema and you're good.

Example: 
```xml
<table name="my_table" identifierQuoting="true">
  <column name="desc" type="VARCHAR" size="100" />
</table>
```

@see http://propelorm.org/documentation/reference/schema.html#table-element

**Comment by NicoMachado** [comment]
> You already got the problem: `DESC` is a reserved SQL keyword and cannot by used as column name without quotation. Just use the attribute `identifierQuoting="true"` on table or database level in your schema and you're good.
> 
> Example:
> 
> ```
> <table name="my_table" identifierQuoting="true">
>   <column name="desc" type="VARCHAR" size="100" />
> </table>
> ```
> 
> @see http://propelorm.org/documentation/reference/schema.html#table-element

Nice to know that.
I allready change the field name, I'll try it later!

Best Regards
