### ISSUE TITLE
weird insert error/query

### ISSUE THREAD

**Issue by jappyjan** [propelorm/Propel2#1517]
When trying to save a new Entity i get the Error:

`Unable to execute INSERT statement [INSERT INTO invoice (receiver_id, created_at, updated_at, id) VALUES (:p0, :p1, :p2, :p3)]`

When running ->toArray() on my Entity i get the following values for the query placeholders:

reciever_id: 21
created_at: null
updated_at: null,
id: null

when trying to execute this manually using phpmyadmin i get the following error:

`#1364 - Feld 'number' hat keinen Vorgabewert`

the fields created_at and updated_at are auto-generated via the "timestampable" behaviour.
the id field is auto-generated via the "auto_add_pk" behaviour.

why do i receive this error?

its only for 2 entities, all other work fine, even though they use the same behaviours...

**Comment by Olbrych** [comment]
Probably "Invoice" table has field "number" which is "not null" and is missing in the insertion code

**Comment by jappyjan** [comment]
rebuild the models. now it worked...
