### ISSUE TITLE
Did anyone test PHP74 compatibility?

### ISSUE THREAD

**Issue by dereuromark** [propelorm/Propel2#1521]
We have found several issues in our pre-trial of PHP74 in Travis.
Currently, the test matrix here fails and does not yet include this new version.

Maybe we can share and create a required patch here to make it compatible with the new soon to be released PHP minor (dec 2019).

**Comment by dereuromark** [comment]
```
PHP Deprecated:  Array and string offset access syntax with curly braces is deprecated in /vendor/propel/propel/src/Propel/Runtime/ActiveQuery/Criteria.php on line 2411
Deprecated: Array and string offset access syntax with curly braces is deprecated in /vendor/propel/propel/src/Propel/Runtime/ActiveQuery/Criteria.php on line 2411
PHP Deprecated:  Array and string offset access syntax with curly braces is deprecated in /vendor/propel/propel/src/Propel/Runtime/ActiveQuery/Criteria.php on line 2414
Deprecated: Array and string offset access syntax with curly braces is deprecated in /vendor/propel/propel/src/Propel/Runtime/ActiveQuery/Criteria.php on line 2414
```
looks like needs small adjustments.

**Comment by oojacoboo** [comment]
We're forking it and maintaining our own repo at this point.  I don't even know who maintains this repo.  It seems to be abandoned.

**Comment by asgouros** [comment]
Is anyone aware of a working fork compatible to PHP7.4?

**Comment by oojacoboo** [comment]
@asgouros we're maintaining one with Symfony 5.0 components now as well.  I'd encourage others to contribute with pull requests.  We'll be maintaining it for years to come.  It doesn't yet support strictly typed generated models, but that'd be an awesome pull request :)

https://github.com/rentpost/Propel2

**Comment by SourceCode** [comment]
If you are not aware, https://github.com/propelorm/Propel3

**Comment by oojacoboo** [comment]
@SourceCode Oh, I'm aware.  Here is an issue I ticket I raised over a year ago...

https://github.com/propelorm/Propel3/issues/86

We've already started migrating to Doctrine now as well, but we'll need to maintain a fork of Propel for quite some time.

**Comment by dereuromark** [comment]
@oojacoboo @asgouros 
What is your status on this subject at this point?

We at Spryker are still evaluating the options. But now things become critical as 7.4 is now really out there a lot, and we are creating tons of deprecation notices everywhere by now.

**Comment by asgouros-25-8** [comment]
Well, we have taken the "fork" path for now just to provide the minimum PHP 7.4 compatibility changes.

**Comment by asgouros** [comment]
Well, we have taken the "fork" path for now just to provide the minimum PHP 7.4 compatibility changes.

**Comment by SourceCode** [comment]
If its required by your software fork and update then submit a PR that is the best way to ensure the support you require gets included in the project long term.

**Comment by oojacoboo** [comment]
@dereuromark We'll be maintaining a fork for at least a couple years.  It's fully 7.4 compatible and running in prod for us.

I'd certainly welcome collaboration on the fork:  https://github.com/rentpost/Propel2

**Comment by dereuromark** [comment]
There is now traffic again on this main library, it might be worth putting it all there if things can go back to normal maintenance mode. As then everyone would profit from it.
Just a question how many maintainers/developers are interested in long term support and help.

**Comment by dereuromark** [comment]
Given that the PHP74 improvements have landed in master, I will close this.
