### ISSUE TITLE
Propel/Runtime/ActiveQuery/Modal...

### ISSUE THREAD

**Issue by karthibca28** [propelorm/Propel2#1537]
Can you please help to solve this error.!

#0 /var/www/html/My_project/vendor/propel/propel/src/Propel/Runtime/ActiveQuery/ModelCriteria.php(1936): Propel\Runtime\ActiveQuery\Criteria->doSelect(Object(Propel\Runtime\Connection\ConnectionWrapper))
#1 /var/www/html/My_project/vendor/propel/propel/src/Propel/Runtime/ActiveQuery/ModelCriteria.php(1006): Propel\Runtime\ActiveQuery\ModelCriteria->doSelect(Object(Propel\Runtime\Connection\ConnectionWrapper))
#2 /var/www/html/My_project/database/classes/my_site/db/my_site/PvActivation.php(107): Propel\Runtime\ActiveQuery\ModelCriteria->findOne()
#3 /var/www/html/My_project/database/classes/my_site/db/my_site/PvActivation.php(76): my_site\db\my_site\PvActivation->makeNewActId(1)
#4 /var/www/html/My_project/database/classes/my_site/db/my_site/PvUser.php(1626): my_site\db\my_site\PvActivation->activateLogin(1, '')
#5 /var/www/html/My_project/database/classes/my_site/db/my_site/PvUser.php(1610): my_site\db\my_site\PvUser->makeLoginResponse(true, Object(my_site\db\my_site\PvUser))
#6 /var/www/html/My_project/api/player/ProfileController.inc(146): my_site\db\my_site\PvUser->makeLogin('admin', '2345673', 0)
#7 [internal function]: my_site\api\ProfileController->profileLogin()
#8 /var/www/html/My_project/vendor/slim/slim/Slim/Route.php(468): call_user_func_array(Array, Array)
#9 /var/www/html/My_project/vendor/slim/slim/Slim/Slim.php(1343): Slim\Route->dispatch()
#10 /var/www/html/My_project/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call()
#11 /var/www/html/My_project/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()
#12 /var/www/html/My_project/vendor/slim/slim/Slim/Middleware/PrettyExceptions.php(67): Slim\Middleware\MethodOverride->call()
#13 /var/www/html/My_project/vendor/slim/slim/Slim/Slim.php(1288): Slim\Middleware\PrettyExceptions->call()
#14 /var/www/html/My_project/site/slim.php(121): Slim\Slim->run()
#15 {main}

**Comment by dereuromark** [comment]
Also duplication of https://github.com/propelorm/Propel2/issues/1539
