### ISSUE TITLE
Propel ORM Error

### ISSUE THREAD

**Issue by karthibca28** [propelorm/Propel2#1538]
Slim Application Error
The application could not run because of the following error:

Details
Type: Propel\Runtime\Exception\PropelException
Message: Unable to execute INSERT statement [INSERT INTO user_activation (id, uid, act_id, act_uuid, expire_time, act_time, user_agent) VALUES (:p0, :p1, :p2, :p3, :p4, :p5, :p6)]
File: /var/www/html/my_project/database/classes/cvsite/db/cvsite/Base/CvActivation.php
Line: 1125

**Comment by dereuromark** [comment]
Duplication of https://github.com/propelorm/Propel2/issues/1539
