### ISSUE TITLE
Propel runtime doInsert error

### ISSUE THREAD

**Issue by karthibca28** [propelorm/Propel2#1540]
Slim Application Error
The application could not run because of the following error:

Details
Type: Propel\Runtime\Exception\PropelException
Message: Unable to execute INSERT statement [INSERT INTO pv_activation (id, uid, act_id, act_uuid, expire_time, act_time, user_agent) VALUES (:p0, :p1, :p2, :p3, :p4, :p5, :p6)]
File: /var/www/html/My-Project/database/classes/pvsite/db/pvsite/Base/PvActivation.php
Line: 1125

Trace
#0 /var/www/html/My-Project/database/classes/pvsite/db/pvsite/Base/PvActivation.php(998): pvsite\db\pvsite\Base\PvActivation->doInsert(Object(Propel\Runtime\Connection\ConnectionWrapper))
#1 /var/www/html/My-Project/database/classes/pvsite/db/pvsite/Base/PvActivation.php(950): pvsite\db\pvsite\Base\PvActivation->doSave(Object(Propel\Runtime\Connection\ConnectionWrapper))
#2 [internal function]: pvsite\db\pvsite\Base\PvActivation->pvsite\db\pvsite\Base\{closure}()
#3 /var/www/html/My-Project/vendor/propel/propel/src/Propel/Runtime/Connection/TransactionTrait.php(35): call_user_func(Object(Closure))
#4 /var/www/html/My-Project/database/classes/pvsite/db/pvsite/Base/PvActivation.php(963): Propel\Runtime\Connection\ConnectionWrapper->transaction(Object(Closure))
#5 /var/www/html/My-Project/database/classes/pvsite/db/pvsite/PvActivation.php(82): pvsite\db\pvsite\Base\PvActivation->save()
#6 /var/www/html/My-Project/database/classes/pvsite/db/pvsite/PvUser.php(1626): pvsite\db\pvsite\PvActivation->activateLogin(1, '')
#7 /var/www/html/My-Project/database/classes/pvsite/db/pvsite/PvUser.php(1610): pvsite\db\pvsite\PvUser->makeLoginResponse(true, Object(pvsite\db\pvsite\PvUser))
#8 /var/www/html/My-Project/api/player/ProfileController.inc(146): pvsite\db\pvsite\PvUser->makeLogin('admin', 'dffeww69Z5!CZPnF', 0)
#9 [internal function]: pvsite\api\ProfileController->profileLogin()
#10 /var/www/html/My-Project/vendor/slim/slim/Slim/Route.php(468): call_user_func_array(Array, Array)
#11 /var/www/html/My-Project/vendor/slim/slim/Slim/Slim.php(1343): Slim\Route->dispatch()
#12 /var/www/html/My-Project/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call()
#13 /var/www/html/My-Project/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()
#14 /var/www/html/My-Project/vendor/slim/slim/Slim/Middleware/PrettyExceptions.php(67): Slim\Middleware\MethodOverride->call()
#15 /var/www/html/My-Project/vendor/slim/slim/Slim/Slim.php(1288): Slim\Middleware\PrettyExceptions->call()
#16 /var/www/html/My-Project/site/slim.php(121): Slim\Slim->run()
#17 {main}

**Comment by dereuromark** [comment]
Not enough infos and stale.
