### ISSUE TITLE
Drop PHP5 support with a major

### ISSUE THREAD

**Issue by PhilinTv** [propelorm/Propel2#1544]

**Comment by dereuromark** [comment]
To clarify:

The next release (beta) would still be 5.6 compatible to give folks time to update, while allowing the rest to already use php7 (up to 7.4).

The RC and stable releases would then have the PHP7.2+ only approach most likely.
PHP7.1 is already EOL and thus probably not worth keeping as minimum.

**Comment by dereuromark** [comment]
This has already been done now earlier.
