### ISSUE TITLE
Component conflict when installing with Lumen 7.x

### ISSUE THREAD

**Issue by nikeshhajari** [propelorm/Propel2#1545]
Lumen uses newer dependencies for Symfony components:

symfony/console: ^5.0
symfony/error-handler: ^5.0
symfony/http-kernel: ^5.0
symfony/http-foundation: ^5.0
symfony/mime: ^5.0
symfony/var-dumper: ^5.0

Current Propel2 dependencies:
symfony/yaml: ~2.3||~3.0||~4.0
symfony/console: ~2.3||~3.0||~4.0
symfony/finder: ~2.3||~3.0||~4.0
symfony/validator: ~2.3||~3.0.0||~3.1.0||^3.2.4||~4.0
symfony/filesystem: ~2.3||~3.0||~4.0
symfony/config: ~2.3||~3.0||~4.0

Request to update component version to make compatible with Lumen.

**Comment by dereuromark** [comment]
Solved with https://github.com/propelorm/Propel2/pull/1536
