### ISSUE TITLE
Migrate from php 5.6 to 7.x and propel 1.6 to 2

### ISSUE THREAD

**Issue by 41i-6h0rb4n1** [propelorm/Propel2#1554]
We have a customized framework with propel 1.6 and php 5.6.
We are upgrading to php 7.4. Is there any problem to run propel 2 under php 7.4?

**Comment by SourceCode** [comment]
I have the latest master branch running in 7.4 without issue. (Warnings or errors).  Previously there were some count features that would raise warnings but those all look to be resolved from the usage out apps have.

**Comment by nivshah** [comment]
I'm migrating a propel 1.7.1 app to propel 2, also due to upgrading to php7.4.x

Is there a migration guide for propel1.x to propel2.x anywhere? Does anyone have experience with this? OP have you had any luck so far?

**Comment by dereuromark** [comment]
Master is now PHP7.4 compatible, we soon release a new version here.

**Comment by 41i-6h0rb4n1** [comment]
> I'm migrating a propel 1.7.1 app to propel 2, also due to upgrading to php7.4.x
> 
> Is there a migration guide for propel1.x to propel2.x anywhere? Does anyone have experience with this? OP have you had any luck so far?

We have just started this upgrade. If we encounter any problems, I can provide you with some information.
