### ISSUE TITLE
Too few arguments symfony\config\Definition\Builder\TreeBuilder.php

### ISSUE THREAD

**Issue by manaka02** [propelorm/Propel2#1558]
Hello, 
First really thanks for your works, 
I'm working with this using symfony 4 and it works perfectly, but, when I do composer update, it specified that propel update dependancy to symfony 5 and I have this error. I check symfony class and the constructor require 1 argument but the last version of propel give 0, 

hope you can fix it !  

`ArgumentCountError: Too few arguments to function Symfony\Component\Config\Definition\Builder\TreeBuilder::__construct(), 0 passed in \vendor\propel\propel\src\Propel\Common\Config\PropelConfiguration.php on line 32 and at least 1 expected in \vendor\symfony\config\Definition\Builder\TreeBuilder.php on line 26`

here is my propel verison : "propel/propel": "~2.0@dev"

Really Thanks

**Comment by zigu007** [comment]
QuickFix: add `"symfony/config": "4.4.*"` to your project `composer.json`.
We need update: `Propel\Common\Config\PropelConfiguration:32`.
`Symfony\Component\Config\Definition\Builder\TreeBuilder` (`"symfony/config": "5.*"`) needs one parameter at least in `__construct()`.

**Comment by manaka02** [comment]
```
"propel/propel": "~2.0@dev",
        "symfony/config": "4.4.*",
        "symfony/filesystem": "4.4.*",
        "symfony/validator": "4.4.*",
        "symfony/finder": "4.4.*",
        "symfony/console": "4.4.*",
        "symfony/yaml": "4.4.*"
```
Here is my configuration and it works for me!
Thanks
