### ISSUE TITLE
PHP8 Incompatibilities [PHP]

### ISSUE THREAD

**Issue by Incognito** [propelorm/Propel2#1568]
Related to: https://github.com/propelorm/Propel2/issues/1541

Visible in travis “nightly php release” builds. The first obvious issues look like this:

```
Deprecated: Method ReflectionParameter::getClass() is deprecated in /home/travis/build/propelorm/Propel2/vendor/phpunit/phpunit/src/Framework/MockObject/MockMethod.php on line 308
PHP Deprecated:  Method ReflectionParameter::getClass() is deprecated in /home/travis/build/propelorm/Propel2/vendor/phpunit/phpunit/src/Framework/MockObject/MockMethod.php on line 308
```

And

```
Deprecated: Required parameter $modifiedClause follows optional parameter $columnPhpName in /home/travis/build/propelorm/Propel2/tests/Propel/Tests/Runtime/ActiveQuery/ModelCriteriaWithSchemaTest.php on line 58
```

**Comment by Incognito** [comment]
This will likely require an update to Phpunit, which means supported versions of PHP would become incompatible with tests.

**Comment by dereuromark** [comment]
We should try to upgrade phpunit here to 8+
As this is require-dev this shouldn't have a direct impact on projects using this library.

**Comment by Incognito** [comment]
If you can drop php 7.1 you unlock phpunit 8.

**Comment by dereuromark** [comment]
Done in https://github.com/propelorm/Propel2/pull/1618
So that unlocks a follow up PR then here.

**Comment by dereuromark** [comment]
Is anyone interested in further getting this repo PHP 8 ready?
you can either built on top of https://github.com/propelorm/Propel2/pull/1611 - or use a separate branch here.

**Comment by dereuromark** [comment]
@propelorm/propel2 
Pease review https://github.com/propelorm/Propel2/pull/1611 as PR for PHP 8 compatibility now.

We can then release soon a new version.

**Comment by dereuromark** [comment]
We are going to merge the PHP 8 support this week.
Everyone: Please do a check on it if possible.
