### ISSUE TITLE
Drop legacy Symfony support [Symfony]

### ISSUE THREAD

**Issue by Incognito** [propelorm/Propel2#1574]
A lot of code supports long-past-EOL versions of Symfony components. It’s getting harder to validate that we actually support these. For example, when running tests with `composer update --prefer-lowest` they fail. We should drop support for unsupported versions, and we should verify the lowest supported versions still work.

Does this needs a bit of discussion before we can move forward?

![Screenshot from 2020-06-23 09-49-30](https://user-images.githubusercontent.com/379322/85375631-de42c280-b536-11ea-9fa6-62f4aad22d90.png)

**Comment by dereuromark** [comment]
So you want to keep ^3.4, ^4.3, ^5.0
Correct?

**Comment by dereuromark** [comment]
https://github.com/propelorm/Propel2/pull/1590 open

**Comment by Incognito** [comment]
I think even 4.3 and 5.0 can go, they're EOL sooner than Maria 10.1 and php 7.2.

This might be unpopular for the broader community so let's look at symfony/vendor as a benchmark:

![Screenshot from 2020-06-26 12-46-24](https://user-images.githubusercontent.com/379322/85849347-16ead200-b7ab-11ea-8cb0-db8cd0fc7343.png)
![Screenshot from 2020-06-26 12-46-08](https://user-images.githubusercontent.com/379322/85849351-181bff00-b7ab-11ea-8b14-a75729cbf3ff.png)
![Screenshot from 2020-06-26 12-45-55](https://user-images.githubusercontent.com/379322/85849354-181bff00-b7ab-11ea-9dd2-d995991f7a99.png)
![Screenshot from 2020-06-26 12-45-43](https://user-images.githubusercontent.com/379322/85849356-18b49580-b7ab-11ea-9f2d-97e4d165dc8c.png)


It looks like 2.8, 3.4, 4.3, 4.4, and 5.0 are all heavily used. The others are a small fraction of use.

A bit deeper into the data: `Spryker/propel` had 22926 installs over the last 30 days, and `propel/propel` had
35770. So we can assume 64% of propel users are bound to `"spryker/symfony": "^3.0.0"`, which is sub-set for v2 and v3, and excludes some v4 releases. In generally it seems at-least 20% of the 67% propel consumers (15% of all world-wide propel2 users) are not ready to upgrade due to us dropping legacy symfony builds.

So the cost of droppoing is at-least 15% get locked out of updates. I don't know about the other 36% of non-spryker users but if we assume there's another 20% who are held back, it could total to maybe 20% of all propel users are held back (until they update symfony).

**Comment by dereuromark** [comment]
Yeah, but if my PR shows that we can support them without additional pain then we can just do that.

**Comment by dereuromark** [comment]
PR now open.
