### ISSUE TITLE
Unlisted symfony/translation dependency [PHP]

### ISSUE THREAD

**Issue by Incognito** [propelorm/Propel2#1575]
There is an "inherited" dependency on `symfony/translation` due to the dependency on `symfony/validator`, which should become a first-class dependency (listed in composer.json) because it is used by the library under some conditions.

This is especially a problem for us because `validation` doesn't require translation in the more recent versions they ship, so the dependency becomes lost and never gets installed.

It is also important to list which versions will work, because not all versions of `symfony/translation` are backwards-compatible with Propel. Therefore, adding it and limiting it to the actual working range is the ideal way here. The bigger question is: is it an "optional" dependency or not? It could change the way we fix this.

**Comment by dereuromark** [comment]
It is optional if it can be that (and isnt necessary required for the code to run).
And it looks this way

    Symfony\Component\Translation\IdentityTranslator

is the only occurring use statement, and in tests only.
So require dev with the right versions is fine.
