### ISSUE TITLE
Symfony incompatibilities [Symfony]

### ISSUE THREAD

**Issue by Incognito** [propelorm/Propel2#1578]
There are various incompatibility issues regarding upgrading to symfony 5.0 components. Each will need to be investigated. The major obvious blocker right now is the tree configurator root node.

Related:
- https://github.com/propelorm/Propel2/issues/1562
- https://github.com/propelorm/Propel2/issues/1534
- https://github.com/propelorm/Propel2/issues/1574

When digging deeper into inter-major versions of symfony we appear to have even more issues than expected. Here's where CI is failing:

|                 Version                	| All                	| Yaml               	| Config             	| Console            	| Filesystem         	| Finder             	| Translation        	| Validator          	|
|:--------------------------------------:	|--------------------	|--------------------	|--------------------	|--------------------	|--------------------	|--------------------	|--------------------	|--------------------	|
| ~2.7                                   	| :heavy_check_mark: 	| :heavy_check_mark: 	| :heavy_check_mark: 	| :writing_hand:     	| :heavy_check_mark: 	| :heavy_check_mark: 	| :heavy_check_mark: 	| :heavy_check_mark: 	|
| ^2.7                                   	| :heavy_check_mark: 	| :heavy_check_mark: 	| :heavy_check_mark: 	| :writing_hand:     	| :heavy_check_mark: 	| :heavy_check_mark: 	| :heavy_check_mark: 	| :heavy_check_mark: 	|
| ~3.0                                   	| :x:                	| :heavy_check_mark: 	| :heavy_check_mark: 	| :writing_hand:     	| :heavy_check_mark: 	| :heavy_check_mark: 	| :question:         	| :x:                	|
| ^3.1.7                                 	| :heavy_check_mark: 	| :heavy_check_mark: 	| :heavy_check_mark: 	| :writing_hand:     	| :heavy_check_mark: 	| :heavy_check_mark: 	| :heavy_check_mark: 	| :heavy_check_mark: 	|
| ^3.0                                   	| :heavy_check_mark: 	| :heavy_check_mark: 	| :heavy_check_mark: 	| :heavy_check_mark: 	| :heavy_check_mark: 	| :heavy_check_mark: 	| :heavy_check_mark: 	| :heavy_check_mark: 	|
| ~v4.0                                  	| :heavy_check_mark: 	| :heavy_check_mark: 	| :heavy_check_mark: 	| :writing_hand:     	| :heavy_check_mark: 	| :heavy_check_mark: 	| :heavy_check_mark: 	| :heavy_check_mark: 	|
| ^4.0                                   	| :heavy_check_mark: 	| :heavy_check_mark: 	| :heavy_check_mark: 	| :heavy_check_mark: 	| :heavy_check_mark: 	| :heavy_check_mark: 	| :heavy_check_mark: 	| :question:         	|
| v5                                     	| :x:                	| :heavy_check_mark: 	| :writing_hand:     	| :writing_hand:     	| :heavy_check_mark: 	| :heavy_check_mark: 	| :heavy_check_mark: 	| :heavy_check_mark: 	|
| mixed use of v2 <br/>or v3 or v4 or v5 	| :heavy_check_mark: 	| :game_die:         	| :game_die:         	| :game_die:         	| :game_die:         	| :game_die:         	| :game_die:         	| :game_die:         	|

- :writing_hand: = I had to change propel
- :game_die: = you need the magic versions to line up just right on your actual project too.
- :heavy_check_mark: = No problems.
- :x: = Propel doesn't work with this.
- :question: = I don't know why it fails but I suspect this is related.

It appears mixing versions, or using v3, is the only stable build from the min/max range right now.

https://github.com/spryker/Propel2/tree/sf5-validator-translation
https://github.com/spryker/Propel2/tree/sf5-validator-translation-sf5
https://github.com/spryker/Propel2/tree/sf5-validator-translation-sf4-max
https://github.com/spryker/Propel2/tree/sf5-validator-translation-sf4-min
https://github.com/spryker/Propel2/tree/sf5-validator-translation-sf27
https://github.com/spryker/Propel2/tree/sf5-validator-translation-sf3-max
https://github.com/spryker/Propel2/tree/sf5-validator-translation-sf3-min
https://github.com/spryker/Propel2/tree/sf5-validator-translation-sf27-max

**Comment by dereuromark** [comment]
Anything left or is this done?

**Comment by Incognito** [comment]
validator v5, but I'll create a new issue for it.
