### ISSUE TITLE
Add CS standard and sniffer

### ISSUE THREAD

**Issue by dereuromark** [propelorm/Propel2#1592]
Right now no standard checks the project
What about adding https://github.com/spryker/code-sniffer ?
Battle-tested in million runs of Spryker Framework.

**Comment by Incognito** [comment]
+1 if and only if we version lock it. We can use dependabot to auto-bump it.

**Comment by dereuromark** [comment]
Done through https://github.com/propelorm/Propel2/blob/master/composer.json#L49-L50
