### ISSUE TITLE
Documentation for "Using Custom Platform" is incorrect

### ISSUE THREAD

**Issue by SpikedCola** [propelorm/Propel2#1594]
I'm attempting to override the mapping between Propel types and native SQL types.

The docs here http://propelorm.org/documentation/reference/schema.html say:

You must then specify that mapping in the build.properties for your project:
propel.platform.class = propel.engine.platform.${propel.database}Platform

But this leads to the error:
Unrecognized option "platform" under "propel". Available options are "database", "exclude_tables", "general", "generator", "migrations", "paths", "reverse", "runtime".

I believe the correct string is `propel.generator.platformClass = ...` 

Thanks!

**Comment by Incognito** [comment]
Needs PR against https://github.com/propelorm/propelorm.github.com/blob/8bcf1eef407093b225d281021b73cc122cdcbee4/documentation/reference/schema.markdown

**Comment by SpikedCola** [comment]
Created PR # 412 for this issue

**Comment by dereuromark** [comment]
I dont see a PR. Please link it.

**Comment by Incognito** [comment]
https://github.com/propelorm/propelorm.github.com/pull/412

**Comment by SpikedCola** [comment]
Thanks @Incognito

**Comment by dereuromark** [comment]
Closing then this one in favor of docs repo.
