### ISSUE TITLE
Drop EOL Symfony support

### ISSUE THREAD

**Issue by PhilinTv** [propelorm/Propel2#1629]
Symfony ^4.3.0, ^5.0.0 are EOL July 2020.

**Comment by dereuromark** [comment]
we should wait here though for another 1-2 releases
they are currently working and even if EOL, there is no immediate need to clean them out just yet.

we cleaned out the ones we needed to in order to make our test harness work again or were > 6 months EOL.

**Comment by dereuromark** [comment]
I would recommding we drop v3 support now for the beta release. Keeping 4 and 5 is more than enough.

**Comment by mringler** [comment]
Maybe a Symfony expert wants to chime in, but I believe v3 is really outdated by now, so removing it is best.

**Comment by dereuromark** [comment]
We can do that now for the next release.

**Comment by dereuromark** [comment]
Anyone wants to add Symfony6 and drop 3/4?

**Comment by fbourigault** [comment]
I opened #1815 for Symfony 6.

**Comment by fbourigault** [comment]
Do we want to drop support for any unmaintained Symfony version? It would imply dropping <4.4 and 5.0, 5.1 and 5.2. I can open another PR to remove support.

**Comment by dereuromark** [comment]
The <5.2 are not too relevant
This is mainly about the major version(s), So v3

**Comment by fbourigault** [comment]
Removing <4.4 would allow us to remove `src/Propel/Generator/Command/Console/Input/ArrayInput.php` (I diffed it against 4.4.0 ArrayInput and only differences are CS).

Is dropping <4.4 an option?

**Comment by dereuromark** [comment]
Sure, if those changes make sense like here why not. Just dropping for the sake of it (while it would actually still work) would just be a bad change usually.
