### ISSUE TITLE
[Bug][PostGres][json] diff detects change of column type varchar to json

### ISSUE THREAD

**Issue by tienbuide** [propelorm/Propel2#1630]
creating a diff of a database with column type json detects a change from varchar to json.

this is because the `src/Propel/Generator/Reverse/PgsqlSchemaParser.php:288` does not know `json` as a type native Pgsql type and therefore uses `varchar` as a fallback

**Comment by dereuromark** [comment]
Are you able to provide a PR for us here?
This would be great as we plan to do another bugfix release very soon.

**Comment by tienbuide** [comment]
@dereuromark in progress ;)

**Comment by tienbuide** [comment]
@dereuromark here you go. https://github.com/propelorm/Propel2/pull/1631
