### ISSUE TITLE
Undefined index: microtime in Profiler.php:240

### ISSUE THREAD

**Issue by acabutto** [propelorm/Propel2#1646]
It may happen that Profiler::getProfileBetween() is called before Profiler::start(). In that case an error is thrown.

I have just proposed a workaround patch to avoid the problem but somebody with a better understanding of the architecture should investigate a bit.

**Comment by dereuromark** [comment]
Can you open a PR with the suggested changes?

**Comment by acabutto** [comment]
Sure, just opened.

**Comment by dereuromark** [comment]
PR https://github.com/propelorm/Propel2/pull/1647
