### ISSUE TITLE
Object of class Propel\Generator\Model\Table could not be converted to string

### ISSUE THREAD

**Issue by Daenu** [propelorm/Propel2#1649]
https://github.com/propelorm/Propel2/blob/3cc71ba71031c6ca2e0aa82e8c9e2bd01a36c811/src/Propel/Generator/Manager/ReverseManager.php#L254

Array is filled with objects of Type Table in Line 254 it should be $tableName
Otherwise an error occures in Line 260, where the array should implode

**Comment by dereuromark** [comment]
Can you open a PR with your suggested changes here?

**Comment by dereuromark** [comment]
I opened https://github.com/propelorm/Propel2/pull/1650 for now.

**Comment by dereuromark** [comment]
I don't quite understand how this could throw such an error if the __toString() should auto cast this to a string just fine.
It should really only create messy log files, but not halt execution..
