### ISSUE TITLE
Can not build with non-primary foreign key

### ISSUE THREAD

**Issue by chuongnh3atgmaildotcom** [propelorm/Propel2#1659]
Seems #1259 caused an issue when building model with non-primary foreign key.
That case is mentioned in this discussion https://github.com/propelorm/Propel2/pull/1259#discussion-diff-76629831. The discussion hasn't finished and now I'm finding that exact case.

**Steps to Reproduce**
1. foreign key refers to an unique key of $foreignTable instead of its primary key, and foreign table has composite primary key.
    ```
    <?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
    <database name="bookstore" defaultIdMethod="native" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"    namespace="Propel\Tests\Bookstore">
      <table name="event">
        <column name="id" type="integer" required="true" primaryKey="true" autoIncrement="true"/>
        <column name="name" type="varchar" size="50" required="true"/>
        <column name="Event" type="varchar" size="50" required="true"/>
        <column name="organiser_id" type="integer" required="true"/>
        <!-- This FK is incomplete -->
        <foreign-key foreignTable="organiser" name="test_event_fk_Event_organiser_name">
            <reference local="Event" foreign="name"/>
        </foreign-key>
      </table>
      <table name="organiser">
        <!-- Has composite PK -->
        <column name="id" type="integer" required="true" primaryKey="true" autoIncrement="true"/>
        <column name="secondary" type="integer" required="true" primaryKey="true"/>
        <column name="name" type="varchar" size="50" required="true"/>
        <unique>
            <unique-column name="name"/>
        </unique>
      </table>
    </database>
    ```
2.  run `bin/propel model:build`

**Expected Behavior**
Build successfully

**Current Behavior**
error thrown: \Propel\Generator\Exception\BuildException Table "event" contains a foreign key to table "organiser" but does not have a reference to foreign primary key "id"

**Possible Solution**
Do not check for incomplete foreign key if it does not refer to any foreign key

**Comment by dereuromark** [comment]
Are you able to make a PR with suggested changes to fix this?

**Comment by chuongnh3atgmaildotcom** [comment]
@dereuromark 
https://github.com/propelorm/Propel2/pull/1661
