### ISSUE TITLE
toJSON but then lowercase

### ISSUE THREAD

**Issue by MagicLegend** [propelorm/Propel2#1671]
Hi,

I prefer to keep everything in one standard within my codebase. Now is JSON case-sensitive (unfortunately), and I'm having trouble with Propel not giving me the option to change how it outputs JSON. I want to use the `toJSON()` function, but I want all the field names to be lowercase (and not `TYPE_PHPNAME`). I don't want to add post-processing everywhere; and rewriting existing functionality is also not desired. Would it be possible to pass through an optional parameter down to the `exportTo($parser, $includeLazyLoadColumns = true)` function, changing the hardcoded `TableMap::TYPE_PHPNAME`?

I think the change would involve the following:

1. Prepare the enum value here
https://github.com/propelorm/Propel2/blob/ae14a1fb891d1e45be54f8d9c8e016d7a9a4c0e1/src/Propel/Generator/Builder/Om/templates/baseObjectMethodMagicCall.php#L53-L58

2. Change `exportTo()` to accept an extra variable
https://github.com/propelorm/Propel2/blob/0839979f5721f4810b9b02ac8e96e5e8f4358182/src/Propel/Generator/Builder/Om/templates/baseObjectMethods.php#L180-L199

3. Pass it down to `$this->toArray()`
https://github.com/propelorm/Propel2/blob/0839979f5721f4810b9b02ac8e96e5e8f4358182/src/Propel/Generator/Builder/Om/templates/baseObjectMethods.php#L198

----

Possibly it also should be supported here?
https://github.com/propelorm/Propel2/blob/225a124256ccc5b18cf3325988ad1f49ba756811/src/Propel/Runtime/Collection/Collection.php#L541-L571

----

Am I missing anything in this flow? Would this fit in the Propel style? I would be willing to spend some time on building this if there is viability in supplying this setting. Otherwise Ill just have to write something custom for myself to process the keys to lowercase.

**Comment by MagicLegend** [comment]
I went ahead and quickly implemented the mentioned changes. I could not find any tests testing the `$includLadyLoadColumns` parameter either, so I was not 100% sure if and where tests would be desired. Please provide me some feedback on that at the PR: #1672

**Comment by dereuromark** [comment]
PR open.
