### ISSUE TITLE
Security:  * [CVE-NONE-0001][]: SQL injection possible with limit() on MySQL

### ISSUE THREAD

**Issue by DawoudIO** [propelorm/Propel2#1675]
Getting the following from my security scan, based on the link it is closed but unsure why the security db is not updated. 

```
Run symfonycorp/security-checker-action@v2
/usr/bin/docker run --name symfonycorpclilatest_52141a --label 54bb10 --workdir /github/workspace --rm -e INPUT_LOCK -e INPUT_DISABLE-EXIT-CODE -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/CRM/CRM":"/github/workspace" symfonycorp/cli:latest  "check:security" "--dir" "src/composer.lock" "--disable-exit-code=0"
Symfony Security Check Report
=============================

1 package has known vulnerabilities.

propel/propel (2.0.0-alpha11)
-----------------------------

 * [CVE-NONE-0001][]: SQL injection possible with limit() on MySQL

[CVE-NONE-0001]: https://github.com/propelorm/Propel2/issues/1463

Note that this checker can only detect vulnerabilities that are referenced in the security advisories database.
Execute this command regularly to check the newly discovered vulnerabilities.
```

**Comment by DawoudIO** [comment]
any ideas here?

**Comment by dereuromark** [comment]
If you look into https://github.com/propelorm/Propel2/pull/1464/commits/478f938153ee1684d4306ccea3147540546a5586 that merged commit doesn't seem to be part fo this repo.
Probably someone merged that into propel3 or alike.

We might have to backport this into master then and prepare for alpha12 release next week(s).

Are you able to make a PR here?

**Comment by dereuromark** [comment]
But https://github.com/propelorm/Propel2/commit/cd23d7384a15cfe203e23b3a835c8ab1d81d9246 is merged, so yes, this is fixed.
I would suggest fixing the tool that wrongly reports this then maybe.

**Comment by DawoudIO** [comment]
looking at the DB https://github.com/FriendsOfPHP/security-advisories/blob/master/propel/propel/2018-02-14.yaml

looks like alpha7 is the last version but it is erroring out at version 11

**Comment by dereuromark** [comment]
Most likely a tooling problem here, not being able to understand alpha version order or alike.
Known issue with also other tools that use non natural sorting by default here (note how 11 is then < 7 often).

**Comment by DawoudIO** [comment]
That is what I think the issue is also, so I opened https://github.com/FriendsOfPHP/security-advisories/issues/511

maybe next release you can move away from the alpha tag
