### ISSUE TITLE
classPrefix and tablePrefix configuration properties

### ISSUE THREAD

**Issue by cristianoc72** [propelorm/Propel2#1692]
Reviewing a configuration file, I'm wondering if it's time to remove `classPrefix` and `tablePrefix` properties.

-  `classPrefix` was introduced years ago, when Propel was distributed as Pear package. In fact, it's a sort of old style Pear namespace, when PHP (3 and 4 versions) didn's support them. Since Propel2 is distributed via Composer and it adheres to PSRs, the code base and generated classes support namespaces. So, imho there's no need of this option.
-  `tablePrefix' is an old style way to put different projects tables in one single database. Some years ago, host providers often included only one database in their plans, so table prefix was a forced choice in many cases. Today, the cheapest host plan offers almost 5 databases so, imho we could remove this property without problems.

From the code point of view, we can reduce a bit of complexity, by removing several `if` statements (actually, not many).

If you're agree, I can prepare a pull request.

**Comment by dereuromark** [comment]
We could deprecate those for the time being, with or without throwing a notice, and remove it then in the next major release?
We do have one upcoming now the next days, and maybe we shouldn't hard-remove anything that quickly.

**Comment by cristianoc72** [comment]
I'm closing this issue by now: I'll remember it near next major release 😄

**Comment by dereuromark** [comment]
We can still move forward here.
I just hinted that maybe deprecation and then removing is better than removing it right away.
