### ISSUE TITLE
Unable to use php74 preloading because of how table maps are dumped

### ISSUE THREAD

**Issue by prgTW** [propelorm/Propel2#1695]
![image](https://user-images.githubusercontent.com/203249/104244628-1d008180-5463-11eb-9a9a-b5f2714bc1a2.png)

**Comment by prgTW** [comment]
references #361

**Comment by mringler** [comment]
I have created a PR (#1742) which should fix this issue. If you have time to test it, I'd be happy to get some feedback

**Comment by emicks** [comment]
I am using propelorm/Propel2 together with SkyFoxvn/PropelBundle in a Symfony 4.4 application. PR #1742 breaks the application even if the model has been rebuilt, because the database connections are configured via PropelBundle (config coming from config/packages/propel.yaml in the symfony application) and the generated loader script is not included. Is there any workaround for this?

**Comment by mringler** [comment]
Interesting, thank your for reporting.
What error message are you seeing?

**Comment by emicks** [comment]
I'm getting a "Database map was not initialized. Please check the database loader script included by your conf" error. After  (manually) including the generated loadDatabase.php in PropelBundle::configureConnections(), it seems to work. As far as I understood PR #1742, the generated loader is included at the end of the (PHP) config script. However, with PropelBundle, the config is loaded from YAML and connections are  initialized in PropelBundle::boot().

**Comment by mringler** [comment]
Great that you figured it out and it is working. I'd still like to find out what went wrong, so we can fix it.
So, initially, was there no `require_once` at the end of conf.php? Or did it point to another file?
At the top of `conf.php` (line 3), does it check for version 2 (instead of "propel2-dev"):
```
$serviceContainer->checkVersion(2);
```

**Comment by emicks** [comment]
AFAIK, PropelBundle does not use a `conf.php`. With PropelBundle, configuration is loaded from a .yaml file according to the bundle's config info which does not recognize `loaderScriptDir` : https://github.com/SkyFoxvn/PropelBundle/blob/5.0/DependencyInjection/Configuration.php
The connections are then initialized in the boot code of the bundle. If I `require_once` the generated loader in PropelBundle::configureConnections() (line 59 in  https://github.com/SkyFoxvn/PropelBundle/blob/5.0/PropelBundle.php )  it works.  
Perhaps your initial assumption that "_the configuration is the only file that is imported directly into a Propel project_" could be true only for standalone projects, but not for Symfony projects with PropelBundle.

**Comment by mringler** [comment]
jinx

**Comment by mringler** [comment]
Alright, that sucks. Seems like they implemented their own way of configuring Propel, and now the two packages are tightly coupled.
Easiest fix I can think of is for them to check required config version, and if necessary have their `model:build` command (I think they ship their own, right?) set a location for the loader script and then, if necessary, load it during bootstrapping.

A way to check if manual loading is required would be something like
```php
if(defined('StandardServiceContainer::CONFIGURATION_VERSION') 
  && StandardServiceContainer::CONFIGURATION_VERSION >= 2) {
    ...
}

**Comment by SkyFoxvn** [comment]
@mringler yes the bundle configures Propel by his own way. The idea of the bundle is to be simple a wrapper for Propel which basically mean to save you time for configurations by preconfiguring the propel more specifically to work with Symfony file architecture

**Comment by dereuromark** [comment]
We can close this then as there is nothing we can do here on our side as follow up?

**Comment by mringler** [comment]
I think @SkyFoxvn implemented this in the wrapper, nothing to do on Propel side. So this can be closed.
