### ISSUE TITLE
Is there any way to import propel config in tests directory ?

### ISSUE THREAD

**Issue by abdyek** [propelorm/Propel2#1740]
I am learning phpunit to test my model and controller classes. But I couldn't any way to use phpunit with propel orm. I have seen [here](http://propelorm.org/documentation/cookbook/working-with-test-suite.html) but this article made me confused therefore I want to act my scenario to test. I have applied necessary steps in the [The Build Time](http://propelorm.org/documentation/02-buildtime.html) section. My project has a routing library this start from index.php and there is `require 'propel/config.php';` line in index.php. (I changed output directory while build time)
Propel ran perfectly if it used in index.php but it doesn't work properly by phpunit command,
Where am i making a mistake ?

**Comment by mringler** [comment]
You need to import Propel into your tests the same way you import it into your project. Most likely by requiring the autoload file (`require __DIR__ . '/vendor/autoload.php';`).

Don't worry about the "Working with Propel’s Test Suite" documentation, that page is about writing tests for Propel itself, not writing tests for a project which uses Propel.

**Comment by abdyek** [comment]
> 
> 
> You need to import Propel into your tests the same way you import it into your project. Most likely by requiring the autoload file (`require __DIR__ . '/vendor/autoload.php';`).
> 
> Don't worry about the "Working with Propel’s Test Suite" documentation, that page is about writing tests for Propel itself, not writing tests for a project which uses Propel.

Thank you, I imported propel/config.php using require and it ran perfectly.
Actually I didn't see this error when added `require 'propel/config.php';` in my test classes. This error is about my local mysql command line application.
```
...
Caused by
PDOException: SQLSTATE[HY000] [2002] No such file or directory
...
```

You think should I import autoload file? Because propel/config.php looks like enough

**Comment by mringler** [comment]
That's not necessary. If the Propel classes are found, you don't need to include `autoload.php` again.

**Comment by abdyek** [comment]
> 
> 
> That's not necessary. If the Propel classes are found, you don't need to include `autoload.php` again.

Thank you, I will close this issue
