### ISSUE TITLE
add COLLATE to table column postsql

### ISSUE THREAD

**Issue by pishdar** [propelorm/Propel2#1743]
for example:

    <table name="sample" phpname="Sample">
        <column name="name" type="VARCHAR" size="255"  collate="fa-IR-x-icu" />
    </table>
--------------------------------------

CREATE TABLE public."sample"
(
    name character varying(255) COLLATE pg_catalog."fa-IR-x-icu"
);

----------------------------------------
set fa-IR-x-icu to COLLATE column

**Comment by pishdar** [comment]
Also we use, for example:

```
<table name="sample" phpname="Sample">
    <column name="name" type="VARCHAR" size="255"  sqlType='VARCHAR(255) COLLATE pg_catalog."fa-IR-x-icu"' />
</table>
```

```
CREATE TABLE "sample"
(
    "name" VARCHAR(255) COLLATE pg_catalog."fa-IR-x-icu" 
);

```
Resolwe by sqlType.

**Comment by dereuromark** [comment]
Are you willing to do a PR for this?
