### ISSUE TITLE
'Group' Table Name Make Issue on MariaDB

### ISSUE THREAD

**Issue by abdyek** [propelorm/Propel2#1745]
I know _group_, _when_ are rezerved keyword to sql but I can't see warning when generating sql or model classes. Therefore this is should be a bug.

```
PHPUnit 8.5.15 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.0.6
Configuration: /opt/lampp/htdocs/sholist-api/phpunit.xml

......E.....................                                      28 / 28 (100%)

Time: 10.86 seconds, Memory: 8.00 MB

There was 1 error:

1) GroupTest::testGetsByShoppingCardId
Propel\Runtime\Exception\PropelException: Unable to execute INSERT statement [INSERT INTO group (id, shopping_card_id, member_id) VALUES (:p0, :p1, :p2)]

/opt/lampp/htdocs/sholist-api/propel/model/Base/Group.php:819
/opt/lampp/htdocs/sholist-api/propel/model/Base/Group.php:745
/opt/lampp/htdocs/sholist-api/propel/model/Base/Group.php:690
/opt/lampp/htdocs/sholist-api/vendor/propel/propel/src/Propel/Runtime/Connection/TransactionTrait.php:35
/opt/lampp/htdocs/sholist-api/propel/model/Base/Group.php:703
/opt/lampp/htdocs/sholist-api/propel/model/Group.php:23
/opt/lampp/htdocs/sholist-api/tests/unit/Model/GroupTest.php:16

Caused by
PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'group (id, shopping_card_id, member_id) VALUES (?, ?, ?)' at line 1

/opt/lampp/htdocs/sholist-api/vendor/propel/propel/src/Propel/Runtime/Connection/PdoConnection.php:183
/opt/lampp/htdocs/sholist-api/vendor/propel/propel/src/Propel/Runtime/Connection/StatementWrapper.php:81
/opt/lampp/htdocs/sholist-api/vendor/propel/propel/src/Propel/Runtime/Connection/ConnectionWrapper.php:394
/opt/lampp/htdocs/sholist-api/propel/model/Base/Group.php:799
/opt/lampp/htdocs/sholist-api/propel/model/Base/Group.php:745
/opt/lampp/htdocs/sholist-api/propel/model/Base/Group.php:690
/opt/lampp/htdocs/sholist-api/vendor/propel/propel/src/Propel/Runtime/Connection/TransactionTrait.php:35
/opt/lampp/htdocs/sholist-api/propel/model/Base/Group.php:703
/opt/lampp/htdocs/sholist-api/propel/model/Group.php:23
/opt/lampp/htdocs/sholist-api/tests/unit/Model/GroupTest.php:16

```

**Comment by mringler** [comment]
I think you can get Propel to put quotes around the table name by enabling identifier quoting. You can enable it for the table or the whole database by adding the `identifierQuoting` attribute to the respective tag in schema.xml.

I have not tested this, so if you do, please let me know if it works.

Still, I would just rename the table. I suspect the name will keep causing problems somewhere.

If you believe Propel should show a warning, when a table uses a reserved keyword as name, it is probably best if you create a PR for that.

**Comment by abdyek** [comment]
> I think you can get Propel to put quotes around the table name by enabling identifier quoting. You can enable it for the table or the whole database by adding the `identifierQuoting` attribute to the respective tag in schema.xml.
> 
> I have not tested this, so if you do, please let me know if it works.
> 
> Still, I would just rename the table. I suspect the name will keep causing problems somewhere.
> 
> If you believe Propel should show a warning, when a table uses a reserved keyword as name, it is probably best if you create a PR for that.

I tried `identifierQuoting`  attribute to fix it. But it didn't work as expected. I changed schema.xml and generated sql file using `propel sql:build --output-dir="propel" --overwrite`
If you mean contribute propel that saying Pull Request, I am not sure that I can do

**Comment by nederdirk** [comment]
Hey @abdyek , does this still occur on a more recent version? If so, you could perhaps help us with debugging this by telling which _methods_ correspond to the referenced lines in the base-class.

I recently bumped into a similar issue (#1769 ) in our table/models named `order`, but the only occurrence of the text `INSERT` in the base class now has the table name properly quoted.

**Comment by abdyek** [comment]
Hey @nederdirk :smiley: , do you want to me to test `order`, `group` etc. table names with propel master? If so, should i use `identifierQuoting` attribute?

**Comment by nederdirk** [comment]
> Hey @nederdirk smiley , do you want to me to test `order`, `group` etc. table names with propel master? If so, should i use `identifierQuoting` attribute?

Thanks for your reply! Yeah, definitely with the `identifierQuoting` attribute enabled! (that should have been the default, in my opinion, but that's not the issue at hand) A single table with the name of a SQL keyword would be enough to test. Don't hesitate to give plenty of information, like the schema definition, which _functions_  show up in stack traces, and the contents of the referenced lines (and perhaps some lines before and after those, to complete the picture)

**Comment by abdyek** [comment]
> > Hey @nederdirk smiley , do you want to me to test `order`, `group` etc. table names with propel master? If so, should i use `identifierQuoting` attribute?
> 
> Thanks for your reply! Yeah, definitely with the `identifierQuoting` attribute enabled! (that should have been the default, in my opinion, but that's not the issue at hand) A single table with the name of a SQL keyword would be enough to test. Don't hesitate to give plenty of information, like the schema definition, which _functions_ show up in stack traces, and the contents of the referenced lines (and perhaps some lines before and after those, to complete the picture)

I want to test all sql reserved keyword so I created a tiny phpunit generator to test it. But I couldn't complete because it return issue. Issue is here
```bash
PHP Fatal error:  Uncaught ParseError: syntax error, unexpected 'And' (T_LOGICAL_AND), expecting identifier (T_STRING) in /opt/lampp/htdocs/deneme/propel/model/Map/AndTableMap.php:5
Stack trace:
#0 /opt/lampp/htdocs/deneme/vendor/composer/ClassLoader.php(346): Composer\Autoload\includeFile('/opt/lampp/htdo...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('Map\\AndTableMap')
#2 /opt/lampp/htdocs/deneme/vendor/propel/propel/src/Propel/Runtime/Map/DatabaseMap.php(115): spl_autoload_call('Map\\AndTableMap')
#3 [internal function]: Propel\Runtime\Map\DatabaseMap->addTableFromMapClass('\\Map\\AndTableMa...')
#4 /opt/lampp/htdocs/deneme/vendor/propel/propel/src/Propel/Runtime/ServiceContainer/StandardServiceContainer.php(264): array_map(Array, Array)
#5 /opt/lampp/htdocs/deneme/generated-conf/loadDatabase.php(6): Propel\Runtime\ServiceContainer\StandardServiceContainer->initDatabaseMaps(Array)
#6 /opt/lampp/htdocs/deneme/propel/config.php(33): require_once('/opt/lampp/htdo...')
#7 /opt/lampp/htdocs/deneme/tests/M in /opt/lampp/htdocs/deneme/vendor/phpunit/phpunit/src/TextUI/Command.php on line 98
```
But I don't know that is it about sql reserved keyword. Maybe it is my setup issue. I will review again and try to complete tomorrow. Repository link is [here](https://github.com/abdyek/TryingSqlReserved)

**Comment by abdyek** [comment]
Hello @nederdirk again!! :smile: 
I finished testing code in the repository.
**and**, **as**, **case**, **default**, **or** and **primary_key** keywords are making issue I think because these keywords also are php reserved keywords. Other than these passed perfectly as table name and column name.
I hope my answer satisfied you.
Finally, reason of the fatal error in my previous comment this php reserved keywords.

**Comment by nederdirk** [comment]
Hey @abdyek, great researching work! It's a sad thing you can't name a class `And` etc. in PHP, (but I understand it from the parser perspective...)

Would you consider 'I can't give propel classes names of PHP keywords' a new definition of this bug report, or can we close this issue?

**Comment by abdyek** [comment]
> Hey @abdyek, great researching work! It's a sad thing you can't name a class `And` etc. in PHP, (but I understand it from the parser perspective...)
> 
> Would you consider 'I can't give propel classes names of PHP keywords' a new definition of this bug report, or can we close this issue?

 Thank You!! :smiley: We can close this issue :+1:
I want to ask a question before close this issue. Can I pull request for Propel to show notice that if developers use the keywords? If I can do, how do I keep in roadmap of Propel? I've never done a pull request before for large projects. So I think must be rules for it.

**Comment by nederdirk** [comment]
> I want to ask a question before close this issue. Can I pull request for Propel to show notice that if developers use the keywords? If I can do, how do I keep in roadmap of Propel? I've never done a pull request before for large projects. So I think must be rules for it.

@dereuromark Motion to close this issue?

Regarding submitting a PR: there are no global rules for contributing, and in the Propel2 project folks are generally pretty relaxed. Many projects provide a `CONTRIBUTING.md` file in the root of the project to lay out the rules, or a 'Contributing' section in the `README.md`. For Propel2 you'll find that at https://github.com/propelorm/Propel2#contribute . That section specifically states that everyone is welcome to submit a contribution; generally project maintainers will be grateful, especially if you write some paragraphs about why you think the changes are necessary and/or helpful. If you have any open questions don't be afraid to ask for help (e.g. I've asked for help about 'what would be a good method to test this' and have received great answers!)
Don't stress too much about the coding standards, as those will be automatically checked when you submit a contribution.

Peace and all good,
Dirk
