### ISSUE TITLE
Bug with enum default value ...

### ISSUE THREAD

**Issue by phili67** [propelorm/Propel2#1758]
I've to delete the defaultValue in the schema.xml in the case of an enum.

https://github.com/phili67/ecclesiacrm/pull/1886/files

The bug is that propel put a NULL value :

Here's the table :
```
CREATE TABLE `userconfig_ucfg` (
  `ucfg_per_id` mediumint(9) unsigned NOT NULL,
  `ucfg_id` int(11) NOT NULL default '0',
  `ucfg_name` varchar(50) NOT NULL default '',
  `ucfg_value` text,
  `ucfg_type` enum('text','number','date','boolean','textarea','choice') NOT NULL default 'text',
  `ucfg_choices_id` mediumint(9) unsigned NULL,
  `ucfg_tooltip` text NOT NULL,
  `ucfg_permission` enum('FALSE','TRUE') NOT NULL default 'FALSE',
  `ucfg_cat` varchar(20) NOT NULL,
  PRIMARY KEY  (`ucfg_per_id`,`ucfg_id`),
  CONSTRAINT fk_ucfg_choices_id FOREIGN KEY (ucfg_choices_id) REFERENCES userconfig_choices_ucfg_ch(ucfg_ch_id) ON DELETE SET NULL
) ENGINE=InnoDB CHARACTER SET utf8 COLLATE utf8_unicode_ci;
```

I can explain this, in the base model :
```
public function setType($v)
    {
        if ($v !== null) {
            $v = (string) $v;
        }

        if ($this->ucfg_type !== $v) {
            $this->ucfg_type = $v;
            $this->modifiedColumns[UserConfigTableMap::COL_UCFG_TYPE] = true;
        }

        return $this;
    } // setType()
```

but the default value is :
$this->ucfg_type = 'text'

So the code is never been called and strangely I get in the DB : NULL

The default value should be 'text'

**Comment by mringler** [comment]
I have tried your code, but it seems to work for me. Maybe we can figure out together why it does not work on your end. 
Here is what I did:
 - Created the table from your `CREATE TABLE` statement, but with only the enum column (I use MySQL 8.0.25)
 - Reverse engineered the Propel schema using `database:reverse`, which gives me the column like this: 
```
<column name="ucfg_type" phpName="UcfgType" type="CHAR" sqlType="enum('text','number','date','boolean','textarea','choice')" required="true" defaultValue="text"/>
```
- Built the model - it has a `setUcfgType()` method exactly as you gave it. (Note that the default value is applied by the database, not the setter).

Now I can do:
```php
$c1 = new UserconfigUcfg();
$c1->save();
echo $c1->getUcfgType(); // outputs 'text'

$c2 = new UserconfigUcfg();
$c2->setUcfgType('number');
$c2->save();
echo $c2->getUcfgType(); // outputs 'number'
```
Any differences you can spot right away?

Oh, please check that there are no `preInsert()`, `postInsert()`, `preSave()` or `postSave()` hooks that fiddle with the value.

**Comment by phili67** [comment]
The way to reproduce the bug is to do :

$c2 = new UserconfigUcfg();
$c2->setUcfgType('txt');
$c2->save();

For me the mariadb get NULL in the ucfg_type field.

**Comment by mringler** [comment]
When you log into the database and look at the column for a newly inserted row, is the field set there?
i.e.
```
mysql> select * from userconfig_ucfg;
+-----------+
| ucfg_type |
+-----------+
| text      |
| number    |
| text      |
| number    |
| text      |
| number    |
| text      |
| number    |
+-----------+
```

**Comment by phili67** [comment]
Yes it's like this.

**Comment by mringler** [comment]
Hmm, even when switching to MariaDB (10.3.29-MariaDB-0ubuntu0.20.04.1), I cannot reproduce the issue.

My schema:
```xml
    <table name="userconfig_ucfg" idMethod="native" phpName="UserconfigUcfg">
       <column name="id" type="INTEGER" primaryKey="true" autoIncrement="true"/>
       <column name="ucfg_type" phpName="UcfgType" sqlType="enum('text','number','date','boolean','textarea','choice')" required="true" defaultValue="text"/>
       <column name="insertDate" type="timestamp" required="true" defaultExpr="CURRENT_TIMESTAMP"/>
     </table>
```
My test case:
```php
        $c3 = new UserconfigUcfg();
        $c3->setUcfgType('text');
        $c3->save();
        $c3->reload();
        var_export($c3->toArray());
```
Output is:
```php
array (
  'Id' => 6,
  'UcfgType' => 'text',
  'Insertdate' => '2021-06-22 22:29:54.000000',
)
```
(I need the `reload()` to get the value of `Insertdate`, but `UcfgType` is set without it, too.)

In the output, the result is exactly as expected. Now I have no idea how I can help you. Please let me know what I can do to figure this out.
