### ISSUE TITLE
Propel2 Under Another Library

### ISSUE THREAD

**Issue by abdyek** [propelorm/Propel2#1791]
Hello Everyone!

I like Propel ORM and I usually use it for my Php projects. Same way I am developing a library about authentication for php developers and the library uses Propel. I wrote unit test for almost all codes in the library and I think it is stable. But I didn't tag it as stable release. Because a stable released library having not stable dependency is strange. Actually I am not sure that. This is my first library.

Do you think I should downgrade propel in my library for stable release?
Or should I tag stable version for my library?

if you have any idea about my library, please don't hesitate to say it.
My library link is [here](https://github.com/abdyek/whoo)

**Comment by cristianoc72** [comment]
Propel 2 in still in beta but it's much more stable than Propel 1, which is not maintained since (perhaps) 10 years! I think you can release your library as "stable".

**Comment by abdyek** [comment]
> Propel 2 in still in beta but it's much more stable than Propel 1, which is not maintained since (perhaps) 10 years! I think you can release your library as "stable".

Firstly, thanks to reply.
I must be sure that composer won't make issue for this. Can I tag my library as stable even my library has beta dependency and Is this a recommended approach?

**Comment by dereuromark** [comment]
I guess it depends on how to refer to propel as dependency

Does
```
"require": {
    "propel/propel": "~2.0@dev"
  },
```
work?

In general, I would be careful with too permissive declaration as long as we are not in stable semver process.
Spryker, for example, here releases a specific compatibility release per propel release, locking it to a specific version here to be sure:
https://github.com/spryker/propel-orm/blob/master/composer.json#L8

**Comment by abdyek** [comment]
> I guess it depends on how to refer to propel as dependency
> 
> Does
> 
> ```
> "require": {
>     "propel/propel": "~2.0@dev"
>   },
> ```
> 
> work?
> 
> In general, I would be careful with too permissive declaration as long as we are not in stable semver process. Spryker, for example, here releases a specific compatibility release per propel release, locking it to a specific version here to be sure: https://github.com/spryker/propel-orm/blob/master/composer.json#L8

Thanks to reply,
I was tried
```json
"require": {
  "propel/propel": "~2.0@dev"
}
```
or
```json
"require": {
  "propel/propel": "2.0.0-beta1"
}
```
.
I decided that to add `composer require propel/propel:2.0.0-beta1` command in document of my library. I will close this issue.

Good luck with that!
