### ISSUE TITLE
MigrationManager::getFirstUpMigrationTimestamp(): Return value must be of type int, null returned  

### ISSUE THREAD

**Issue by thejager** [propelorm/Propel2#1852]
If there are no migrations to run, this function returns `null`. Shouldn't the return type of this function be `int | null`?

**Comment by dereuromark** [comment]
See https://github.com/propelorm/Propel2/pull/1849/files#diff-bfc5a054d65e7d5aeefe0c7f521961bf2b512862c07ea1c28891e096e4f6f506R327

**Comment by thejager** [comment]
Sorry, thank you!
