### ISSUE TITLE
Migration silently does not run sql statement properly

### ISSUE THREAD

**Issue by filiperochalopes** [propelorm/Propel2#1937]
OS: MacOS Ventura. 
Project (docker ready): https://github.com/filiperochalopes/cadastro-procedimentos-fisioterapia/tree/develop. 

![image](https://user-images.githubusercontent.com/34348097/210441265-1e2e7ad3-457a-4d31-a9a1-0af78e3988f8.png). 

To reproduce:
```sh
# Run containers with docker-compose, unfortunatelly I can't share the initial database sql because it has sensitive data
make run
propel migrate
```

The SQL statement is not working but if I run it in a SQL terminal it runs normaly.

```php
   public function preUp(MigrationManager $manager)
    {

        $pdo = $manager->getAdapterConnection('default');

        $tabela_records = TabelaQuery::create()->find();

        echo "Removendo patentes de fisioterapeutas (tabela)...\n";
        // Removendo patentes e títulos do nome do fisioterapeuta na lista de tabelas
        $sql = "UPDATE tabela SET fisioterapeuta=TRIM(REGEXP_REPLACE(fisioterapeuta, 'GM\\s(\\(S\\)\\s)?|Ten\\.\\s|\\s\\(Estagiári.\\)|CC\\s(\\(S\\)\\s)?|SO\\s|Dr.?\\.\\s', '')) WHERE fisioterapeuta  IS NOT NULL;";
        $stmt = $pdo->prepare($sql);
        $stmt->execute();
```

And the worse part it fails silently and you won't see any warning or error

**Comment by filiperochalopes** [comment]
Running on dbeaver returns ok. 
![image](https://user-images.githubusercontent.com/34348097/210460302-46dacc75-adaf-4589-aa91-ea8a269c9e37.png)

**Comment by mringler** [comment]
If you are not getting an error, it suggests that the conditions are not matched, i.e. the regex needs more backslashes.
Is it only the query with the regex or all statements that are not working?

**Comment by filiperochalopes** [comment]
I also tried debugging with PDO::errorInfo but there is no error showed. It just return `0`

**Comment by mringler** [comment]
Pretty sure your problem comes from the backslashes. You are using double quotes around the regex, PHP will strip those:
```
"\\s" ---PHP--> "\s" ---MySQL Parser--> <non-printable char denoted by \s> ---> Pattern Matcher
```
Try using single quotes or doubling the slashes. Or maybe even tripling? Escapes are a mess.

**Comment by filiperochalopes** [comment]
I tryed single slashes before. I will triple it to test.

**Comment by filiperochalopes** [comment]
Worked with triple slash :face_with_spiral_eyes:
