### ISSUE TITLE
[RFC] Making it easier for 3rd parties to provide integration with Propel and Doctrine

### ISSUE THREAD

**Issue by schmittjoh** [propelorm/Propel2#234]
Just an idea I had to make it easier for authors to design reusable libs.

The idea is to optionally let propel's base class extend a class provided by a library author. That would mean that propel's base class is not at the bottom of the hierarchy anymore, e.g.

BundleModelClass -> extends PropelBaseClass -> extends LibraryClass

Now if that class already has properties with setters and getters, the propel base class would need to take that into account and should not override them, but instead take advantage of what is already provided by the base class (the one from the library).

This would make generation of the propel base class a bit more complex, but it would greatly simplify the life of library/bundle authors, and also benefit propel users by increasing the number of libraries that they can use.

**Comment by dereuromark** [comment]
I will close these stale and old tickets.
We can open new ones as per needs, but they are just collecting dust here.
