### ISSUE TITLE
[RFC] model collections

### ISSUE THREAD

**Issue by havvg** [propelorm/Propel2#266]
What do you think about model specific collections?

Those collections are pre-configured `PropelObjectCollection` for a given model.
They would follow the same principles as each model itself. A `BaseUserCollection` and a `UserCollection` would be created.
A respective `ActiveQuery` will always return an instance of this collection where applicable (not on count() etc.).

This would create a home for collection specific business logic.
### An example use-case

A `User` may create a rated `Review` on a `Product`.
Now the `ProductQuery` would have a method `getReviews` which currently yields a `PropelObjectCollection`.

If you now want to calculate the average value of all attached reviews on the product, you would have to find a home for the new method. Let's say you created a `Product::getAverageReviewRating` which yields the average value of the rating of each review attached to the product. 

This seems fine, but if you want to abstract such behavior, let's say the `Product` is related to a `Manufacturer`.
You could add a `ReviewQuery::filterByManufacturer` which yields another collection. 

If both methods would yield a `ReviewCollection` and you would move the calculation of the average into `ReviewCollection::getAverageRating`, you can call this on any result set provided by any query done by the `ReviewQuery`.

**Comment by SCIF** [comment]
Current state of model collections is some odd: you allowed to hydrate collections by checking of class existence, but generated phpdoc still old and don't contain name collections, which is very useless in IDE. Also, php7 will bring ability to use strict returned type definition, which will rise relevance of current feature (we can check config «use php7 features» flag in config and generate according code).

I suggest add boolean key «generator.named_collections» to configuration or attribute to database in schema. We can add this feature as disabled by default if you afraid to generate large amount of files, but user will have ability to decide which strategy to use. Cli key for command is some little bit worse for me, but much better than nothing :).

**Comment by dereuromark** [comment]
We will have to open a new discussion here for 2022+
