### ISSUE TITLE
Improve enum type to embrace JSR303 Bean validation-like

### ISSUE THREAD

**Issue by ludofleury** [propelorm/Propel2#293]
At the moment, when you define an enum type on a field, the generated setter has some logic.
When you set an invalid value on a setter it throws an exception. That's cool, yet it breaks the validation process.

Providing an option to generate a "zero-logic" setter for this kind of field could be a simple solution to enable the standard validation process to collect a violation instead of catching an instant error.

**Comment by dereuromark** [comment]
We will have to open a new discussion here for 2022+
