### ISSUE TITLE
[RFC] remove static initialization of TableMap

### ISSUE THREAD

**Issue by jaugustin** [propelorm/Propel2#361]
We need to find a good way to initialize the `TableMap`classes and remove the static call 
`TableMap::buildTableMap()` at the bottom of each `TableMap`classes

Maybe we could use :
- composer class mapping (to auto discover classes)
- use the propel container
- ...

**Comment by dereuromark** [comment]
@mringler Can we close this with latest changes done?

**Comment by mringler** [comment]
Yes, we handled this. Let's close the issue.
