### ISSUE TITLE
Benchmark with other version and libraries

### ISSUE THREAD

**Issue by vlastv** [propelorm/Propel2#478]
| Library | Insert | findPk | complex | hydrate | with | memory usage | time |
| --: | --: | --: | --: | --: | --: | --: | --: |
| PDO | 71 | 78 | 58 | 57 | 55 | 768,832 | 0.32 |
| Propel16 | 181 | 121 | 85 | 151 | 166 | 9,699,328 | 0.71 |
| Propel16WithCache | 117 | 67 | 76 | 129 | 130 | 9,699,328 | 0.53 |
| Propel17 | 167 | 105 | 82 | 151 | 166 | 9,437,184 | 0.68 |
| Propel17WithCache | 118 | 69 | 70 | 117 | 109 | 9,699,328 | 0.49 |
| Propel20 | 183 | 116 | 83 | 180 | 179 | 12,320,768 | 0.75 |
| Propel20WithCache | 129 | 78 | 81 | 153 | 143 | 10,747,904 | 0.59 |
| Propel20FormatOnDemand | 128 | 76 | 77 | 146 | 144 | 6,029,312 | 0.58 |
| Doctrine24 | 305 | 260 | 152 | 458 | 461 | 16,252,928 | 1.67 |
| Doctrine24WithCache | 305 | 251 | 81 | 283 | 211 | 16,777,216 | 1.17 |
| Doctrine24ArrayHydrate | 304 | 256 | 82 | 158 | 137 | 15,728,640 | 0.97 |
| Doctrine24ScalarHydrate | 306 | 252 | 82 | 127 | 114 | 15,728,640 | 0.92 |
| Doctrine24WithoutProxies | 304 | 252 | 83 | 214 | 307 | 15,990,784 | 1.20 |

After merge PR #482 

| Library | Insert | findPk | complex | hydrate | with | memory usage | time |
| --: | --: | --: | --: | --: | --: | --: | --: |
| Propel20 | 184 | 118 | 88 | 179 | 180 | 5,767,168 | 0.75 |
| Propel20WithCache | 126 | 76 | 79 | 150 | 144 | 5,767,168 | 0.58 |
| Propel20FormatOnDemand | 129 | 76 | 78 | 146 | 145 | 5,767,168 | 0.58 |

**Legend**
In columns of "Insert", "findPk", "complex", "hydrate" and "with" represents the time in milliseconds. 
In column "memory_usage" stated real memory usage in bytes, including the necessary classes to library work.
In column "time" indicates the time taken to perform all tests in seconds.
The lower the value, the better, for all the columns.

_Please do not close this issue, I will be updated periodically._

_My repository for this tests https://github.com/vlastv/php-orm-benchmark_

**Comment by motin** [comment]
Updated 2015-Dec-07 - including Yii 1, Yii 2, LessQL and Eloquent shows that Propel 2 is rather slow compared to the competition these days.

## PHP-FPM 5.6.4 with opcode cache

| Library                          | Insert | findPk | complex| hydrate|  with  | memory usage |  time  |
| --------------------------------:| ------:| ------:| ------:| ------:| ------:| ------------:| ------:|
|                              PDO |    111 |    121 |     15 |     78 |    221 |      774,944 |   0.55 |
|                           LessQL |    313 |    335 |    100 |    220 |    281 |    5,494,704 |   1.42 |
|                                  |        |        |        |        |        |              |        |
|                             YiiM |    683 |    332 |     99 |    195 |    104 |    9,175,040 |   2.18 |
|                    YiiMWithCache |    632 |    360 |    106 |    179 |    116 |    9,175,040 |   1.96 |
|                                  |        |        |        |        |        |              |        |
|                            Yii2M |   1207 |   1198 |    141 |    483 |    302 |   13,369,344 |   4.56 |
|                Yii2MArrayHydrate |   1662 |    872 |    131 |    264 |    217 |   13,631,488 |   3.81 |
|               Yii2MScalarHydrate |   1314 |    964 |    140 |    225 |    239 |   13,631,488 |   3.80 |
|                                  |        |        |        |        |        |              |        |
|                         Propel20 |    568 |    183 |    377 |    747 |    824 |   10,747,904 |   4.19 |
|                Propel20WithCache |    377 |    114 |    389 |    576 |    690 |   10,747,904 |   3.61 |
|           Propel20FormatOnDemand |    393 |    129 |    241 |    629 |    748 |   11,010,048 |   3.42 |
|                                  |        |        |        |        |        |              |        |
|                        DoctrineM |    758 |   1023 |   1087 |    639 |    598 |   16,515,072 |   8.41 |
|               DoctrineMWithCache |    776 |   1096 |   1224 |    879 |    637 |   15,990,784 |   9.18 |
|            DoctrineMArrayHydrate |    800 |   1103 |    857 |    430 |    588 |   15,990,784 |  10.19 |
|           DoctrineMScalarHydrate |    910 |   1285 |   1774 |    336 |    453 |   15,990,784 |  11.83 |
|          DoctrineMWithoutProxies |    805 |   1190 |   1282 |    518 |    751 |   15,990,784 |  12.47 |
|                                  |        |        |        |        |        |              |        |
|                         Eloquent |   1206 |    733 |    188 |    289 |    527 |   11,272,192 |   4.36 |
|             EloquentWithoutEvent |   1051 |    707 |    175 |    308 |    833 |   11,010,048 |   3.92 |

## HHVM 3.10.1

| Library                          | Insert | findPk | complex| hydrate|  with  | memory usage |  time  |
| --------------------------------:| ------:| ------:| ------:| ------:| ------:| ------------:| ------:|
|                              PDO |     58 |     29 |     10 |     40 |     92 |      763,920 |   0.25 |
|                                  |        |        |        |        |        |              |        |
|                           LessQL |    187 |    211 |     68 |     86 |    152 |   10,328,440 |   0.80 |
|                                  |        |        |        |        |        |              |        |
|                             YiiM |    383 |    201 |    111 |     85 |     46 |    6,325,032 |   1.09 |
|                    YiiMWithCache |    384 |    212 |    111 |     92 |     52 |    6,343,648 |   1.11 |
|                                  |        |        |        |        |        |              |        |
|                            Yii2M |    558 |    397 |     88 |     92 |     56 |    8,711,264 |   1.86 |
|                Yii2MArrayHydrate |    566 |    348 |     90 |     83 |     57 |    8,744,344 |   1.77 |
|               Yii2MScalarHydrate |    561 |    350 |     90 |     68 |     57 |    8,746,528 |   1.76 |
|                                  |        |        |        |        |        |              |        |
|                         Propel20 |    426 |    128 |    639 |    451 |    532 |   10,362,480 |   2.72 |
|                Propel20WithCache |    388 |     92 |    615 |    394 |    455 |   10,422,936 |   2.46 |
|           Propel20FormatOnDemand |    352 |     92 |    605 |    309 |    482 |   10,449,600 |   2.36 |
|                                  |        |        |        |        |        |              |        |
|                        DoctrineM |    642 |    655 |    904 |    436 |    318 |   19,621,456 |   5.55 |
|               DoctrineMWithCache |    658 |    682 |    948 |    452 |    338 |   19,631,944 |   5.72 |
|            DoctrineMArrayHydrate |    627 |    664 |    911 |    224 |    240 |   18,423,328 |   5.27 |
|           DoctrineMScalarHydrate |    636 |    659 |    949 |    159 |    202 |   17,339,720 |   5.17 |
|          DoctrineMWithoutProxies |    663 |    702 |    905 |    282 |    344 |   19,384,088 |   5.46 |
|                                  |        |        |        |        |        |              |        |
|                         Eloquent |    633 |    298 |    110 |    101 |    215 |   13,945,632 |   1.75 |
|             EloquentWithoutEvent |    597 |    318 |    126 |    122 |    242 |   13,865,192 |   1.77 |       

Note: The reference is the PDO TestSuite (the number of tests is adjusted to make raw PDO score about 100 to each test). For the ORMs, the smaller score is the better (i. e. the faster).

**Comment by Big-Shark** [comment]
@motin Please test on the php7 too

**Comment by motin** [comment]
@Big-Shark Sure, will do

**Comment by motin** [comment]
## PHP-FPM 7.0.0 GA

| Library                          | Insert | findPk | complex| hydrate|  with  | memory usage |  time  |
| --------------------------------:| ------:| ------:| ------:| ------:| ------:| ------------:| ------:|
|                              PDO |     78 |     89 |      4 |     74 |    207 |    1,720,072 |   0.45 |
|                                  |        |        |        |        |        |              |        |
|                           LessQL |    207 |    188 |     89 |    181 |    169 |   10,108,848 |   1.09 |
|                                  |        |        |        |        |        |              |        |
|                             YiiM |    437 |    193 |     87 |    116 |     84 |    4,194,304 |   1.70 |
|                    YiiMWithCache |    409 |    201 |    100 |    106 |     81 |    4,194,304 |   1.55 |
|                                  |        |        |        |        |        |              |        |
|                            Yii2M |    530 |    624 |     80 |    169 |    122 |    6,291,456 |   3.01 |
|                Yii2MArrayHydrate |    515 |    489 |     84 |    130 |    107 |    8,388,608 |   2.17 |
|               Yii2MScalarHydrate |    483 |    369 |     98 |    119 |    129 |    8,388,608 |   2.31 |
|                                  |        |        |        |        |        |              |        |
|                         Propel20 |    404 |     95 |    375 |    534 |    534 |    6,291,456 |   4.11 |
|                Propel20WithCache |    257 |     58 |    358 |    470 |    413 |    6,291,456 |   3.54 |
|           Propel20FormatOnDemand |    358 |     54 |    482 |    426 |    464 |    6,291,456 |   4.40 |
|                                  |        |        |        |        |        |              |        |
|                        DoctrineM |    846 |   1396 |   3220 |    569 |    570 |   14,680,064 |  20.79 |
|               DoctrineMWithCache |    547 |    722 |   1106 |    353 |    349 |   14,680,064 |  16.96 |
|            DoctrineMArrayHydrate |    504 |    936 |   2698 |    285 |    523 |   14,680,064 |  13.22 |
|           DoctrineMScalarHydrate |    753 |   1085 |   1567 |    197 |    377 |   14,680,064 |  19.21 |
|          DoctrineMWithoutProxies |    496 |    871 |   1762 |    247 |    544 |   14,680,064 |  13.05 |
|                                  |        |        |        |        |        |              |        |
|                         Eloquent |    709 |    478 |    147 |    223 |    451 |    8,388,608 |   3.34 |
|             EloquentWithoutEvent |    610 |    347 |    148 |    207 |    364 |    8,388,608 |   2.35 |

**Comment by Big-Shark** [comment]
@motin Today I found yii cheating and fixed it, also updated propel, eloquent, yii2 and doctrine orm.
https://travis-ci.org/Big-Shark/forked-php-orm-benchmark

**Comment by motin** [comment]
@Big-Shark Great, I updated the results for all benchmarks in the readme of https://github.com/Big-Shark/forked-php-orm-benchmark, and they are vastly different from last time. Lesson: We should make sure to get consistent, reproducible results before interpreting the numbers too much.

**Comment by marcj** [comment]
>https://travis-ci.org/Big-Shark/forked-php-orm-benchmark 

cool :) :+1:

**Comment by marcj** [comment]
But I guess there is something wrong with memory detection. Yii and Propel2 have the same memory `8,388,608`, which is rather highly unusual.

**Comment by Big-Shark** [comment]
@marcj It's very strangely, but we running every test for different thread, and calculate memory for thread
https://github.com/Big-Shark/forked-php-orm-benchmark/blob/master/propel_20/TestRunner.php
https://github.com/Big-Shark/forked-php-orm-benchmark/blob/master/propel_20/TestRunnerPropel20TestSuite.php

**Comment by motin** [comment]
Just guessing, but the memory may be reserved in discrete chunks.
