### ISSUE TITLE
Getting the PDO connection instance

### ISSUE THREAD

**Issue by CMCDragonkai** [propelorm/Propel2#509]
How do you extract the PDO connection instance out of Propel? I have libraries that depend on the PDO instance, I would like to use the same PDO connection for all the libraries.

Furthermore, is there way to customise which folders Propel generates its models?

**Comment by murraycollingwood** [comment]
This is a protected var and there are no getters in this class. 
<img width="341" alt="Image" src="https://github.com/user-attachments/assets/25e1d6d1-a92a-4836-acd8-65e59c8aca00" />

I need to pass the PDO object to this class:
`$server = new Sabre_CalDAV_Server($pdo);
`

So now I'm having to create my own object:
`$pdo = new PDO($dsn, $user, $password, $pdoOptions);
`

It would have been easier if I could have called a function to get the actual PDO object from Propel2.
How hard would that have been????

Cheers
Murray
