### ISSUE TITLE
Identifier Quoting on update no longer happening

### ISSUE THREAD

**Issue by chrisnoden** [propelorm/Propel2#781]
An UPDATE, by modifying a model object and issuing an $obj->save(), no longer results in the identifiers in the SQL (MySQL) being quoted. Last working version was #a60e310907eccaa107aa0db5648802a731d88c41

Attempting to enable the identifier quoting in the Model class has no effect:

    public function buildCriteria()
    {
        $criteria = parent::buildCriteria(); // calls Base/Model parent method
        $criteria->setIdentifierQuoting(true);
        return $criteria;
    }

This creates a problem for field names that use reserved words (such as 'read') which should be back-tick quoted in the MySQL query.

**Comment by said-jomedia** [comment]
Thank you so much. Know it's working.

**Comment by greddyatpt** [comment]
Is there a way to add the `identifierQuoting` attribute to a reverse-engineered schema automatically?  That way we can have a script generate the schema, build the model classes, convert the configuration, and refresh autoload code without any manual editing.  Don't want to use XSLT if I can avoid it.

**Comment by marcj** [comment]
@greddyatpt, no, but you can easily edit it using simplexml of PHP and set there `<database name="foo" identifierQuoting="true">'

**Comment by rimas-kudelis** [comment]
Is there a reason why this is not on by default?

**Comment by rimas-kudelis** [comment]
Also, this setting seems to have no effect on the sql statement generated in the `findPkSimple()` method. :(
