### ISSUE TITLE
toJSON => fromJSON doesn't works

### ISSUE THREAD

**Issue by daniele-webmaori** [propelorm/Propel2#784]
```php
/*
 * EXPORT
 */

$export = $form->toJSON();
// {"Id":16,"Name":"asd","AdminFrom":"asd","AdminSubject":"asd","AdminTo":"asd","CreatedBy":1,"CreatedAt":{"date":"2014-10-01 15:32:26","timezone_type":3,"timezone":"Europe\/Rome"},"ModifiedBy":1,"ModifiedAt":{"date":"2014-10-16 16:35:41","timezone_type":3,"timezone":"Europe\/Rome"},"Overwrote":false}

/*
 * IMPORT
 */

$form->fromJSON($export);

// Fatal error: Uncaught exception 'Exception' with message 'DateTime::__construct() expects parameter 1 to be string, array given' in /var/www/repo/kmaori/k-components/composer/propel/propel/src/Propel/Runtime/Util/PropelDateTime.php:90 Stack trace: #0 /var/www/repo/kmaori/k-components/composer/propel/propel/src/Propel/Runtime/Util/PropelDateTime.php(90): DateTime->__construct(Array) #1 /var/www/repo/kmaori/k-includes/models/Base/Form.php(666): Propel\Runtime\Util\PropelDateTime::newInstance(Array, NULL, 'DateTime') #2 /var/www/repo/kmaori/k-includes/models/Base/Form.php(1412): Base\Form->setCreatedAt(Array) #3 /var/www/repo/kmaori/k-includes/models/Base/Form.php(1444): Base\Form->fromArray(Array, 'phpName') #4 /var/www/repo/kmaori/k-includes/models/Base/Form.php(2459): Base\Form->importFrom('JSON', '{"Id":16,"Name"...') #5 /var/www/repo/kmaori/k-plugins/form/lib/FormQuery.php(21): Base\Form->__call('fromJSON', Array) #6 /var/www/repo/kmaori/k-plugins/form/lib/FormQuery.php(21): Form->fromJSON('{"Id":16,"Name"...') #7 /var/ in /var/www/repo/kmaori/k-components/composer/twig/twig/lib/Twig/Template.php on line 294


```

**Comment by fitefoe** [comment]
Thank you for the fix, that works very well. In my application a timestamp is serialized like this: `2014-12-31T20:30:00+0100`

For me it would be better, if the timestamp is returned in UTC rather than a local time.
Instead of `format(\DateTime::ISO8601)` you could use `format('Y-m-d\TH:i:s\Z')`, which is ISO8601 in UTC. What do you think?

**Comment by andrenarchy** [comment]
+1 for UTC!

**Comment by mpscholten** [comment]
Thanks for the suggestion. I think it's a good idea to use UTC. Could you just check the code: https://github.com/mpscholten/Propel2/commit/5c02e92a250725c20ec313916a5789caf73f7c2f

If everything is fine I'll open a pull request :)

**Comment by fitefoe** [comment]
Works great, thank you! I just noticed that my PHP-code was using local time when interpreting Datetime values from the MySQL-DB, so I added `date_default_timezone_set("UTC");` (maybe someone else is facing the same problem)

**Comment by fitefoe** [comment]
In some parts of my code I use `toArray()` combined with `json_encode()`. The `toArray()` function still serializes the date to an array (like `toJSON()` did before). What do you think about handling dates in both functions the same way? Should I open a new issue for that?

**Comment by staabm** [comment]
So do you mean that `$model->fromArray($model->toArray());` leads in the same fatal error?

**Comment by mpscholten** [comment]
It's basically an issue of php's `json_encode` method. Can't you rewrite your code to use propel's native `toJson`?

**Comment by andrenarchy** [comment]
@staabm `$model->fromArray($model->toArray())` seems to work fine.

@mpscholten in some cases you may want to get a JSON-array representation of a collection. This works with `toJSON()` but it wraps the array in a JSON-object. It would be great if you could run something like
```php
json_encode(array( "users" => $users->toArray(), "books" => $books->toArray() ));
```
and get proper ISO8601 timestamps.

The conversion of a `DateTime` instance into an array with keys `date`, `timezone_type` and `timezone` already takes place in `toArray()`, see http://sandbox.propelorm.org/5f8b9ec. As a propel newbie, I'd expect that `toArray()` and `toJSON()` use the same serialization for DateTime instances. What do you think about using ISO8601 in both functions?

**Comment by mpscholten** [comment]
> The conversion of a DateTime instance into an array with keys date, timezone_type and timezone already takes place in toArray(), see http://sandbox.propelorm.org/5f8b9ec.

No, it's a `\DateTime` instance there. It just looks like an array because of some `var_dump`-magic. `print_r` is more explicit here: http://sandbox.propelorm.org/c046968:
```
rray
(
    [Id] => 1
    [Title] => My Heros
    [ReleaseDate] => DateTime Object // <---------
        (
            [date] => 2015-01-04 13:39:48
            [timezone_type] => 3
            [timezone] => Europe/Berlin
        )

)
```

**Comment by andrenarchy** [comment]
@mpscholten oh sorry, I overlooked that. You're right! So `json_encode` is to blame. ;) Is there any way of using the `JsonSerializable` class as suggested [here](http://php.net/manual/de/jsonserializable.jsonserialize.php#111263)? Maybe propel can extend the DateTime class and overwrite `JsonSerialize()`?

**Comment by mpscholten** [comment]
You could use propel's `JsonParser` as a workaround:
```php
$parser = new \Propel\Runtime\Parser\JsonParser();
$parser->toJSON(['users' => $users->toArray(), 'books' => $books->toArray()]);
```

But I agree that you'd expect `json_encode` to just work fine.

> What do you think about using ISO8601 in both functions?

We should do that. There are use cases where an array with the `DateTime` objects is more useful, but IMO the json functionallity is more useful.

> Maybe propel can extend the DateTime class and overwrite JsonSerialize()

That's a really great idea! :) This way we can keep the `toArray` behavior and still fix the json stuff. Propel already provides a way to overwrite the `DateTime` class in the config. We could add the new class and then set the default `DateTime` class to the new "patched" class.

**Comment by marcj** [comment]
We should rather handle this extra rules of data converting into the appropriate method `toArray` or `toJson` like in #850.

**Comment by marcj** [comment]
Another question is: Should ´toArray` really only convert a object to an array or all its field values also from object to non-object representation? I'm not sure about that.

**Comment by mpscholten** [comment]
We can only handle this in `toArray` if we agree that `toArray` should convert all fields to primitives. Otherwise we should patch `\DateTime`. Let's try to find a use case where `toArray` without primitives makes sense. In case we can't find a good one, we should change the behaviour of the method.

It's really sad that this is not already solved by php, it's not that uncommon to `json_encode` a `DateTime`

**Comment by marcj** [comment]
We can't subclass `\DateTime` to fix it because you can overwrite the setter of this field and internal is then again a `\Datetime` object stored. This is internal stuff, the developer shouldn't know about that fact. So it has definitely go into `toArray`.

**Comment by andrenarchy** [comment]
As a non-expert with propel, I like the idea that `toArray()` converts all objects to primitives.

Just reading @marcj's comment, it seems that `toArray()` has to be adapted analogously to `toJSON()`.

**Comment by mpscholten** [comment]
> This is internal stuff, the developer shouldn't know about that fact. 

That's true. Then let's change `toArray` to only return primitives. By doing this we can also remove the patch from the `JsonParser` because it encodes the result of `toArray`.

**Comment by mpscholten** [comment]
Just hacked together this: https://github.com/mpscholten/Propel2/commit/3a2bc561af62f37c610f08d7f23abab57e52e494

**Comment by marcj** [comment]
Looks good @mpscholten :smiley:

**Comment by mpscholten** [comment]
@andrenarchy could you check whether this fixes your initial problem? Then I'll open a pull request :)

**Comment by andrenarchy** [comment]
@mpscholten thx, works like a charm! :smiley:
