### ISSUE TITLE
checkstyle for schema

### ISSUE THREAD

**Issue by staabm** [propelorm/Propel2#789]
would be great if we could provide a tool,
which can check the database schema for naming conventions.

this should not be part of propel2 but could be a separate (cli?)-tool and might even work for propel1+propel2 in case we base it on `schema.xml`. When based on plain sql, it could even work for things beyond propel.

idea stolen from @lstrojny
https://twitter.com/lstrojny/status/522835622466043906

**Comment by dereuromark** [comment]
Given the low feedback I will close for now. PRs always welcome.
