### ISSUE TITLE
Ping function

### ISSUE THREAD

**Issue by drodil** [propelorm/Propel2#798]
Hi,

Is there already functionality to ping the database in Propel? I have a long running process that might not do anything in long time and the database might go away during that time (database is MySQL and error code I see sometimes is 2006 MySQL server has gone away). It would be nice to have some kind of functionality to ping the database during this process for example every 15 minutes or so. For MySQL there is mysqli_ping function but for other databases it might need some other functions like SELECT 1; or so. 

What do you think?

**Comment by geniuscd** [comment]
Hey i know its closed, but im also facing this issue. any fixes?
