### ISSUE TITLE
Throw exceptions instead of returning null when no row found

### ISSUE THREAD

**Issue by mpscholten** [propelorm/Propel2#803]
Propel's Query classes should be able to throw exceptions instead of returning null when no object was when calling `find()`.

This could look like:
```php
$post = PostQuery::create()->filterById($id)->findOneOrFail();
```
The `findOneOrFail` method would throw an exception (should be configurable in the propel build settings) in case no Post with the specific id is found.

---

This is how laravel's eloquent implements this:
```php
$post = Post::findOrFail(1);
```
*(see http://laravel.com/docs/4.2/eloquent)*

This is how Rails ActiveRecord implements this:
```ruby
post = Post.find(id) # will raise an ActiveRecord::RecordNotFound exception when no post found
```
*(see http://guides.rubyonrails.org/active_record_querying.html)*

---

The advantage you gain by throwing exceptions instead of returning null is that you now don't need to check for null in any controller actions your mvc application has. The exception can be catched at a central point (e.g. the symfony kernel would catch the exception, or your front controller, or your plain old index.php) and a generic 404 error message could be rendered.

With the current propel query interface our controller action might look like this:
```php
public function show($id) {
    $post = PostQuery::create()->findOneById($id);
    if ($post === null) {
        throw new \NotFoundException('Post not found');
    }
   
    return $post;
}
```

With the new interface this could look like this:
```php
public function show($id) {
    return PostQuery::create()->filterById($id)->findOneOrFail();
}
```
```yml
propel:
  generator:
    exceptionClass: NotFoundException # Propel should also provide a default ResourceNotFoundException out of the box
```

You can see that the "new" controller is very elegant and does not has to worry about the error handling.

---

I'd appreciate any feedback on this idea, so let me know what you think about this :)

**Comment by vworldat** [comment]
Totally forgot to answer once more:

> That's true. But as suggested by @Celc we could add a feature flag for this, so propel1 users can use the old behaviour.

This would split all propel dependent code (think libraries/bundles/plugins) into pre-BC and post-BC (feature on/off), since hardly anything would work in both situations. No, if we have to break, we should just do it and get it over with. I'm just not convinced this break is needed at all, since the non-breaking wording (`requireOne`) sounds much better to me.

**Comment by mpscholten** [comment]
> This would split all propel dependent code

That's true. I think we should just go with the require api now because of bc. Maybe we can do this for propel 3 ... :)
