### ISSUE TITLE
Could not open input file :bin\propel windows

### ISSUE THREAD

**Issue by cansozeri** [propelorm/Propel2#814]
Hi,

I am using propel on windows and I can not use the command line because of this error. 

Could not open input file :bin\propel

It is related about propel.bat... I think there is a something different configuration needed for windows in this bat file...

```
@echo off

if "%PHPBIN%" == "" set PHPBIN=php
if not exist "%PHPBIN%" if "%PHP_PEAR_PHP_BIN%" neq "" goto USE_PEAR_PATH
GOTO RUN
:USE_PEAR_PATH
set PHPBIN=%PHP_PEAR_PHP_BIN%
:RUN
"%PHPBIN%" "bin\propel" %*

```

**Comment by jagadishnallappa** [comment]
Mates, 
Adding the following lines in system environment variables worked for me.
This didn't work for me
proj_path\vendor\propel\propel\bin
This did
proj_path\vendor\bin

Sorry if this might seem stupid. I did the first one and it didn't work. Perhaps someone else might do the same mistake.
