### ISSUE TITLE
Propel2 schema?

### ISSUE THREAD

**Issue by gossi** [propelorm/Propel2#823]
Is there a propel2 schema available? My propel2 schema.xml at the moment start like this:

``` xml
<database defaultIdMethod="native" name="<name>" namespace="<ns>" identifierQuoting="true"
    defaultPhpNamingMethod="phpname" xmlns:xsi="http://www.w3.org/2001/XMLSchema-inposition"
    xsi:noNamespaceSchemaLocation="http://xsd.propelorm.org/1.6/database.xsd">
```

Well, at least `identifierQuoting` isn't recognized in the 1.6 xsd, which my IDE is happy to report me, with all red signals it has :grin:

I wonder, if there is a new schema, which I didn't found or if there is none, which needs to be created at first.

**Comment by dereuromark** [comment]
Looks like `http://xsd.propelorm.org/1.6/database.xsd` is dead. Is there any change of reviving it?

**Comment by DawoudIO** [comment]
any update on a new URL for `http://xsd.propelorm.org/1.6/database.xsd`

**Comment by dereuromark** [comment]
We found that for PHPStorm it is also enough to just have this file inside the vendor library. It will be found and used.
Maybe someone can make a PR to include it? If it is already somewhere, we can close.

**Comment by jb-lesep** [comment]
test this https://raw.githubusercontent.com/propelorm/Propel/master/generator/resources/xsd/database.xsd

**Comment by darki666** [comment]
test this https://raw.githubusercontent.com/propelorm/Propel/master/generator/resources/xsd/database.xsd
