### ISSUE TITLE
Propel ORM returns error, while executing INSERT statement

### ISSUE THREAD

**Issue by sweet-watermelon** [propelorm/Propel2#828]
I have this schema.xml config:

```
<?xml version="1.0" encoding="UTF-8"?>
<database name="manager" defaultIdMethod="native">
    <table name="users" phpName="Users">
        <column name="id" type="integer" required="true" primaryKey="true" autoIncrement="true" />  
        <column name="name" type="varchar" size="128" required="true" />
        <column name="desc" type="longvarchar" required="true" />
    </table>
</database>
```

And i have this php code

```
$user = new Users();
$user->setName('admin');
$user->setDesc('');
$user->save();
```

And i get this error

```
Unable to execute INSERT statement [INSERT INTO users (id, name, desc) VALUES (:p0, :p1, :p2)]
```

I use latest version of slim framework and latest version of Propel ORM. I write script 2 moutn ago and it will be works, but now i install it and it doesnt working, because i cant execute any Insert statements. Why?

Thanks.

**Comment by mabodev** [comment]
Solution for those that still having problems after enabling identifierQuoting via propel.ext config or hard coding: Use <database ... identifierQuoting="true"> as mentioned on https://github.com/propelorm/Propel2/issues/781
