### ISSUE TITLE
DateTime as Primary Key

### ISSUE THREAD

**Issue by jlvarela** [propelorm/Propel2#829]
Hi,

There is an issue when you define a primary key with a Date (datetime) type in the schema and then build the model, in the auto-generated code (in the Entity-Map.php), in the addInstanceToPool function, the DateTime attribute is casted to a String by doing: (string) dateTimePK. This is causing a Fatal Error exception, because the right way to cast a DateTime is using the ->format('Y-m-d') function. I did the change my self and everything worked fine. So I think the auto-generated code  should consider this right way to cast a DateTime into a String.

PD: By the way, excellent work you've done here, congrats and thank you very much! I love Propel.

Regards,

**Comment by ScubaJimmE** [comment]
I've experienced the same issue today.

Table has compound primary key (see extract from schema.xml below)
```xml
 <table name="diverqualification" idMethod="native" phpName="DiverQualification">
    <column name="diverid" phpName="Diverid" type="INTEGER" primaryKey="true" required="true"/>
    <column name="qualificationid" phpName="QualificationId" type="INTEGER" primaryKey="true" required="true"/>
    <column name="datestarted" phpName="DateStarted" type="DATE" primaryKey="true" required="true"/>
```

Generated EntityMap.php gives:
```php
if (Propel::isInstancePoolingEnabled()) {
            if (null === $key) {
                $key = serialize(array((string) $obj->getDiverid(), (string) $obj->getQualificationId(), (string) $obj->getDateStarted()));
            } // if key === null
            self::$instances[$key] = $obj;
        }
```
**Note (string) $obj->getDateStarted()));**

Therefore, running a save() on this object results in the following exception:

Catchable fatal error: Object of class DateTime could not be converted to string in ...\generated-classes\Map\<Entity>TableMap.php

**Comment by draev** [comment]
This issue still present... any news about it ?

**Comment by ericmmartin** [comment]
I had the same issue and "fixed" it by modifying the <Entity>TableMap.php file for the entity in question. 

Changed:

    $key = serialize(array((string) $obj->getId(), (string) $obj->getCreatedAt()));

to:

    $key = serialize(array((string) $obj->getId(), date_format($obj->getCreatedAt(), 'Y-m-d H:i:s')));
