### ISSUE TITLE
setQueryKey() is not compatible with terminators that execute several queries - such as Paginate()

### ISSUE THREAD

**Issue by SacredSkull** [propelorm/Propel2#848]
#### UPDATE: Previously I thought it was propel's caching system in general that was causing this error, but I've found it's just paginate() (or potentially any terminator that uses more than one Query to run).

When using a caching system (I tested both APC & Memcache) the system does actually store successfully (on both the official APC & memcache methods) but it only stores the first SELECT COUNT(*) query. This behavior has occurred on both a Windows & Linux machine.

In other words, look at this behavior, with Memcache disabled (but setQueryCache still live in the code):

# Without Cache

`[2014-12-29 01:58:40] defaultLogger.INFO: SELECT COUNT(*) FROM (SELECT article.id, article.title, article.body, article.tags, article.positive_votes, article.negative_votes, article.theme_id, article.created_at, article.updated_at, article.slug FROM article) propelmatch4cnt [] []`

`[2014-12-29 01:58:40] defaultLogger.INFO: SELECT article.id, article.title, article.body, article.tags, article.positive_votes, article.negative_votes, article.theme_id, article.created_at, article.updated_at, article.slug FROM article ORDER BY article.id DESC [] []`

#### This chain of events is the same if the cache is enabled, except that the first COUNT SQL statement is stored. When Propel follows through to get a paginated list of rows it suddenly finds that a key has been created already, so it just uses the cache. So, in result, Propel executes a COUNT statement twice. 

# With Cache

`[2014-12-29 01:57:12] defaultLogger.INFO: SELECT COUNT(*) FROM (SELECT article.id, article.title, article.body, article.tags, article.positive_votes, article.negative_votes, article.theme_id, article.created_at, article.updated_at, article.slug FROM article) propelmatch4cnt`

`[2014-12-29 01:57:12] defaultLogger.INFO: SELECT COUNT(*) FROM (SELECT article.id, article.title, article.body, article.tags, article.positive_votes, article.negative_votes, article.theme_id, article.created_at, article.updated_at, article.slug FROM article) propelmatch4cnt [] []`

Maybe I am doing something incredibly wrong, but I don't think so, because I followed the documentation, even using the example on paper, and the same problem occurs.

Here is one example of the code that fails with this:
```
	$posts = ArticleQuery::create()
		->setQueryKey("all_posts")
		->orderById('DESC')
		->paginate($page, $perPage);
```

Whilst you might say that caching such a general query is unnecessary, it is a test, and a test that is failing. I have ensured that spaces in memcache key names are converted to underscores, etc, so it is definitely a propel issue.

Tested with both
```
	$posts = new ArticleQuery();
	$posts = $posts
		->setQueryKey("homepage")
		->paginate($page, $perPage);
```
And the `$posts = ArticleQuery::create()` way. Adding filler parameters like orderById() has no affect on the result.
Which should have done the same thing anyway.

My suggestion is to either:

- Add an optional parameter (defaulting to true) called "cacheable" that is checked before executing the cache behavior.
- When using termination methods that require additional queries, append "_paginate" to the initial count query key so that both are cached separately.

**Comment by nibsirahsieu** [comment]
@SacredSkull  Why did you close this ? does the referenced PR fix your issue?
