### ISSUE TITLE
Simple query returns wrong result

### ISSUE THREAD

**Issue by jengeb** [propelorm/Propel2#849]
Here is the link to a short example:
http://sandbox.propelorm.org/5b75efe

That's the query:
$cinemas = UserCinemaQuery::create()->find();
echo $cinemas->toJSON();

Result is:
{"UserCinemas":[{"UserId":1,"CinemaId":2},{"UserId":1,"CinemaId":2}]}

Expected Result would be:
{"UserCinemas":[{"UserId":1,"CinemaId":1},{"UserId":1,"CinemaId":2}]}

**Comment by fitefoe** [comment]
@dhm80 your work-around works very well for me. Thank you!

**Comment by staabm** [comment]
> I guess it has something todo with the instance pooling. Without PK it's not possible to detect a unique hashcode of a db row.

@marcj would it make sense to bypass the cache within the instance-pool when there is no PK?

**Comment by marcj** [comment]
@staabm well, I'd rather throw an exception for entities without PK.
