### ISSUE TITLE
Update / Edit / Change a foreign key in Propel 2.0

### ISSUE THREAD

**Issue by Leon3K** [propelorm/Propel2#857]
Hello,
I have to update a foreign key, here is an example:

$authorQ = new AuthorQuery();
$author = $authorQ->findOneById(53);

$bookQ = new BookQuery();
$book = $bookQ->findOneById(1328);
$book->setPrice(9.90); //this update works
$book->setAuthor($author); //this not, the old foreign key/id stays the same
$book->save();

This bug was already mentioned about 4 years ago right here: http://stackoverflow.com/questions/8278308/propel-update-foreign-key-reference
Are there any workarounds or bug-fixes for Propel 2.0 available?

Note: Propel does not throws any errors or exceptions.

**Comment by marcj** [comment]
This definitely works as we have covered it in our test suite thousand times. Please reproduce it in http://sandbox.propelorm.org.

**Comment by Leon3K** [comment]
Here is is: http://sandbox.propelorm.org/a617ca5
But when I try to start it the following message comes up: "Fatal error: Class 'Niederlassung' not found in /home/sandbox/script.php on line 8 "

**Comment by marcj** [comment]
Because your schema xml is wrong. Please take a look at examples too see what you need to enter.

**Comment by Leon3K** [comment]
Ok I missed the database selector.But now the Bug is reproduced. The Id stays 2 but it has to be 1.

**Comment by marcj** [comment]
There's no need to set `Niederlassung_id` as primaryKey, because you have already a autoIncrement primaryKey defined. The index `fk_Berater_Niederlassung_idx` is also not necessary as MySQL (and Propel) already makes sure that foreign keys are indexed. So if you remove that primaryKey at Niederlassung_id then you it will work.

**Comment by Leon3K** [comment]
I removed "primaryKey="true"" of line 5 and it works now. Million thanks.
Well I thought the usage of primary keys is a good practive due they are ordered by binary-trees. Or what is your opinion about this? Do you have any further infos why it is better to NOT declare foreightKeys as primaryKeys as well?

**Comment by marcj** [comment]
PrimaryKeys is equal to an UniqueIndex, and Uniques are special indices. All indices are at least binary-trees, that's the nature behind indices. Setting a foreignKey as primaryKey doesn't give you any gain in performance, since foreignKeys are already indexed in InnoDB engine.

**Comment by marcj** [comment]
> Do you have any further infos why it is better to NOT declare foreightKeys as primaryKeys as well? 

because it makes no sense.

**Comment by Leon3K** [comment]
OK thanks have a nice weekend bye
