### ISSUE TITLE
update() requires filtering by the desired column to be updated

### ISSUE THREAD

**Issue by guitarman0831** [propelorm/Propel2#866]
When calling the `update()` function, it requires you to filter by the column being updated.

i.e. if I run the query `SampleQuery::create()->filterById($id)->update(array("Information" => "New information"));`, it returns 1, indicating a row was updated. However, checking the database information, nothing was actually updated. The Information column still contains "Old information" (the previous value).

In order to make the above query work, it would have to be ran as `SampleQuery::create()->filterByInformation("Old information")->update(array("Information" => "New information"))`, which doesn't make sense.

**Comment by marcj** [comment]
Can you please provide us a sandbox fiddle where we can reproduce it? http://sandbox.propelorm.org

**Comment by guitarman0831** [comment]
http://sandbox.propelorm.org/7d617d6 Appears to be a local issue. Closed.
