### ISSUE TITLE
Row is not updated if modified value is part of a compound primary key

### ISSUE THREAD

**Issue by bosycom** [propelorm/Propel2#881]
<b>Precondition</b>: You have a table 'permission' with the columns 'module' , 'role' , 'fk_contact_id'. These three columns form a compound primary key.

<b>Problem</b>: Trying to update a model or collection having a new value for 'role' does not work. Data remains unchanged. No SQL exception.

<b>Reason</b>:  False bindings in \Propel\Runtime\ActiveQuery\Criteria.php.

<b>Example</b>:
This query is generated: UPDATE `permission` SET `role`=:p1, WHERE `permission`.`module`=:p2 AND `permission`.`role`=:p3 AND `permission`.`fk_contact_id`=:p4

with these bindings

p1:role=guest (<-- update value)
p2:module=someModule
p3:role=guest (<-- WRONG, it should be the old value, e.g. 'admin', not 'guest')
p4:32

Binding p3 uses the update value instead of the old/current db value causing the SQL query to not affect any row since the WHERE statement will not match any records.

<b>Workaround</b>: Remove 'role' as primary key field

**Comment by marcj** [comment]
Yes, this is a known limitation. Will be fixed in PR #795

**Comment by dereuromark** [comment]
Is someone able to make a PR here with suggested changes? maybe part of that PR can be extracted into propel2 directly.
