### ISSUE TITLE
I want use the ModelType in Silex。

### ISSUE THREAD

**Issue by dongww** [propelorm/Propel2#883]
Can you separate from the propel-bundle out of the ModelType?

thx.

**Comment by marcj** [comment]
I don't know what you mean. Never worked with Silex. @propelorm/propel2, anyone an idea?

**Comment by dongww** [comment]
I want use form with prople2 model in Silex, but i must require propleBundle to use the ModleType class.

**Comment by cristianoc72** [comment]
Uhm....interesting feature. I should include it in PropelServiceProvider.
May be we could split it in a separate repo to use it both with PropelBundle and PropelServiceProvider.
I'll get alook tonight.
@K-Phoen what do you think about?

**Comment by K-Phoen** [comment]
I guess it can be done but it would be interesting only if the whole [`Form`](https://github.com/propelorm/PropelBundle/tree/2.0/Form) directory is extracted to a new repo (not just the `ModelType`).

That being said, I tend to think that a project with only a few form types is a bit overkill (even if I see the need here).

**Comment by dongww** [comment]
Thank you!

**Comment by dereuromark** [comment]
Looks outdated.
