### ISSUE TITLE
Boolean in schema results in tinyint(1) in MySQL

### ISSUE THREAD

**Issue by jengeb** [propelorm/Propel2#885]
See SQL tab in http://sandbox.propelorm.org/5fe99ad

MySQL supports the boolean data type and the [documentation](http://propelorm.org/documentation/reference/schema.html#other-types) states that boolean is used if the database supports it.

**Comment by marcj** [comment]
http://dev.mysql.com/doc/refman/5.7/en/numeric-type-overview.html

>  BOOL, BOOLEAN
> These types are synonyms for TINYINT(1).

**Comment by jengeb** [comment]
Thanks and sorry, I wasn't aware of that.
