### ISSUE TITLE
Joins with multiple foreign keys to same table fail

### ISSUE THREAD

**Issue by jengeb** [propelorm/Propel2#892]
I have problems with two foreign keys referencing the same table `users`. In a table `movies` I store both the user who created an entry (`CreateUser`) and the user who updated this entry (`UpdateUser`), see the [sandbox](http://sandbox.propelorm.org/e5a686f).

I use `join()` to join the tables `movies` and `users`. Either the query to get `CreateUser` or `UpdateUser` is working. However, joining both fails. The executed SQL query seems to be

```
SELECT movies.ID, movies.TITLE,
  users.NAME AS CreateUserName,
  users.NAME AS UpdateUserName
  FROM `movies`
  INNER JOIN `users` ON (movies.CREATE_USER_ID=users.ID)
  INNER JOIN `users` ON (movies.UPDATE_USER_ID=users.ID)
```

Note that `users` appears twice. Probably it should read
```
SELECT movies.ID, movies.TITLE,
  CreateUser.NAME AS CreateUserName,
  UpdateUser.NAME AS UpdateUserName
  FROM `movies`
  INNER JOIN `users` AS CreateUser ON (movies.CREATE_USER_ID=CreateUser.ID)
  INNER JOIN `users` AS UpdateUser ON (movies.UPDATE_USER_ID=UpdateUser.ID)
```

Is there something wrong in my sandbox code or is there a bug in Propel2?

**Comment by andrenarchy** [comment]
I also noticed that the resulting array contains a key `User` (which is not requested by the code).

**Comment by jengeb** [comment]
Can someone recommend a workaround for this issue?

**Comment by nicklaros** [comment]
join with alias solve this, for example:
```
$movie = MovieQuery::create()
  ->leftJoinCreator('Creator')
  ->withColumn('Creator.Name', 'CreateUserName')
  ->leftJoinUpdater('Updater')
  ->withColumn('Updater.Name', 'UpdateUserName');
```
notice that in your schema file.. `Creator` and `Updater` above is the phpName of foreign key in movie table
```
    <table name="movie">
        <column name="id"                       type="BIGINT" size="20" primaryKey="true" autoIncrement="true" />
        <column name="name"                    type="LONGVARCHAR" />
        <column name="creator_id"            type="BIGINT" size="20" />
        <column name="updater_id"           type="BIGINT" size="20" />

        <foreign-key foreignTable="user" phpName="Creator" refPhpName="CreatedMovie">
            <reference local="creator_id" foreign="id" />
        </foreign-key>
        <foreign-key foreignTable="user" phpName="Updater" refPhpName="UpdatedMovie">
            <reference local="updater_id" foreign="id" />
        </foreign-key>
    </table>
```

**Comment by jengeb** [comment]
@nicklaros Thank you very much for the workaround!

**Comment by jengeb** [comment]
Nevertheless it may make sense to support the query used above. What do you think?

**Comment by nicklaros** [comment]
You're wellcome..
I personally think propel is good at handling join as it is.. alias join gives us flexibility to name relationship the way we want.

**Comment by sjbartley** [comment]
However, there remains the problem (mentioned by andrenarchy) that toArray only allows for one key 'User'. 

In Propel\Generator\Builder\Om at the method addToArrayKeyLookUp(), the array key 'User' is being generated from the table name only, and cannot be customised based on the phpName attribute. 

This is quite a problem and bug in the array generation algorithm, as the array key 'User' is overwritten by subsequent foreign key object toArray calls (i.e. the Updater user data may over-write the Creator user data, or vice-versa).

I would like to know if I am missing something, and there is a way to get toArray working.

**Comment by pawel-oronowicz** [comment]
I am having the same problem as @sjbartley - I have three foreign keys pointing to the same table:

    <foreign-key foreignTable="sites" phpName="Site" refPhpName="Timesheet">
      <reference local="siteID" foreign="siteID"/>
    </foreign-key>
    <foreign-key foreignTable="sites" phpName="FromSite">
      <reference local="from_siteID" foreign="siteID"/>
    </foreign-key>
    <foreign-key foreignTable="sites" phpName="ToSite">
      <reference local="to_siteID" foreign="siteID"/>
    </foreign-key>

 and despite different PhpNames, the Base Class generates `default: $key` incorrectly:

    if (null !== $this->aToSite) {
                switch ($keyType) {
                    case TableMap::TYPE_CAMELNAME:
                        $key = 'site';
                        break;
                    case TableMap::TYPE_FIELDNAME:
                        $key = 'sites';
                        break;
                    default:
                        $key = 'Site';
                }
                $result[$key] = $this->aToSite->toArray($keyType, $includeLazyLoadColumns,  $alreadyDumpedObjects, true);
            }

`default: $key` should be `ToSite`, not `Site`. Similarly for `FromSite`. As a result, the `Site` table is only joined for `Site`, but not for `FromSite` and `ToSite`. The tables are joined in the following way:

    $timesheets = TimesheetQuery::create()
      ->select(Timesheet::getTransferFieldsWithRelations())
      ...
      ->joinWith("Timesheet.FromSite FromSite", Criteria::LEFT_JOIN)
      ->joinWith("Timesheet.ToSite ToSite", Criteria::LEFT_JOIN)
      ->joinWith("Timesheet.Site Site", Criteria::LEFT_JOIN)
      ...

Is there a way around this?

**Comment by pawel-oronowicz** [comment]
Managed to fix the above issue. In `Propel/Generator/Builder/Om/ObjectBuilder.php`, change the following:

    if (\$includeForeignObjects) {";
            foreach ($fks as $fk) {
                $script .= "
            if (null !== \$this->" . $this->getFKVarName($fk) . ") {
                {$this->addToArrayKeyLookUp($fk->getForeignTable(), false)}
                \$result[\$key] = \$this->" . $this->getFKVarName($fk) . "->toArray(\$keyType, \$includeLazyLoadColumns,  \$alreadyDumpedObjects, true);
            }";
            }
            foreach ($referrers as $fk) {
                if ($fk->isLocalPrimaryKey()) {
                    $script .= "
            if (null !== \$this->" . $this->getPKRefFKVarName($fk) . ") {
                {$this->addToArrayKeyLookUp($fk->getTable(), false)}
                \$result[\$key] = \$this->" . $this->getPKRefFKVarName($fk) . "->toArray(\$keyType, \$includeLazyLoadColumns, \$alreadyDumpedObjects, true);
            }";
                } else {
                    $script .= "
            if (null !== \$this->" . $this->getRefFKCollVarName($fk) . ") {
                {$this->addToArrayKeyLookUp($fk->getTable(), true)}
                \$result[\$key] = \$this->" . $this->getRefFKCollVarName($fk) . "->toArray(null, false, \$keyType, \$includeLazyLoadColumns, \$alreadyDumpedObjects);
            }";
                }
            }
            $script .= "
        }";

to

    if (\$includeForeignObjects) {";
            foreach ($fks as $fk) {
                $script .= "
            if (null !== \$this->" . $this->getFKVarName($fk) . ") {
                {$this->addToArrayKeyLookUp($fk->getPhpName(), $fk->getForeignTable(), false)}
                \$result[\$key] = \$this->" . $this->getFKVarName($fk) . "->toArray(\$keyType, \$includeLazyLoadColumns,  \$alreadyDumpedObjects, true);
            }";
            }
            foreach ($referrers as $fk) {
                if ($fk->isLocalPrimaryKey()) {
                    $script .= "
            if (null !== \$this->" . $this->getPKRefFKVarName($fk) . ") {
                {$this->addToArrayKeyLookUp($fk->getRefPhpName(), $fk->getTable(), false)}
                \$result[\$key] = \$this->" . $this->getPKRefFKVarName($fk) . "->toArray(\$keyType, \$includeLazyLoadColumns, \$alreadyDumpedObjects, true);
            }";
                } else {
                    $script .= "
            if (null !== \$this->" . $this->getRefFKCollVarName($fk) . ") {
                {$this->addToArrayKeyLookUp($fk->getRefPhpName(), $fk->getTable(), true)}
                \$result[\$key] = \$this->" . $this->getRefFKCollVarName($fk) . "->toArray(null, false, \$keyType, \$includeLazyLoadColumns, \$alreadyDumpedObjects);
            }";
                }
            }
            $script .= "
        }";


As well as this:

    protected function addToArrayKeyLookUp(Table $table, $plural)
    {
        $phpName = $table->getPhpName();
        $camelCaseName = $table->getCamelCaseName();
        $fieldName = $table->getName();

to:

    protected function addToArrayKeyLookUp($phpName, Table $table, $plural)
    {
        if($phpName == "") {
            $phpName = $table->getPhpName();  
        }
        
        $camelCaseName = $table->getCamelCaseName();
        $fieldName = $table->getName();

Now I can reference multiple FKs with PHPNames to the same table without any issues.

**Comment by sjbartley** [comment]
@pawel-oronowicz that's great. Will you try to merge your work in via a pull-request?

**Comment by pawel-oronowicz** [comment]
@sjbartley created PR #1009
