### ISSUE TITLE
Symfony Join Query on propel 2

### ISSUE THREAD

**Issue by loicdev** [propelorm/Propel2#893]
Hi , 
I try it : http://sandbox.propelorm.org/941f06b
 on Symfony 2 Framework but join between both tables don't work.

When i try  : 
 TableA::create()
                  ->join('TableB')
                  ->useQuery('TableB')
                    ->endUse()
                  ->find();

I obtain this error :  "Unknown relation TableB on TableA table"

 But i have the relation in tableA 
column name="node_id" type="integer" 
foreign-key foreignTable="node"
      reference local="node_id" foreign="id" 
 foreign-key

Have you got  an issue about it ? thx

**Comment by marcj** [comment]
The relation there is called "Node", not "TableB".
