### ISSUE TITLE
Decimal with a zero scale 

### ISSUE THREAD

**Issue by kairichard** [propelorm/Propel2#894]
When working with a legacy database that has field like the following

```mysql
  `field_name` decimal(11,0) DEFAULT NULL
```

propel generates a wrong schema.xml omitting the scale of the field

This can be reproduced using `make test` from https://github.com/kairichard/propel-issue-decimal-zero-scale where a second migration will be created because the schema does not match with the generated migration.

**Comment by robin850** [comment]
I guess this can be closed as #897 has been merged.
