### ISSUE TITLE
Wrong type definition in generated migration

### ISSUE THREAD

**Issue by kairichard** [propelorm/Propel2#895]
When working with a legacy database that has field like the following

```mysql
  `field_name` decimal(10,3) DEFAULT '1.000' NOT NULL
```

propel generates a wrong migration omitting the `10,3` in the type definition

This can be reproduced using `make test` from https://github.com/kairichard/propel-issue-decimal-default where a second migration will be created because the schema does not match with the generated migration.

**Comment by robin850** [comment]
It looks like this can be closed as well since #898 has been merged.
