### ISSUE TITLE
moveSubtreeTo failed when passing ConnectionInterface instance as 3rd parameter in nested set case

### ISSUE THREAD

**Issue by nicklaros** [propelorm/Propel2#899]
As the title said, it throws an error with message:

Argument 3 passed to Base\blablabla::moveSubtreeTo() must be an instance of ORM\Base\PropelPDO, instance of Propel\Runtime\Connection\DebugPDO given

well I need to wrap it in a transaction by passing my ConnectionInterface instance, but it just accept PropelPDO instance.
Is this intentional?

**Comment by dereuromark** [comment]
Is this still relevant or can it be closed?

**Comment by nicklaros** [comment]
Mmm not sure as I dont use it anymore, but I think yes it can be closed.
