### ISSUE TITLE
Propel inserts twice

### ISSUE THREAD

**Issue by PeterSchumacher** [propelorm/Propel2#901]
When using sqlite, rows get inserted twice.

Here's my setup,

composer.json
```text
"propel/propel": "~2.0@dev"
```

schema.xml
```xml
<table name="usertype" phpName="Usertype">
  <column name="id" phpName="Id" type="integer" required="true" primaryKey="true" autoIncrement="true"/>
<column name="name" phpName="Name" type="VARCHAR" required="true"/>
</table>  
```

test.php
```php
$usertype = new Usertype;  
$usertype->setName('X_' . time());  
$usertype->save();
```

sqlite select after running test.php
```sql
sqlite> select * from usertype;  
1|X_1426856872  
2|X_1426856872  
```

Update : When running in sandbox, it correctly inserts one row.
See it here : http://sandbox.propelorm.org/9d8003c

Thanks!

**Comment by marcj** [comment]
Hard to say what the error here really is, since we can not reproduce it easily. Does it happen only with SQLite?

**Comment by PeterSchumacher** [comment]
Figured it out and Propel has nothing to do with it. Sorry for wasting your time :(

I recently switched from using mod_rewrite to 'fallbackresource' under Apache.
When using 'fallbackresource', all calls to non-existing files are routed to a specific file usually index.php.
A non-existing favicon triggered a second call to index.php which resulted in a duplicated row.
