### ISSUE TITLE
Unwanted save cascade

### ISSUE THREAD

**Issue by david-fanin** [propelorm/Propel2#903]
Hello,

Here is my code and its result:

```
$object1 = Object1Query::create()->findPk($pkObject1);

$object2 = new Object2();
$object2->setObject1($object1);

$object1->setProperty('value');
$object1->save();// Triggers the save of "$object2" but I do not want this
```

To begin with, is that it would make more sense if there was no save cascade in this direction of the relation. No?

Then, how can we prevent this save cascade?
I tried the following 2 solutions without results:
- The first:

```
<table name="object2_table" phpName="Object2">
     // ...
    <column name="id_object1" type="integer"/>

    <foreign-key foreignTable="object1_table" phpName="Object1" onUpdate="none">
        <reference local="id_object1" foreign="id"/>
    </foreign-key>
</table>
```
- The second:
  `$object2->setObject1(null);` before `$object1->save();`

Can you help me?

I have "propel/propel-bundle 1.4.4" in a Symfony2.6 project.

**Comment by marcj** [comment]
Instead of passing the object itself to its foreign model setter, you should pass only its ID.

```php
$object2->setObject1Id($object1->getId());
```
