### ISSUE TITLE
Unexpected behavior withColumn in combination with paginate..?

### ISSUE THREAD

**Issue by BondITSolutions** [propelorm/Propel2#905]
I have two tables named `tickets` and `responses`, the latter containing the responses to a certain ticket (`tickets` has many `responses`).

Now when I execute the following LOC it gives me back the right amount of tickets (5):

    TicketsQuery::create()->paginate(1, 5)->count();

Now when I add a column which counts the responses as follows:

    TicketsQuery::create()
        ->leftJoin('Tickets.Responses')
        ->withColumn('COUNT(Responses.id)', 'NbResponses')
        ->paginate(1, 5)->count();

It only returns a collection with 1 instead of 5 tickets, why is this? 

Edit: I figure it has something to do with only 1 of the tickets having responses. But shouldn't it still return 5 tickets, but with the latter 4 having NbResponses set as 0?

**Comment by marcj** [comment]
Because you aggregate your results using `COUNT()`. You need to add a `GROUP BY` statement to keep your rows separated. 

```php
TicketsQuery::create()
    ->leftJoin('Tickets.Responses')
    ->withColumn('COUNT(Responses.id)', 'NbResponses')
    ->groupById()
    ->paginate(1, 5)->count();
```

**Comment by BondITSolutions** [comment]
Ah, of course. Thanks!
