### ISSUE TITLE
Properties of child classes lost after serialize->unserialize

### ISSUE THREAD

**Issue by david0** [propelorm/Propel2#915]
An object that is serialized using sleep looses instance properties that are declared in child classes:

```php
class Book extends Base\Book
{
  private $color;
  public function setColor($color) { $this->color = $color; }
  public function getColor() { return $this->color; }
}

$book = new Book();
$book->setColor('blue');

echo 'Before: '.$book->getColor()."\n";
$unserializedBook = unserialize(serialize($book));
echo 'After: '.$unserializedBook->getColor()."\n";
```
Output
```
Before: blue
After:
```

I would expect that the property would be restored by default, similar to PHP's default behavior.
[baseObjectMethods.php:209](https://github.com/propelorm/Propel2/blob/fb7aa33479797a5e2fe794eeb3762691cb6416b2/src/Propel/Generator/Builder/Om/templates/baseObjectMethods.php#L209) is causing this problems. `get_object_vars` is scope aware and does not return the attributes of child classes. [ReflectionClass::getProperties](http://php.net/manual/en/reflectionclass.getproperties.php) should work as expected here.

**Comment by marcj** [comment]
Thanks for the report. Do you mind sending a fix in a pull-request?
