### ISSUE TITLE
slaves configuration

### ISSUE THREAD

**Issue by jeremydenoun** [propelorm/Propel2#920]
In Propel/Common/Config/PropelConfiguration.php:137 you authorize only dsn nodes but we must provide login/pass to PdoAdapter for use it..

I propose to add : 
 	       	       	       	       	       	->scalarNode('user')->end()
	       	       	       	       	       	->scalarNode('password')->treatNullLike('')->end()
l.140 to fix it

**Comment by jeremydenoun** [comment]
my patch permit to use same options than write connection in read (slaves)  connections ...
I do it for use Propel\Runtime\Connection\ProfilerConnectionWrapper for slaves but for be complete we should add a parameter in log for determine if request come from read or write connection. I'm work on it

**Comment by marcj** [comment]
Guess this is fixed in https://github.com/propelorm/Propel2/pull/1146. Please give me a ping when not.
