### ISSUE TITLE
Unrecognized option "disableIdentifierQuoting" under "propel.generator.objectModel" 

### ISSUE THREAD

**Issue by greddyatpt** [propelorm/Propel2#925]
Getting the following error in Propel 2 when propel.yaml has disableIdentifierQuoting set under objectModel.

Unrecognized option "disableIdentifierQuoting" under "propel.generator.objectModel" 

Some of the column names in our mysql DB are reserved keywords so they need to be quoted.  With this option unavailable, the generated SQL statements have no quotes.

Is there a workaround for this?

**Comment by marcj** [comment]
I guess the documentation is outdated. "identifierQuoting" is now an option at `<database>` and `<table>`

**Comment by marcj** [comment]
Added it.

**Comment by greddyatpt** [comment]
Thank you.  You've added the "propel.generator.objectModel.identifierQuoting=true|false" in propel.ext, right?  This would allow us to control quoting in the "propel database:reverse" command.

**Comment by rambabusaravanan** [comment]
Please update the latest documentation and the references on the site ..
Newbies are struggling a lot by finding proper syntax ..

http://propelorm.org/documentation/
http://propelorm.org/documentation/reference/
http://propelorm.org/Propel/reference/
http://propelorm.org/Propel/documentation/
