### ISSUE TITLE
Problem with sql:build

### ISSUE THREAD

**Issue by iAlbertoDaniel** [propelorm/Propel2#929]
Installation went well, but the problem comes when I execute
vendor\bin\propel sql:build

Fatal error: Call to a member function getName() on a non-object in C:\xampp\htd
ocs\MyWeb\vendor\propel\propel\src\Propel\Generator\Platform\DefaultPlatfor
m.php on line 441

More details...

c:\xampp\htdocs\MyWeb>composer install
Loading composer repositories with package information
Installing dependencies (including require-dev)
  - Installing symfony/filesystem (v2.6.6)
    Loading from cache

  - Installing symfony/config (v2.6.6)
    Loading from cache

  - Installing symfony/translation (v2.6.6)
    Loading from cache

  - Installing symfony/validator (v2.6.6)
    Loading from cache

  - Installing symfony/finder (v2.6.6)
    Loading from cache

  - Installing symfony/console (v2.6.6)
    Loading from cache

  - Installing symfony/yaml (v2.6.6)
    Loading from cache

  - Installing psr/log (1.0.0)
    Loading from cache

  - Installing propel/propel (dev-master 8b32cd2)
    Cloning 8b32cd2e1965def9b535276ad7dbe5e5298a500f

  - Installing twig/twig (v1.18.1)
    Loading from cache

symfony/validator suggests installing doctrine/annotations (For using the annota
tion mapping. You will also need doctrine/cache.)
symfony/validator suggests installing doctrine/cache (For using the default cach
ed annotation reader and metadata cache.)
symfony/validator suggests installing symfony/http-foundation ()
symfony/validator suggests installing symfony/intl ()
symfony/validator suggests installing egulias/email-validator (Strict (RFC compl
iant) email validation)
symfony/validator suggests installing symfony/property-access (For using the 2.4
 Validator API)
symfony/validator suggests installing symfony/expression-language (For using the
 2.4 Expression validator)
symfony/console suggests installing symfony/event-dispatcher ()
symfony/console suggests installing symfony/process ()
propel/propel suggests installing monolog/monolog (The recommended logging libra
ry to use with Propel.)
Writing lock file
Generating autoload files

c:\xampp\htdocs\MyWeb>vendor\bin\propel sql:build

Fatal error: Call to a member function getName() on a non-object in C:\xampp\htd
ocs\MyWeb\vendor\propel\propel\src\Propel\Generator\Platform\DefaultPlatfor
m.php on line 441

**Comment by marcj** [comment]
can you please give us the full stack trace using `-vvv` as command option.

**Comment by iAlbertoDaniel** [comment]
c:\xampp\htdocs\MyWeb>vendor\bin\propel sql:build -vvv
Processing: schema.xml
  6 tables processed successfully
6 tables found in 1 schema files.

Fatal error: Call to a member function getName() on a non-object in C:\xampp\htd
ocs\MyWeb\vendor\propel\propel\src\Propel\Generator\Platform\DefaultPlatfor
m.php on line 441

c:\xampp\htdocs\MyWeb>

Is that correct?

**Comment by cristianoc72** [comment]
It's about a column: maybe a typo in a <column> tag?

c:\xampp\htdocs\MyWeb>vendor\bin\propel sql:build -vvv
Processing: schema.xml
6 tables processed successfully
6 tables found in 1 schema files.

Fatal error: Call to a member function getName() on a non-object in
C:\xampp\htd
ocs\MyWeb\vendor\propel\propel\src\Propel\Generator\Platform\DefaultPlatfor
m.php on line 441

c:\xampp\htdocs\MyWeb>

Is that correct?

—
Reply to this email directly or view it on GitHub
<https://github.com/propelorm/Propel2/issues/929#issuecomment-98214735>.

**Comment by iAlbertoDaniel** [comment]
Thank you @cristianoc72 you were right. I change some couple of things in my schema.xml file and that solved the issue.
