### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by tleb** [propelorm/Propel2#930]
Hello,

As it seem that the project can be used in production, could a release be created ?

Another reason: as Composer clones the project, it clones `.git/`, which is 26.1Mb big. It might not seem a lot, but it is when you have a small connection like mine (~100ko/s in real usage).

**Comment by marcj** [comment]
No, not yet. https://github.com/propelorm/Propel2/wiki. Afaik there's no way to repack git and reupload it to Github, due to Githubs limitations.

**Comment by robin850** [comment]
@tleb : You can use the `--prefer-dist` option to avoid downloading the `.git` directory as far as I know.
