### ISSUE TITLE
Using reserved words as column names

### ISSUE THREAD

**Issue by mrjulio** [propelorm/Propel2#936]
```php
protected function findPkSimple($key, ConnectionInterface $con)
 {
        $sql = 'SELECT id, name, email, group, phone, token, login_at, created_at, status FROM user WHERE id = :p0';
        // ....
}
```

The code above was generated in class Base\UserQuery. As you can see I used `group` word for column name which is a reserved word. I obviously receive a big error when running this. 
I believe that this should still work with Propel.

Maybe there should be a way to auto-detect the string separator from the db config.
I know that with mysql this can be changed via config (`ANSI_QUOTES` if i'm not mistaken).

Any ideas ?
Thank you.

**Comment by SourceCode** [comment]
The problem I see with that is that there are different reserved words in different database engines and at different versions.  Right now I don't believe you tell propel what version of what system you are using and it would probably require those specifics to be able to do this.  I'm just a user though and I thought this same thing then reached the conclusion above as to why it may not make sense to do that or prevent it.

**Comment by SCIF** [comment]
It's dbal related issue, not orm. I suppose that currently Propel can't (and will not in close future) provide dbal features.

**Comment by marcj** [comment]
You need to activate `identifierQuoting` at `database` or `table` element. http://propelorm.org/documentation/reference/schema.html#database-element

**Comment by mrjulio** [comment]
Awesome! Thank you!
