### ISSUE TITLE
Oracle: Limit IN-Lists to 1000 elements

### ISSUE THREAD

**Issue by david0** [propelorm/Propel2#939]
```php
$ids = range(1,2000);
$bookQuery = BookQuery::create()->filterById($ids);
$bookQuery->find(); 
```
will generate the following SQL, which is not valid for Oracle:
```sql
SELECT  FROM book WHERE book.id IN (:p1,:p2, ... ,:p2000)
```
IN-lists are limited to 1000 elements by Oracle. Statements with longer IN-Lists will always fail with "ORA-01795 maximum number of expressions in a list is 1000".

Propel should work around this limitation, e.g. by splitting up the in lists in blocks of 1000:
```sql
SELECT  FROM book WHERE (book.id IN (:p1,:p2, ... ,:p1000) OR book.id IN (:p1001, :p1002, ..., :p2000))
```

**Comment by staabm** [comment]
Not sure this is worth a workaround. Whats your use-case for selecting that much rows with one query?

**Comment by david0** [comment]
We used this in lists workaround before and are migrating to propel.

There are different use cases, but one the deletion of some objects.
There is some business logic involved in identify the elements to be deleted. For sure something like a subselect might also be possible, but I would like to avoid that because of testability reasons.

**Comment by staabm** [comment]
You could also `array_chunk` and delete in 1000 row batches

**Comment by david0** [comment]
Yes, for delete that would be possible and even better would be to use OCI-Collections for that (but thats not possible for Propel IMO, because you need a custom named type for that).
Since object deletion might be triggered by `save()` its not trivial to split the query up using `array_chunk`: I guess the termination methods (find/delete/update) must be overwritten and the query must be clone with fewer elements. That sounds like a hard thing to do. 

I really think the easiest solution is to fall back to multiple IN-conditions in that case. This would work for all use cases (delete/find/update/aggregate data using group by etc) and I don't see any side effects.
Everything else will just mean don't use `filterByXXX` with arrays with oracle, because it might fail with growing input data.
One would need to carefully investigate if the array passed to `filterByXXX` can get larger than 1000 elements (which is theoretically always the case i guess).

**Comment by marcj** [comment]
There are always limitations, even with max allowed placeholders in prepared statements. So, not using `filterByXXX` in all cases just to bypass one of those limitations is not a good advice. Fixing that by Propel is rather hard since those `Criteria` objects don't have a direct way of getting the `Adapter` being used for the current connection. That means we need to make all `Criteria` classes aware of its current environment. I'm not sure if this is the right way to go. There may be other ways to fix that, but I believe using the generator to generate different code is even more complex.

To keep this simple, you could just overwrite those `filterBy` methods you know that can get more than 1000 items.

```php
public function filterById($value) {
    if (is_array($value) && count($value) > 1000)(
        foreach (array_chunk($value, 1000) as $ids) {
            $this->filterById($ids);
        }
        return $this;
    } else {
        return $this->filterById($value);
    }
}
```

**Comment by david0** [comment]
As an workaround I implemented it like that (OR is missing). I would prefer an solution that covers all cases, but I understand that fixing this edge case is Propel not that trivial (and my use case is part of the problem), so I guess I have to live with that. 
Thanks anyway!

**Comment by marcj** [comment]
Alright. We reopen this issue when the need increases.
