### ISSUE TITLE
Initial autoincrements

### ISSUE THREAD

**Issue by solidevolution** [propelorm/Propel2#940]
Hello,

is there a possibility to set initial autoincrement-values in the xml file or in the models? At the moment we have a fixes.sql script as workaround at our vagrant development machines.

**Comment by SourceCode** [comment]
I was wondering the same not too long ago.  I ended up doing the same type of work around but it would have been nice to declare the starting point for auto-increment in the table schema itself.

**Comment by marcj** [comment]
I'd use migration files or set in the fixtures a primary key explicitly. There's no way of setting an initial value in the schema.xml and I don't think this would make sense as the schema is for mapping not initializing the database.
