### ISSUE TITLE
Additional foreign keys on cross-reference table produce duplicate query methods

### ISSUE THREAD

**Issue by eelkevdbos** [propelorm/Propel2#941]
TestCase: http://sandbox.propelorm.org/1fb3e57

Attaching additional foreign keys to a cross-reference table produces duplicate methods throwing: `Fatal error: Cannot redeclare method filterByXXXXX`

**Comment by eelkevdbos** [comment]
Additional foreign keys are treated like primary entities of the cross-reference with the 'helper' filters that come with it. This might be unexpected behavior. Could we add the cross-reference specific filter methods only on the primary keys of the cross reference?

So in my TestCase:

let the builder add methods on user to filter on ProductAttributeByCreator and ProductAttributeByUpdater

let the builder skip methods on user to filter on Product via ProductAttribute cross-reference

**Comment by dereuromark** [comment]
Is someone able to make a PR here with suggested changes?

**Comment by dimaxz** [comment]
still a real problem ((

**Comment by TechWilk** [comment]
Also creates the following error. Adding it here to bring those searching by it to the existing issue.
`Duplicate symbol declaration 'doAdd___'.intelephense(1004)`

**Comment by mringler** [comment]
Check #1963, which should fix the issue.
Looks like the error occurs when a cross-ref table is named after two of the tables it connects, i.e. a cross-ref table `UserGroup` connecting the tables `User` and `Group`. As a workaround, you could just rename the cross-ref table if that is an option.
