### ISSUE TITLE
Changed default key type isn't respected in collections

### ISSUE THREAD

**Issue by mgkimsal** [propelorm/Propel2#944]
The toArray() method defaults the key type to phoneme

$keyType = TableMap::TYPE_PHPNAME

If the default key type in the generator is set to something that's not phpName (camelName, for example), each call to toArray() needs to have an explicit parameter set.  As it's the third parameter, it's particularly bothersome, but even outside that nitpick, the default type should be respected for the object in question should be used.  It's generated, but not usable via collections method.

I can't seem to find a workaround on this either, as there's no generated base collection class that can be modified - everything's touching the core propel code - again, at least from what I'm seeing.  If this is addressed in the docs, and I'm just missing it, please point me to the right docs so I can go read up on this.

**Comment by marcj** [comment]
You can use a custom collection class and overwrite that `toArray` method. http://propelorm.org/documentation/reference/model-criteria.html#using-an-alternative-collection-class
