### ISSUE TITLE
What's the current version?

### ISSUE THREAD

**Issue by jjok** [propelorm/Propel2#945]
All the documentation points to this being the current version of Propel, but there doesn't seem to have been a stable release yet.

**Comment by marcj** [comment]
Current stable is v1.7 https://github.com/propelorm/Propel/releases

**Comment by jjok** [comment]
That's not very clear on this page: http://propelorm.org/download.html

**Comment by robin850** [comment]
@jjok : Yep you're right ; [a link](https://github.com/propelorm/propelorm.github.com/commit/3d4a68628d30d809dd7e728c228f73777ec55c87) has been added to point to the stable 1.x series site. Thanks for spotting this!
