### ISSUE TITLE
Self referencing *JoinRelatedBy* producing invalid syntax on MariaDB

### ISSUE THREAD

**Issue by lerp** [propelorm/Propel2#950]
I have a self-referencing table which I am trying to join.

    <table name="category">
        <column name="id" type="integer" primaryKey="true" autoIncrement="true"/>
        <column name="name" type="varchar" size="250" required="true" primaryString="true"/>
        <column name="parent" type="integer"/>

        <foreign-key foreignTable="category" onDelete="CASCADE" onUpdate="CASCADE">
            <reference local="parent" foreign="id"/>
        </foreign-key>
    </table>

When I try to join based on the foreign key like so:

    CategoryQuery::create()
        ->filterByParent(null)
        ->leftJoinCategoryRelatedByParent()
        ->find();

I get a syntax error due to the two table references needing to be distinct. i.e. the left table needs a different name/alias to the right table.

For example, I can manually achieve what I want with the below statement:

    SELECT root.id, root.name, child.id, child.name
    FROM category root
    JOIN category child 
    ON child.parent = root.id 
    WHERE root.parent IS NULL;

Sorry if this is an erroneous report, I am new to Propel.

**Comment by SCIF** [comment]
@lerp , you can try to set relation alias, as workaround:
```
CategoryQuery::create()
    ->filterByParent(null)
    ->leftJoinCategoryRelatedByParent('child')
    ->find();
```
It works for me in [sandbox](http://sandbox.propelorm.org/63ecdf9)

Seems like bug.

**Comment by SCIF** [comment]
@lerp , also, use `phpName` and `refPhpName` attributes of foreign key for beauty relations names.

**Comment by lerp** [comment]
@SCIF Hmm, this work around isn't working for me. I'm more than likely doing something wrong.

    $categories = CategoryQuery::create()
        ->filterByParent(null)
        ->leftJoinCategoryRelatedByParent('child')
        ->find();

creates the query:

    SELECT `category`.`id`, `category`.`name`, `category`.`parent`
    FROM `category`
    LEFT JOIN `category` `child`
    ON (`category`.`parent`=`child`.`id`)
    WHERE `category`.`parent` IS NULL 


Which:
- isn't fetching any of the foreign information
- has the on clause the wrong way around: it should be `category.id = child.parent`

Resulting in the below:

    +------+----------+--------+
    | id   | name     | parent |
    +------+----------+--------+
    | 4582 | Security |   NULL |
    +------+----------+--------+

Instead of something like:

    +------+----------+--------+------+--------------------------------------------------+--------+
    | id   | name     | parent | id   | name                                             | parent |
    +------+----------+--------+------+--------------------------------------------------+--------+
    | 4582 | Security |   NULL | 4583 | Lockout / Tagout Products                        |   4582 |
    | 4582 | Security |   NULL | 4590 | Padlocks & Hasp and Staples                      |   4582 |
    | 4582 | Security |   NULL | 4592 | Security Chains & Bike Locks                     |   4582 |
    | 4582 | Security |   NULL | 4600 | Safes & Key Safes                                |   4582 |
    | 4582 | Security |   NULL | 4605 | Door Security & Furniture                        |   4582 |
    | 4582 | Security |   NULL | 4686 | Security; Cameras, Lighting & Door Entry         |   4582 |
    +------+----------+--------+------+--------------------------------------------------+--------+

**Comment by nicklaros** [comment]
as @SCIF said, try to use phpName and refPhpName in your schema, for example:

```javascript
<table name="category">
    <column name="id" type="integer" primaryKey="true" autoIncrement="true"/>
    <column name="name" type="varchar" size="250" required="true" primaryString="true"/>
    <column name="parent" type="integer"/>

    <foreign-key foreignTable="category" phpName="ParentCategory" refPhpName="ChildCategory" onDelete="CASCADE" onUpdate="CASCADE">
        <reference local="parent" foreign="id"/>
    </foreign-key>
</table>
```

then, you can query like this

```javascript
CategoryQuery::create()
    ->filterByParent(null)
    ->leftJoinParentCategory('ParentCategory')
    ->find();
```

**Comment by lerp** [comment]
@nicklaros Aha, that works, thank you... I tried to read the docs on `refPhpName` but it was a bit muddling trying to think about a self referencing reference name. Lots of referencing...
