### ISSUE TITLE
ObjectFormatter ignores the fields specified by the "select" method on a query if the instance is already in the instance pool

### ISSUE THREAD

**Issue by jadkik** [propelorm/Propel2#952]
Say you use the ObjectFormatter everywhere. You run these two queries:

```
$query1 = BookQuery::create()->findPk(12);
var_dump($query1);

$query2 = BookQuery::create()->select(['Book.Name', 'Book.Summary'])->findPk(12);
var_dump($query2);
```

When running $query2 alone, you are supposed to get an `array('Book.Name' => ..., 'Book.Summary' => ...)`. However if a Book with id 12 is already in the instance pool of the formatter (i.e. you ran $query1 beforehand), you'll get an object back instead of the array.

This is not reproducible with other formatters AFAIK.

**Comment by marcj** [comment]
Confirmed in http://sandbox.propelorm.org/a04402c. You can work around this issue by calling `Map\BookTableMap::clearInstancePool();`.

Guess in https://github.com/propelorm/Propel2/blob/master/src/Propel/Runtime/Formatter/ArrayFormatter.php#L129 the cache key should also based on the selected columns.

**Comment by jadkik** [comment]
For now, I am calling `Propel\Runtime\Propel::disableInstancePooling()` to fix this globally, instead of calling `TableMap::clearInstancePool()` every time I need it.

I am assuming this makes the `ObjectFormatter` behave like the `OnDemandFormatter`, but still supports `getPrimaryKeys()` (which I am using throughout my code).

I believe the cache key should not depend on the selected columns. Instead it should not be cached if there are custom selected columns. However I'm not very familiar with the source code of Propel, so I'm not sure about that.

**Comment by marcj** [comment]
You're right. Building the cache index key not only on its primary key, but also on a hash of its selected columns and the formatter class should fix this issue.

**Comment by gharlan** [comment]
It is also an issue when using additional filter methods: http://sandbox.propelorm.org/79b3ed3
