### ISSUE TITLE
Sortable behavior not working with ENUM scope

### ISSUE THREAD

**Issue by pimpreneil** [propelorm/Propel2#954]
Here is a problem that I encountered using Propel1, I just reproduced it on Propel2, so here it is:

When adding a sortable behavior scopped to a column that has a ENUM type, the rank is wrong on creation (and on all the futher rank manipulations done on the object).

I am kind of new to this project so I don't know if I will manage to add the tests and modify the generator to produce a PR... So here is the workaround I am currently using:

I override the `getScopeValue` method in the object class. In the base class, the method looks like this:

```php
public function getScopeValue($returnNulls = true)
{
    return $this->get{MyEnumColumn}();
}
```

So I simply override the method to make it return the actual SQL value corresponding to my enum value like so:

```php
public function getScopeValue($returnNulls = true)
{
    return array_search($this->get{MyEnumColumn}(), {MyTableMap}::getValueSet({MyTableMap}::COL_{MYENUMCOLUMN}));
}
```

**Comment by marcj** [comment]
Guess that's just a limitation of the Sortable behavior. What do you think about sending a PR with [your changes](https://github.com/pimpreneil/Propel2/commit/b7be11b08d5cdb0876b0dd860ceb2f3aa09ffacd)?
