### ISSUE TITLE
Propel2 news

### ISSUE THREAD

**Issue by Lionel09** [propelorm/Propel2#955]
Hello,

First of all, thanks a lot for everybody working on this project, hope Propel will continue to offer an alternative to Doctrine for a long time. 

Now I'm looking for fresh news about Propel2, because the last blog post in from Nov.2014: could you please provide some information about roadmap and/or milestones?
Or in a more simple way, is it really a good idea to choose Propel2 now to start an important project? :)

Many thanks.

**Comment by SourceCode** [comment]
I concur.  As a developer using Propel2 in very large applications I'll let you know that I wouldn't start building something without it.

**Comment by nicklaros** [comment]
Indeed propel2 is powerfull and so easy to use..

**Comment by marcj** [comment]
http://propelorm.org/blog/2015/06/27/propel2-current-state-and-future.html

**Comment by Lionel09** [comment]
"I'm planing now to write every ~two weeks a blog post about what has been done in that data-mapper development, so you're up to date."

It seems you don't reach your goal! ;)

**Comment by marcj** [comment]
Yeah I'm quite busy. :P

**Comment by Lionel09** [comment]
Hi @marcj I understand you're quiet busy but I will really appreciate if you can take some time to explain to the whole world what is the state of art of Propel in this early 2016, because I suppose (and hope) the last blog post is now outdated. Thanks for some fresh news! :)
