### ISSUE TITLE
RFC: What about introduce «typed» collections?

### ISSUE THREAD

**Issue by SCIF** [propelorm/Propel2#956]
Inspired by @Big-Shark idea. We can generate stub collections for each model on «model:build» action.
```php
class BookCollection extends ObjectCollection {}
```
It will allow to replace `ChildArticle[]|ObjectCollection` with `BookCollection` from phpdoc of `find*()` methods. Also, it will allow to restrict returned type if you will use php7 (in user defined functions/methods and in generated Base models).

**Comment by staabm** [comment]
I think we discussed this in the past (there should be an issue somwhere in the tracker). 

I like the idea.

**Comment by SCIF** [comment]
Oh. Sorry, didn't search before create.

Duplicate #266.
