### ISSUE TITLE
fix for #711 breaks the case when phpName is not specified

### ISSUE THREAD

**Issue by miklcct** [propelorm/Propel2#965]
propel2 2.0.0 alpha 5 breaks the following because of the fix for #711 

    <table name="Message">
        <column name="from_id" type="BIGINT" phpType="int" required="true"/>
        <foreign-key foreignTable="Person" onUpdate="cascade" onDelete="restrict"  >
            <reference local="from_id" foreign="id" />
        </foreign-key>
        <column name="to_id" type="BIGINT" phpType="int" required="true"/>
        <foreign-key foreignTable="Person" onUpdate="cascade" onDelete="restrict"  >
            <reference local="to_id" foreign="id" />
        </foreign-key>
        <column name="content" type="LONGVARCHAR" required="true"/>
    </table>

The phpName is supposed to be generated automatically, but the generated names are the same, causing error. Propel should generate random different phpNames for the foreign keys.

**Comment by marcj** [comment]
No, it should not generate random `phpNames`. If you have two foreign-keys pointing to the same table then you have to specify different `phpName`s for each.
