### ISSUE TITLE
Migration from Propel to Propel2

### ISSUE THREAD

**Issue by Lionel09** [propelorm/Propel2#966]
I want to migrate a Symfony2 project (v.2.7.1) from Propel1.7 to Propel2 (currently "alpha 5").

I'm using various Propel behaviors and third party bundles which relies on "Propel" adaptators to correctly work. It will be very helpful for me to have your comments for each behavior / bundle to know if it's trivial to migrate or if difficulties (and which!) could happen...

**Behaviors:**

    Archivable
    NestedSet
    Sluggable
    QueryCache
    Timestampable
    Typehintable (willdurand/propel-typehintable-behavior)
    Equalnest (craftyshadow/propel-equalnest-behavior)
    Geocodable (willdurand/geocoder-bundle)

**Third party bundles:**

    FOSUserBundle
    GlorpenPropelBundle
    FOSElasticaBundle

**Comment by Lionel09** [comment]
a little summary of my research of information...

## Core behaviors

Theses behaviors are in the Propel2 source code, so I suppose it works as in Propel1

```
Archivable
NestedSet
Sluggable
QueryCache
Timestampable
```

## Third-party behaviors

> Equalnest

The author does not seem confident in the compatibility like explained in [this issue](https://github.com/VanTanev/EqualNestBehavior/issues/17). I'll create a new issue to know the state of the art for managing an "equal nest" in Propel2.

> Geocodable

A [PR](https://github.com/geocoder-php/GeocodableBehavior/pull/34) has been done, but no news for a long time...

## Core source

The ```typehintable``` is in the core of Propel2, so it smells good

## Third-party bundles
> FOSUserBundle

Propel2 integration is related to [that issue](https://github.com/FriendsOfSymfony/FOSUserBundle/issues/1787); as the ```typehintable``` behavior is now in the Propel core, I suppose we have to change the schema.xml supplied by default by FOSUserBundle for Propel.

> GlorpenPropelBundle

It seems not compatible for the moment as explained [here](https://github.com/glorpen/GlorpenPropelBundle/issues/6), but I suppose it would be better to discuss all the subjects covered in this fantastic bundle in a dedicated issue to know how Propel2 manage these problematics.

> FosElasticaBundle

Even for  [Propel1](https://github.com/FriendsOfSymfony/FOSElasticaBundle/issues/801), this bundle was a little bit hard to use, I suppose we have to work for Propel2.

**Comment by oujesky** [comment]
Some time ago, I made experimental Propel2 fork of FOSUserBundle here: https://github.com/oujesky/FOSUserBundle/tree/propel2

It is a bit outdated now, but still might serve as a some sort of starting point. (The [schema.xml](https://github.com/oujesky/FOSUserBundle/blob/propel2/Resources/config/propel2/schema.xml) there is still depending on `typehintable` behaviour, which I also forked here https://github.com/oujesky/TypehintableBehavior/tree/propel2, but this is completely unnecessary now)

**Comment by marcj** [comment]
* Archivable - still in v2
* NestedSet - still in v2
* Sluggable - still in v2
* QueryCache - still in v2
* Timestampable - still in v2
* Typehintable (willdurand/propel-typehintable-behavior) - built in, not necessary.
* Equalnest (craftyshadow/propel-equalnest-behavior) - not for v2
* Geocodable (willdurand/geocoder-bundle) - not for v2

**Comment by marcj** [comment]
The migration in general is still easy. Peer classes are now TableMap, namespaces are now included. It isn't that much work, so my forks of Propel v1 behaviors which I made compatible with v2:

* https://github.com/marcj/EventDispatcherBehavior
* https://github.com/marcj/BazingaPropelEventDispatcherBundle

**Comment by marcj** [comment]
If you have further question feel free to ask, but I'm going to close this issue for now as it doesn't include any issue with propel2 itself.
