### ISSUE TITLE
getXXX always returns the first value in the result set (for every value in the result set) when Primary Key is not set for a table

### ISSUE THREAD

**Issue by vyasbhavin** [propelorm/Propel2#976]
Here is my table without a Primary Key (it's a relationship table that maintains a many-to-many relation between primary keys)

<table name="A_SubCat" idMethod="native" phpName="ASubcat">
    <column name="SubCKey" phpName="Subckey" type="INTEGER" required="true"/>
    <column name="CKey" phpName="Ckey" type="INTEGER" required="true"/>
    
    <foreign-key foreignTable="A_Category" onDelete="CASCADE" skipSql="true">
      <reference local="SubCKey" foreign="CKey"/>
    </foreign-key>
    <vendor type="mysql">
      <parameter name="Engine" value="MyISAM"/>
    </vendor>
  </table>

For values 5,6,7 of SubCKey above (where CKey is 1) the following PHP code

$subcategories = ASubcatQuery::create()
  ->filterByCkey(1)
  ->find();
foreach($subcategories as $subcat) {
  echo $subcat->getSubckey()."<br>";
}

prints 5,5,5 (instead of 5,6,7).

Adding primaryKey="true" as below

<table name="A_SubCat" idMethod="native" phpName="ASubcat">
    <column name="SubCKey" phpName="Subckey" type="INTEGER" primaryKey="true" required="true"/>
    <column name="CKey" phpName="Ckey" type="INTEGER" required="true"/>
    
    <foreign-key foreignTable="A_Category" onDelete="CASCADE" skipSql="true">
      <reference local="SubCKey" foreign="CKey"/>
    </foreign-key>
    <vendor type="mysql">
      <parameter name="Engine" value="MyISAM"/>
    </vendor>
  </table>

fixes that bug and returens 5,6,7

I believe the problem lies in getNext() in

/homepages/41/d93423774/htdocs/ormawaken/vendor/propel/propel/src/Propel/Runtime/Collection/CollectionIterator.php

Where it's unable to increment the counter when a Primary Key is not present.

**Comment by marcj** [comment]
> Here is my table without a Primary Key (it's a relationship table that maintains a many-to-many relation between primary keys)

Then you should set both external primary keys as primary key of this table. Tables without PK aren't working correctly.
