### ISSUE TITLE
Duplicate records in query result

### ISSUE THREAD

**Issue by raesche** [propelorm/Propel2#977]
Hi
I want to implement a unix style file permission scheme to define user access rights to some of my records. Now I want to list all files that are either owned by the user or are part of one of his groups. For this, I need to perform a query with two->useXXXQuery() in a  row and an  _or()  to combine two requests. As a result, some of the records are returned three instead of one time. I'm not sure if this is a bug or if I'm doing something wrong.

Here's my Scheme:
![scheme](https://cloud.githubusercontent.com/assets/13539009/9150322/dd4e73fe-3dd3-11e5-95ae-ef48907a3c53.PNG)

And this is the code which finds all files that are accessible by the current user:
![query](https://cloud.githubusercontent.com/assets/13539009/9150327/1e8717cc-3dd4-11e5-8ca4-e768ada21b8a.PNG)

Comments:
Line 135 returns all files owned by the user
Line 139 returns all files that are part of one of his groups
Line 136 should combine the two request above but lead to the problem described
Line 145 is a workaround to eliminate duplicate entries

This is a screenshot of the file list as it should be (using the workaround on line 145)
![filtered](https://cloud.githubusercontent.com/assets/13539009/9150333/aac96a46-3dd4-11e5-969b-e9028fa8aa78.PNG)

And this is a screenshot of the file list as it is returned when not using the workaround:
![duplicates](https://cloud.githubusercontent.com/assets/13539009/9150334/bb2c6a0a-3dd4-11e5-862e-29c0b9b6cbad.PNG)

Please advice.
Thanks & best regards
Rashid

(rashid.talib@rocketmail.com)

**Comment by raesche** [comment]
I forgot to attach the line which calls the read() function:
![call](https://cloud.githubusercontent.com/assets/13539009/9150363/cae5ff50-3dd5-11e5-821c-a8bd85242604.PNG)

**Comment by mpscholten** [comment]
I guess `$record->distinct()->find()` might work :)

**Comment by raesche** [comment]
distinct() works perfect, thanks :-)

I was not aware of this function, but now I found the documentation on http://api.propelorm.org/1.6.0/ModelCriteria.html#method_distinct
