### ISSUE TITLE
Sluggable tables won't generate unique slugs.

### ISSUE THREAD

**Issue by EVILoptimist** [propelorm/Propel2#982]
If a record is created with a NULL slug that would otherwise conflict with another slug in the database (i.e. when you add the "sluggable" behavior to an existing dataset.), a unique slug will never be stored unless it is explicitly defined.

This code WILL create a new slug on a record whose slug is NULL, UNLESS that record's slug conflicts with another record.

``` php
$entity = MyEntityQuery::create()->findOne();
$entity->save();
```

**Comment by EVILoptimist** [comment]
Found out why the slug isn't being updated. See #981.

**Comment by EVILoptimist** [comment]
Pretty sure I've got this one figured out. PR pending feedback #981.

**Comment by dereuromark** [comment]
PR open. Just needs to get finished and merged.
