### ISSUE TITLE
Migrate: Change type of column fails when a foreign key uses that column

### ISSUE THREAD

**Issue by xrm** [propelorm/Propel2#986]
Newest Propel-version, running under Linux with PHP 5.4.41-0

Migration will fail if changing the type of a column in schema.xml while having a foreign key linked to that column.

I had:

```
  <table name="chapter" idMethod="native" phpName="Chapter">
    <column name="id" phpName="id" type="BIGINT" sqlType="bigint(20) unsigned" primaryKey="true" autoIncrement="true" required="true"/>
```

as well as (at some other table):

```
    <foreign-key foreignTable="chapter" name="quiz_list_ibfk_2" onDelete="CASCADE" onUpdate="CASCADE">
      <reference local="chapterId" foreign="id"/>
    </foreign-key>
```

I changed the first part to:

```
  <table name="chapter" idMethod="native" phpName="Chapter">
    <column name="id" phpName="id" type="INTEGER" sqlType="int(11) unsigned" primaryKey="true" autoIncrement="true" required="true"/>
```

Resulting migration-sql says:

```
ALTER TABLE `chapter`
  CHANGE `id` `id` int(11) unsigned NOT NULL AUTO_INCREMENT;
```

But the migration crashes with:

```
  [Propel\Runtime\Exception\RuntimeException]
  Failed to execute SQL "ALTER TABLE `chapter`
    CHANGE `id` `id` int(11) unsigned NOT NULL AUTO_INCREMENT;

  [PDOException]
  SQLSTATE[HY000]: General error: 1025 Error on rename of './smartphone_propel/#sql-915_177d02' to './smartphone_propel/chapter' (errno: 150)
```

It's possible to work around this by first deleting all foreign keys, migrating, changing the field names, migrating again, and finally readding the foreign keys, but probably not very feasible.

**Comment by marcj** [comment]
Have you also changed "chapterId" to `type="INTEGER" sqlType="int(11) unsigned"`? They need to be the same type.

**Comment by xrm** [comment]
Which chapterId?

**Comment by marcj** [comment]
```xml
    <foreign-key foreignTable="chapter" name="quiz_list_ibfk_2" onDelete="CASCADE" onUpdate="CASCADE">
      <reference local="chapterId" foreign="id"/>
    </foreign-key>
```

**Comment by xrm** [comment]
Ah, the remote chapterId. Sorry, I got confused.

Yes, I did change that one as well.

**Comment by marcj** [comment]
Ok, then please post the complete migration file which fails and the reduced (to 2 tables) schema.xml, so I can test it.

**Comment by dereuromark** [comment]
Outdated.
