### ISSUE TITLE
modifications on concrete_inheritance parent do not get propagated to child

### ISSUE THREAD

**Issue by miklcct** [propelorm/Propel2#988]
When I dig an entity using a query class of parent, modify it and save it, the changes do not get propagated to the child, leading database inconsistency.

Assume Child inherit Parent and has a boolean column Foo

```
$child = (new Child())->setId(1)->setFoo(FALSE)->save();
(new ParentQuery())->requirePk(1)->setFoo(TRUE)->save();
$child->reload();
echo $child->getFoo(); // FALSE instead of expected TRUE

**Comment by marcj** [comment]
You should not query and update the parent in the concrete_inheritance scenario because there is no bi-directional update implemented. See the parent only as ID generator and a template where columns get copied to all children.
