### ISSUE TITLE
Weird additional cross join when using table alias

### ISSUE THREAD

**Issue by ChristopheHertigers** [propelorm/Propel2#991]
I'm experiencing weird additional "cross join" statements being generated in addition to the expected "inner join"s.

I'm using the relational api because the real query I noticed this on is much more complex, but I can easily reproduce this with a simple example:
```
BookQuery::create()->join('Author')->where('Author.NAME = ?', 'test')->toString());
```
gives me as expected
```
SELECT  FROM `book` 
INNER JOIN `person` ON (book.AUTHOR_PERSON_ID=person.ID) 
WHERE person.NAME = :p1
```
But with alias
```
BookQuery::create()->join('Author a')->where('a.NAME = ?', 'test')->toString());
```
should give the same query (with an alias) but instead gives
```
SELECT  FROM `book` 
CROSS JOIN `person` 
INNER JOIN `person` `a` ON (book.AUTHOR_PERSON_ID=a.ID) 
WHERE person.NAME = :p1
```
which returns many duplicate rows in a populated database.

Here's a fiddle that reproduces this behaviour:
http://sandbox.propelorm.org/a0c932f

I've only been able to reproduce this when actually setting a where condition on the aliased table, merely selecting columns does not seem to trigger this.

Thanks for having a look!

Cheers,
Christophe

**Comment by nibsirahsieu** [comment]
As per doc said (http://propelorm.org/documentation/reference/model-criteria.html#relational-api)
>
The names passed as parameters in these methods, like 'Book.Author', 'Author.Name', and 'Book.Title', are ''explicit column names''. These names are composed of the phpName of the model, and the phpName of the column, separated by a dot (e.g. 'Author.Name').

Here is the modified version: http://sandbox.propelorm.org/e900ed9

**Comment by ChristopheHertigers** [comment]
Oh my :)
So the problem was that the interpretation is case sensitive? Ok, I didn't think about that.
I used the uppercase notation as above because that's the way is is generated in the constants of the BasePeers, to be honest.

Many thanks for helping,
Christophe
