### ISSUE TITLE
Conditions added in a useQuery block cannot be combined

### ISSUE THREAD

**Issue by TomNoblesse** [propelorm/Propel2#995]
Hello everyone

Currently stuck with a bit of code I'm writing and I don't know whether it's an oversight or just me doing it wrong.

What I want to achieve is an expansion of this example:

http://propelorm.org/documentation/reference/model-criteria.html#combining-several-conditions

Instead of searching one table however, I want to search 2 or more tables.

If you solved a similar issue, would you kindly share some insight on how you did it (alternative solutions welcome!)? Or, if it's a bug then, ... oh well. =)

Thanks!

---
__Propel sandbox:__
http://sandbox.propelorm.org/eed8865

__Desired sql:__
<code>SELECT * FROM `book` INNER JOIN `author` ON (book.AUTHOR_ID=author.ID) WHERE (book.NAME LIKE :p1 AND book.NAME LIKE :p2) OR (author.NAME LIKE :p1 AND author.NAME LIKE :p2)</code>

__Error:__
<code>Fatal error: Uncaught exception 'Propel\Runtime\Exception\LogicException' with message 'Cannot combine unknown condition cond34'</code>

**Comment by gharlan** [comment]
You could do it this way: http://sandbox.propelorm.org/0ff8b49

**Comment by TomNoblesse** [comment]
I could and I shall, because that works perfectly. =p

Thanks for the swift reply!
